### ISSUE TITLE
Changes on go.* files have to pass all Github quality gates

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#1000]
**Description**
Currently a change in one of the `go.*` files (e.g. `go.mod`) is not triggering all quality gates in Github.

This leads to dependency changes which are not verified for potential conflicts in the CLI and can cause to a non-working code base.

**Reason**
Regexp in Prow-pipeline doens't consider chagnes in `go.*` files (see [link](https://github.com/kyma-project/test-infra/blob/main/prow/jobs/incubator/reconciler/reconciler.yaml#L18))

**Comment by jakobmoellersap** [comment]
I think this was fixed by you @Tomasz-Smelcerz-SAP right?
