### ISSUE TITLE
CI/CD: add traceability by adding logging to PROW bash functions

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#1005]
**Description**

The traceability of PROW pipelines is very hard because the logs are seldom giving an indication of the underneath executed bash function.

To solve this gap, each called bash function should print a log message including the function name and provided parameters.

AC:
* Executed bash scripts in PROW are enhanced by printing a log message including the executed function name and the passed parameters (consider https://stackoverflow.com/questions/1835943/how-to-determine-function-name-from-inside-a-function)

**Reasons**

Make PROW pipelines traceable.

**Attachments**

**Comment by jakobmoellersap** [comment]
Affected Pipelines:
- [nightly-main-reconciler](https://status.build.kyma-project.io/?job=nightly-main-reconciler)
- [nightly-main-reconciler-e2e](https://status.build.kyma-project.io/?job=nightly-main-reconciler-e2e)
- [periodic-main-kyma-incubator-reconciler-kyma1-kyma2-upgrade](https://status.build.kyma-project.io/?job=periodic-main-kyma-incubator-reconciler-kyma1-kyma2-upgrade)
- [nightly-main-reconciler-publish-unstable-cli](https://status.build.kyma-project.io/?job=nightly-main-reconciler-publish-unstable-cli)
- [kyma-upgrade-gardener-kyma2-to-main](https://status.build.kyma-project.io/?job=kyma-upgrade-gardener-kyma2-to-main-reconciler-main)
- [kyma-upgrade-k3d-kyma2-to-main](https://status.build.kyma-project.io/?job=kyma-upgrade-k3d-kyma2-to-main)
- [pre-main-reconciler-publish-pr-cli](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/pr-logs/directory/pre-main-reconciler-publish-pr-cli)
- [pre-main-reconciler-cli-integration-kyma-latest-k3d](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/pr-logs/directory/pre-main-reconciler-cli-integration-kyma-latest-k3d)
- [pre-main-reconciler-cli-integration-kyma-main-k3d](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/pr-logs/directory/pre-main-reconciler-cli-integration-kyma-main-k3d)
- [pre-main-reconciler-cli-kyma-prev-to-last-release-upgrade-k3d](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/pr-logs/directory/pre-main-reconciler-cli-kyma-prev-to-last-release-upgrade-k3d)

**Comment by medmes** [comment]
In case of INFO Log level: 
<img width="1627" alt="Screenshot 2022-05-04 at 22 02 05" src="https://user-images.githubusercontent.com/5444554/167088235-9969b0d3-882d-4404-af08-f6b6145178d3.png">

In case of ERROR Log level: 
<img width="1677" alt="Screenshot 2022-05-05 at 19 06 22" src="https://user-images.githubusercontent.com/5444554/167088403-6ebc4581-5463-433a-b36d-8a6410681b88.png">
