### ISSUE TITLE
Implement feature flag for Istio optional upgrade

### ISSUE THREAD

**Issue by mjakobczyk** [kyma-incubator/reconciler#1009]
**Description**

We should be able to toggle Istio optional upgrade feature. As a result, there should be a feature flag controlling this behaviour on mothership reconciler level.

**Reasons**

Possible design flaws or misbehaviour should be easily manageable.

**AC**

- [ ] env var name defined in reconciler and mothership reconciler
- [ ] Istio optional upgrade feature configurable for mothership reconciler

**Attachments**

PR that introduced mothership features configuration:
- https://github.com/kyma-project/control-plane/pull/1506

Exemplary feature flag configuration in KCP dev for all reconciler instances:

```yaml
  global.mothership_reconciler.features: |-
    - name: "LOG_ISTIO_OPERATOR"
      value: "true"
```

Reconciler code that includes feature entries:
- https://github.com/kyma-incubator/reconciler/pull/958/files#diff-4914632202b9c7ee5d0ba5f8d143ba5a91887e66c02f35e1456e912092a9346dR17-R21

See feature issue:
- https://github.com/kyma-incubator/reconciler/issues/926

**Comment by strekm** [comment]
not valid anymore, leaving it closed
