### ISSUE TITLE
Track cluster status in remote Kyma cluster

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#1012]
**Description**

Busola has to be enabled to show the status of a Kyma installation in the UI. Busola has only access to Kyma cluster internal resources which implies that the reconciliation status has to be tracked inside of the Kyma cluster.

Goal is to track for each component a config-map which includes the result of the reconciled component:

* Name
* Version
* Reconciliation result
* Timestamp of last reconciliation
* Label which indicates that the config-map includes a reconciliation summary

AC:
* Each component reconciliation trackes the reconciliation result in config-map in the cluster which includes details of the component reconciliation

** Reason**
Enable Busola to show the status of the Kyma cluster.

**Comment by valentinvieriu** [comment]
Would be great to track in here the overal kyma version too, so we don't have to read it from labels

**Comment by tobiscr** [comment]
That actually a little issue: the Kyma version is for us just the "default component version". But already today can any object have his own version and overwrite the provided Kyma version. So, saying this cluster runs on "Kyma 2.1" means only , that the components in this cluster are using 2.1 as default-version. But we have alreyd other components in the cluster running which use a different version (e.g. SRE components etc.)
