### ISSUE TITLE
Adjust reconciler release process to release component-reconcilers decoupled from mothership

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#1016]
**Description**

The release process of the mothership and component reconciler is currently handled in a way that always both artifacts (container for the mothership-reconciler and the container for each component-reconciler) are generated togeher.

This blocks us from releasing a hotfix for a particular component reconciler which can have massive impacts in case of critical production updates.

AC:
* The existing release mechanism is extended to enable the releasing of just a single component reconciler
* It has to be ensured, that a component reconciler can be released based form a previous released version (e.g. using a branch or tag)
* It has to be ensured that a release component-reconciler is passing all established testing pipelines
* It has to be ensured that the contract between the component reconciler and the mothership reconciler which is running on PROD is compatible (e.g. by releasing them as dedicated GO-module?) 

**Reason**
Allow hotfix releases for component reconciler without releasing any other reconciler service.

**Comment by jakobmoellersap** [comment]
Related to https://github.com/kyma-project/control-plane/pull/1601

**Comment by jakobmoellersap** [comment]
Relates to https://github.com/kyma-project/test-infra/pull/5306

**Comment by janmedrek** [comment]
Functionalities of the Reconciler were migrated to the new architecture, this issue will not be worked on.
