### ISSUE TITLE
Follow-Up SQL-Builder: Use Gorm to query data directly

### ISSUE THREAD

**Issue by jeremyharisch** [kyma-incubator/reconciler#1034]
**Description**
In https://github.com/kyma-incubator/reconciler/issues/851 Gorm was implemented in a way that it is used as a SQL-Builder for our DB layer. Meaning, it is configured in `DryRun` mode, without actually executing the build SQLs.
You can have a look at this PR(https://github.com/kyma-incubator/reconciler/pull/1029) on how it was implemented and configured.

As an improvement we could also use Gorm in the more intended way, meaning we could use the `Find(interface{})` function to actually execute the SQLs directly on our DB. But due to several reason I was not able to test the compatibility with our current transaction implementation. 
We should investigate if we can set gorm up to have it compatible with our Connection interface, to have an even cleaner SQL building and execution solution.

Furthermore, we also need to convert the other places where `NewQuery()` is being used to use the Gorm Query instead. Feel free to do it with this issue, or create another follow-up 👍🏻 

**Reasons**
- Use Gorm in more intended way 
- Remove duplicate query code (Query(), QueryRow(), etc.)
- More lightweight solution

**ACs**
- Run Gorm in normal mode (not DryRun)
- Use `Find` to execute SQLs (Now it was only be used to build the FROM clause)
- Use shared Gorm session, to avoid performance issues
- Load test new implementation

**Comment by janmedrek** [comment]
Functionalities of the Reconciler were migrated to the new architecture, this issue will not be worked on.
