### ISSUE TITLE
Enhance deployment manifest of component-reconcilers to support different image-tags per component-reconciler

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#1035]
**Description**

It has to be possible to use different container images per component-reconciler to gain more flexibility in the rollout approach. It has to be possible to release a new reconciler version but to use this new released container only for a particular component reconciler.

AC:
* Per component reconciler can a different image-tag be used (configurable in see [`values.yaml`](https://github.com/kyma-project/control-plane/blob/main/resources/kcp/values.yaml#L5-L6))
* The [bump-reconciler CI job](https://status.build.kyma-project.io/?job=reconciler-control-plane-image-bump) has to be updated to support this new configuration approach (a bump has to update the version of the mothership reconciler and all component reconcilers)

**Reasons**

Make deployments more flexible to allow the upgrade of single component reconcilers if needed.

**Attachments**

**Comment by janmedrek** [comment]
Reconciler has moved to the new architecture, this issue will not be worked on.
