### ISSUE TITLE
Define API for Provisioner Operator

### ISSUE THREAD

**Issue by janmedrek** [kyma-incubator/reconciler#1047]
**Description**

As described in [this issue](https://github.com/kyma-project/kyma/issues/13759) there will be a new approach introduced when it comes to Kyma provisioning. In order to provide a more declarative approach to the whole flow, multiple new operators will be introduced along with the new CRDs. It is on our side to define what should be included in the `Cluster` CRD in order to contain all the information required for Gardener Shoot provisioning.

Right now the Provisioner exposes the [GraphQL API ](https://github.com/kyma-project/control-plane/blob/main/components/provisioner/pkg/gqlschema/schema.graphql), we can translate it to the CRD, still, unnecessary parts should be omitted not to create too much-unneeded complexity.

**Reasons**

We want to implement declarative cluster provisioning logic.

**Acceptance Criteria**
- [ ] CRD YAML prepared
- [ ] CRD contains all the information required for Shoot provisioning

**Attachments**

[Modular Architecture for Reconcilers](https://github.com/kyma-project/kyma/issues/13759)

We need to consider adding additional options in comparison to the old API, for example, there were requests to provide a way of passing percentage string values for Gardener workers - `maxSurge` and `maxUnavailable` fields.

**Comment by franpog859** [comment]
My work plan: 
- [x] translate one to one the GraphQL API to the CRD
- [ ] add new options, for example `maxSurge` and `maxUnavailable`
- [ ] check the Gardener API and consider adding even more options
- [ ] add validation and constrains as required fields
- [ ] clean up the CRD
- [ ] prepare a short document that describes the proposal of the CRD
- [ ] wait for the review and merge the changes

**Comment by franpog859** [comment]
It's merged and was presented on the k8s operators' sync. I'm closing this issue
