### ISSUE TITLE
Cannot provision cluster with kyma 2.0.4 - istio issue

### ISSUE THREAD

**Issue by hanngos** [kyma-incubator/reconciler#1058]
**Description**
Cannot provision a cluster with kyma version: 2.0.4. Getting istio-related errors:

- `Could not fetch Istio version: Target Prefix could not be found: Target Istio container registry path could not be found in values.yaml`
- `no matches for kind \"Gateway\" in version \"networking.istio.io/v1alpha3\`

See: 
- [Prow pipeline logs](https://storage.googleapis.com/kyma-prow-logs/logs/hanngos_test_of_prowjob_skr-aws-upgrade-integration-dev/1518847432513818624/build-log.txt)
- [Kibana logs](https://kibana-sf-2eaed983-6984-422e-b6a3-2dbf1c1775cc.cls-03.cloud.logs.services.sap.hana.ondemand.com/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now%2Fd,to:now%2Fd))&_a=(columns:!(_source),filters:!(),index:'14462540-9c20-11eb-bfd5-3d4e267b3508',interval:auto,query:(language:kuery,query:'%22a89d6ee0-cb13-4033-a326-2c755d6752bc%22%20and%20%22kind%20%5C%22Gateway%5C%22%20in%20version%20%5C%22networking.istio.io%2Fv1alpha3%5C%22%22'),sort:!()))

Context:
The bug was detected when working on SKR Landscape pipeline `skr-kyma-to-kyma2-upgrade-aws-dev` renamed to `skr-aws-upgrade-integration-dev`, in which kyma input version was changed from 1.24 to 2.0.4.
PRs: https://github.com/kyma-project/test-infra/pull/5293, https://github.com/kyma-project/kyma/pull/14006

It is also related to [this issue](https://github.com/kyma-project/test-infra/issues/5167), where

- Kyma CLI gardener pipeline `kyma-upgrade-gardener-kyma-to-kyma2` was renamed to `kyma-upgrade-gardener-kyma2-minor-versions` and it checks previous minor versions, going back from the latest release.
- a new k3d pipeline to test minor upgrades is introduced.
See those PRs: https://github.com/kyma-project/test-infra/pull/5234 and https://github.com/kyma-project/test-infra/pull/5326.

**Steps to reproduce**
Provision SKR cluster with kyma version 2.0.4.

**Hint**
Check the reconciler version on DEV and PROD or kyma-cli.

**Comment by mjakobczyk** [comment]
Hello @hanngos ! What Kyma CLI version was used for installation of Kyma 2.0.4? What was the k8s version on the cluster?

**Comment by barchw** [comment]
Related PR: https://github.com/kyma-incubator/reconciler/pull/1059

**Comment by jakobmoellersap** [comment]
can this issue be closed? Ideally we can close https://github.com/kyma-project/test-infra/issues/5167 as well

**Comment by hanngos** [comment]
Closing issue - provisioning SKR cluster with kyma version 2.0.4 works.
