### ISSUE TITLE
Istio reconciliation always restart pods with istio sidecar

### ISSUE THREAD

**Issue by veichtj** [kyma-incubator/reconciler#1079]
**Description**
The istio component reconciler applies predefined istio settings to the kyma cluster. Additionally it tries to find pods which do have a different istio sidecar image then the expected one. At the moment this seem not to work, it always finds all pods having a istio sidecar injected and do a rollout restart on the deployment.

**Expected result**
Pods are just restarted if their istio sidecar image is different as the expected one, which is given within the kyma istio chart values.

**Actual result**
Every istio reconciliation loop determines all pods which do have a istio sidecar and rollout restart the relevant deployment.

**Steps to reproduce**

- install a kyma cluster with reconciler, main version
- check pod start date for ory pods
- rerun reconciler for component istio
- check pod start date for ory pods, should have not changed, but it has

**Troubleshooting**

**Comment by cnvergence** [comment]
Issues were identified in performer.go code, there were two issues with manipulating Istio versions on both istio-configuration and istio helm charts.

**Comment by cnvergence** [comment]
Waiting on bumps:
- https://github.com/kyma-project/control-plane/pull/1671
- https://github.com/kyma-project/cli/pull/1264
