### ISSUE TITLE
Reconciler is not considering latest changes after provisioning the PR-version once

### ISSUE THREAD

**Issue by VladislavPaskar** [kyma-incubator/reconciler#1112]
**Prerequisite**

I did some changes to the eventing-controller component. In order to build a new GCR eventing-controller image with these changes, I need to open a PR. This will trigger the `pre-kyma-components-eventing-controller` prowjob. This prowjob pushes the image to GCR. As the second step on every PR, I bump the eventing-controller image in the charts with the freshly pushed image (`PR-1111`). So, there is always a two-step action list:

1. Push the changes to the component and wait for the prowjob to build the image
2. Bump the image in the charts and push the changes.

 **Issue description**

Eventing components also have a [pre-main-skr-eventing pipeline](https://status.build.kyma-project.io/?job=pre-main-kyma-skr-eventing), which provisions Kyma SKR(with PR-version)  using KEB client and executes the eventing fast-integration tests on it. So, the following problem has happened. I pushed the changes to the eventing-controller as the step one of the previous action-list in order to build the eventing-controller image. The `pre-main-skr-eventing` also got executed. It provisioned an SKR cluster with not yet bumped eventing-controller (because the image was still in the building phase). After I pushed the image bump for the eventing-controller, the newly triggered `pre-main-skr-eventing ` was provisioning an SKR again, but with the old PR state without bump. So, starting from that point, the pipeline was testing the old PR state.  

According to @tobiscr, the PR version got cached after the first provisioning via keb client and wasn't updated with the new commits with later provisioner calls.

**Expected result**

Every time an SKR provisioning with Kyma PR-version gets triggered, reconciler must always consider the latest PR changes regardless how many new commits were added. 

**Actual result**

The reconciler "caches" the Kyma PR-version state from the first provisioning call and doesn't consider newer commits on the PR.

**Steps to reproduce**

1. Update the eventing controller and open a PR
2. The `pre-main-skr-eventing ` pipeline provisions SKR and caches the kyma PR-version in the current PR state
3. Wait for eventing-controller image to be built by the `pre-kyma-components-eventing-controller` pipeline, bump the image in the charts and push the changes
4. The `pre-main-skr-eventing` will be retriggered, but the SKR will be provisioned without considering the latest PR-changes (in our case - it's the image bump).

**Comment by janmedrek** [comment]
Reconciler has moved to the new architecture, this issue will not be worked on.
