### ISSUE TITLE
Sidecar injection does not work during istio reconciliation

### ISSUE THREAD

**Issue by veichtj** [kyma-incubator/reconciler#1138]
**Description**

During the the reconciliation run of the istio component reconciler, for a defined time slot the sidecar injection into parallel rolled out deployment does not work. The pods start as usual but without having a istio proxy container attached. So sidecar injection does not work at all. Also the next reconciliation runs do not detect that workloads with missing sidecars. The corrupt pods stay as long till the next rollout of the deployment.

**Expected result**
Sidecar injection works always like the same, parallel reconciliation runs do not affect this at all. Alternatively it is ensured that if there is a workload that did not got a sidecar injected the istio component reconciler can detect that and fix this automatically

**Actual result**
Sidecars are not always injected, once a rollout of a deployment is done during a parallel reconciliation.

**Steps to reproduce**

- provision a k8s cluster (does not matter which one)
- install istio with default profile istio version >= 1.13.x `istioctl install`
- deploy httpbin to a new namespace and label the namespace with `k label namespace httpbin istio-injection=enabled --overwrite`
- check that the httpbin pod has two containers, one is the istio sidecar
- rerun `istioctl install` and in parallel do a `k rollout restart deployment httpbin`
- the httpbin pod will restart without a sidecar

**Troubleshooting**

**Comment by cnvergence** [comment]
Feature was merged, awaiting rollout.
