### ISSUE TITLE
 pre-main-reconciler-cli-kyma-prev-to-last-release-upgrade-k3d failing on Grafana tests

### ISSUE THREAD

**Issue by dariusztutaj** [kyma-incubator/reconciler#1155]
**Description**
Test is failing
_[ERROR] Error when querying Grafana: 503 : no healthy upstream_
It's blocking merging requests, eg. #1145 

**Expected result**
Test finished with success.

**Actual result**
https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-incubator_reconciler/1145/pre-main-reconciler-cli-kyma-prev-to-last-release-upgrade-k3d/1558104649033060352

**Comment by janmedrek** [comment]
The issue has not popped up since then, the pipelines are green (semi). Closing this one.
