### ISSUE TITLE
Failing pre-main-kyma-incubator-reconciler

### ISSUE THREAD

**Issue by barchw** [kyma-incubator/reconciler#1186]
**Description**

The pipeline is failing on https://github.com/kyma-incubator/reconciler/pull/1182 with errors related to linting files not present in the PR

**Expected result**

The pipeline should not fail

**Troubleshooting**

It seems that other files need to be linted for the pipeline to become green

**Comment by kasiakepka** [comment]
The pipelines is failing also for https://github.com/kyma-incubator/reconciler/pull/1185

**Comment by strekm** [comment]
PR: https://github.com/kyma-incubator/reconciler/pull/1188

**Comment by tobiscr** [comment]
PR #1188 got merged.. issue should be solved now.
