### ISSUE TITLE
Connectivity Proxy Reconciler is not able to patch Deployment during chart update

### ISSUE THREAD

**Issue by koala7659** [kyma-incubator/reconciler#1200]
After [upgrade](https://github.tools.sap/kyma/connectivity-k8s-helm-xmake/pull/25) of installed chart of connectivity_proxy to version 2.7.0 we discovered that Connectivity Proxy Reconciler on all environment has started patching all existing installation of connectivity_proxy and failed with following error in the logs. 

`"message":"kubeClient failed to update Deployment 'connectivity-proxy-sm-operator' (namespace: kyma-system)  with strategy 'PATCH': failed to create patch: map: map[] does not contain declared merge key: name","correlation-id":"ab2facd8-f897-4920-8500-1acd8a098da4--973a6ebd-e352-4e7e-807a-888f4b0eb621","component-name":"connectivity-proxy"}`

Incident reported: https://someinternalgithub/kyma/backlog/issues/3062

The problematic deployment that caused the failure has been added in updated chart. It seems there is a bug in the Reconciler that prevents to patch existing chart on the cluster after a new Kubernetes Deployment was added. 

 In the same time the installation of new chart on new Kyma cluster has been completed successfully.

As a result we are not able to deploy new version of connectivity_proxy chart until this issue is solved.
We should:

**1. Find a root cause of the Deployment create patch error and fix it.**

**2. discuss:** 
If we should or not allow to start automatically update all of existing installations when new version is pushed to the repo. This might be a possible security problem for the user and break its existing installation. User can always just uninstall previous version and install the updated one.

**Comment by franpog859** [comment]
The investigation into this topic is ongoing. I found some minor issues but still no main reason why the jobs are created and propagate the secret correctly on the clean Connectivity Proxy `2.7.0` installation but are just not created and everything breaks while upgrading from the `2.4.4` version. I asked @kyma-incubator/jellyfish and @tobiscr for some help and suggestions in this area
