### ISSUE TITLE
Checkmarx has to be added as additional quality gate to the CI pipeline

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#129]
**Description**

Checkmarx is currently not pat of the regular CI pipeline checks. This step has to be added to the CI pipeline of the reconciler.

AC:
* Checkmarx scanner is automatically executed at least once a day for the main branch by a CI pipeline

**Reasons**

Finding of the security threat modelling workshop and required to fulfil security requirements.

**Attachments**

**Comment by suleymanakbas91** [comment]
Done. It will run each working day at 6:30 AM.
