### ISSUE TITLE
Clean up the Connectivity Proxy Reconciler

### ISSUE THREAD

**Issue by akgalwas** [kyma-incubator/reconciler#1363]
**Description**

After the rollout of the CP module, we have to apply final cleanup tasks:

* Remove the following code:
    - Reading binding secret contents, and passing overrides specific to 2.4.4
    - Fixing connectivity-proxy config map
* Remote CP from KEB module list (See https://github.tools.sap/kyma/management-plane-config/blob/main/resources/runtimes/2.20/prod/keb-config.yaml#L39)
* Remove backup files create during the mgiration from CP component to CP module (was used by rollback logic)

**Reasons**
The code that is no longed needed should be removed to achieve a clean CP module state.

**Comment by tobiscr** [comment]
CP module will be rolled out to production on 16th March 2024. After the rollout is completed and 2-3 days of waiting period, we can continue and delete the old CP reconciler.

**Comment by tobiscr** [comment]
Closing as obsolete, will be managed in https://github.tools.sap/kyma/backlog/issues/5268
