### ISSUE TITLE
Connectivity Proxy Reconciler should automatically remove all service-bindings before uninstalling connectivity-proxy 

### ISSUE THREAD

**Issue by koala7659** [kyma-incubator/reconciler#1373]
**Description**

The connectivity proxy reconciler is currently working in a way that it should not be possible to remove connectivity proxy when the user have active OnPremise to Cloud connections via service mappings. User must delete on the cluster all service mappings he created first.

We should automate service mapping deletion process by removing from the cluster all service-mappings the user created as a first stage of uninstallation of connectivity-proxy.   

**Reasons**

This original feature causes problems - there are reported reconciliations errors which are classified as internal incidents. 

Connectivity Proxy will become more reliable and easier to maintain by SRE team.

**Comments**

We consulted Connectivity Proxy development team if the reconciler can safely delete service-bindings from the cluster as part of uninstallation process and they see no any obstacle to do that and we are perfectly fine to proceed. No resource will be left on BTP side.

**Comment by akgalwas** [comment]
This is not planned as the Connectivity Proxy Reconciler will be replaced by the Connectivity Proxy module.
