### ISSUE TITLE
Connectivity Proxy Reconciler should check the presence of Istio resources before installing Connectivity Proxy

### ISSUE THREAD

**Issue by koala7659** [kyma-incubator/reconciler#1386]
**Description**

Connectivity Proxy installation requires Istio to to be installed on the Kyma Cluster.
After the moment when Istio Kyma module is officially enabled it might be possible that Istio might not be present on the Kyma Cluster where Connectivity Proxy is about to be installed. 
That's why before Istio module officially is enabled - we must add Istio pre check in Connectivity Proxy Reconciler as an installation condition.

**Suggested implementation:**

In reconciliation loop we will check for existence of required Istio CRD like Virtual Service and Gateway. If these CRDs are missing we will skip installation without error.

**Comments:**

This must be delivered before Istio module is officially enabled on Canary (in November).

**Comment by tobiscr** [comment]
Closing issue as it got solved in https://github.com/kyma-incubator/reconciler/pull/1403
