### ISSUE TITLE
Respect skip flag in the CRD installer to avoid dirty state while module migration

### ISSUE THREAD

**Issue by a-thaler** [kyma-incubator/reconciler#1387]
**Description**
With https://github.com/kyma-incubator/reconciler/pull/1377 an awesome feature got introduced which allows an component owner to skip reconcilation of the component fully, even if the component is listed in the kyma component list. That gives the freedom to migrate a component to a module not being bound to the kyma release cycle.

Every migration of an existing component to a module will end up using this skip flag feature till the component got removed from the actual kyma version.

Unfortunately the skip flag is not effective for CRDs, resulting in a dangerous in-betwen situation. After the module got rolled-out but the component is not yet removed, the lifecycle manager and the reconciler will race-reconcile the CRDs of the component. That can go well if the versions are exactly the same, however, unforseen dirty effects might happen and more important, the rollout is coupled to the kyma release again. As soon as there are changes to a CRD, you would need to see that both reconcilations will use the same version.

Seeing the implementation, the CRDs are using a component folder structure and could be detected easily. Seeing the relevant [code](https://github.com/kyma-incubator/reconciler/blob/main/pkg/reconciler/service/install.go#L116C2-L), a filter method got introduced already for a more advanced istio use case. So the env variable needs to be read once more in that reconciler part and feeded into the filtering method.

**Reasons**
Avoid the dirty state of having a race-reconcilation, even if all loggs acceptable.

**Attachments**

**Comment by tobiscr** [comment]
PR is https://github.com/kyma-incubator/reconciler/pull/1388

**Comment by a-thaler** [comment]
helm chart adjustments: https://github.com/kyma-project/control-plane/pull/3034

**Comment by a-thaler** [comment]
Was implemented as described
