### ISSUE TITLE
Incorrect StatusURL in response

### ISSUE THREAD

**Issue by rJankowski93** [kyma-incubator/reconciler#175]
**Description**
User can send a few request to mothership reconciler. 
Requests register new cluster, get cluster and get latest cluster return the same struct of response. 
This response contains statusUrl. StatusUrl is correct for request new cluster but fot others is incorrect.  

**Expected result**
Correct StatusUrl for all types of request

**Actual result**
Incorrect StatusUrl for get cluster and get latest cluster

**Comment by tobiscr** [comment]
Seems we have in general a missing option to configure a proper hostname here.. thinking whether we should remove the hostname completely or make it at least configurable (incl. scheme  + port etc.)

**Comment by tobiscr** [comment]
Fix provided in #182
