### ISSUE TITLE
Document resources managed by reconciler

### ISSUE THREAD

**Issue by varbanv** [kyma-incubator/reconciler#179]
**Description**

Provide documentation about resources that will be reconciled by Kyma.
We should document the resource and potentially relevant part of the configuration for each resource. 

**Assignees**

@kyma-project/technical-writers

**Comment by tobiscr** [comment]
With @varbanv  is agreed to create a dump of all resources which have the managed-by reconciler label.

**Comment by tobiscr** [comment]
Labels are added to managed resources.
