### ISSUE TITLE
Implement metrics exporter

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#18]
**Description**

The metrics exporter is responsible to expose to external monitoring systems (e.g. Prometheus from SREs) the list of clusters which are currently in a failure, error or transition state.

These data will be evaluated by the SRE monitoring system and used to reduce false-positive alerts during reconciliation runs. SRE will disable the alerting for a particular time range when a cluster enters a transition state.

Output of the metrics exporter are Prometheus metrics, containing all clusters which are in a transition or error/failure state inclusive the date when the transition state started.

ACs:
* Prometheus metrics has to be exposed over an HTTP socket
* Exposed data have to include all clusters which are in transition/error/failure state inclusive the timestamp when this state started

**Reasons**

Reduce false-positive alerts on SRE side for clusters which are currently reconciled.

**Attachments**

**Comment by suleymanakbas91** [comment]
Metrics endpoint is exposed, and it emits go metrics by default. On top, these three custom metrics have been implemented: 

```
reconciler_reconciliation_status{"cluster_id", "runtime_id", "cluster_version", "configuration_version"} - the status of the reconciliation
reconciler_reconciliation_not_ready_total - total number of clusters currently reconciling or in error/failed state
reconciler_reconciliation_waiting_total - total number of clusters waiting to be reconciled
```
