### ISSUE TITLE
Setup CI pipeline for reconciliation

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#19]
**Description**

Code changes committed to the reconciler repository have to picked up by a CI system (Prow) and trigger a build and unitest/e2e test run.

**Reasons**

Establish CI driven development approach.

**Attachments**

**Comment by suleymanakbas91** [comment]
There are now one pre-submit and one post-submit job which run the `release` target on the Makefile. Prow integration with the repository is also done. This should be enough for now, but, in the future, we can also add e2e integration jobs.
