### ISSUE TITLE
Optimize binary for mothership and component reconciler

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#190]
**Description**

Currently is the mothership and component reconciler bundled into one binary which gets quite huge (>75MB). This could be optimized by generating dedicated binaries for the mothership and another for the component reconciler.

AC:
* Dedicate binaries should be created for mothership and component reconcilers when calling `make build`

**Reasons**

Optimize binary size and reduce resource footprint of the applications.

**Attachments**

**Comment by suleymanakbas91** [comment]
As the first optimization, introducing compiler flags already reduced the binary size by ~20%: https://github.com/kyma-incubator/reconciler/pull/196

**Comment by suleymanakbas91** [comment]
We have now two separate binaries for mothership and component reconcilers: https://github.com/kyma-incubator/reconciler/pull/197. The mothership reconciler binary is around 63MB whereas the component reconciler binary is just 35KB.
