### ISSUE TITLE
Executing 'make docker-push' causes error when running locally caused by invalid image name

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#191]
**Description**

When executing `make all` outside of Prow, an error occurs in the `docker-push` target caused by an invalid image name (see [related code](https://github.com/kyma-incubator/reconciler/blob/main/Makefile#L2)).

The `IMG_NAME` becomes invalid because PROW specific environment variables are undefined.

**Expected result**

Executing `make all` outside of Prow should not lead to invalid image names.

**Actual result**

An invalid IMG_NAME causes an error when executing `make all` outside of Prow.

**Steps to reproduce**

Executing `make all` on a developer laptop will show following error when reaching the `docker-push` target:

     Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
     docker tag reconciler /reconciler:
     Error parsing reference: "/reconciler:" is not a valid repository/tag: invalid reference format
     make: *** [docker-push] Error 1

**Troubleshooting**

**Comment by ralikio** [comment]
Fixed in https://github.com/kyma-incubator/reconciler/pull/198.
