### ISSUE TITLE
Support cluster deletion in reconciler

### ISSUE THREAD

**Issue by rJankowski93** [kyma-incubator/reconciler#200]
**Description**

The reconciler has to offer the option to delete a Kyma installation on a cluster. The design approach to use component reconcilers for component-specific operations has to be reused. Each component reconciler has to be able to modify the regular deletion process by custom hooks (pre, post-hooks etc.).

**AC**

- [ ] A cluster can be marked to be deleted (e.g. new cluster state `delete_pending`)
- [ ] Deletion result should be reflected in cluster status (e.g. by adding states like `delete_error`, `delete_ready`)
- [ ] Deletion of a component has to be be executed by the corresponding component reconciler
- [ ] A component reconciler can inject custom logic which can be executed before, instead of the regular deletion logic or after the deletion (pre-delete-, post-delete, and delete hook etc.).
- [ ] Component reconcilers are sending heartbeats about their deletion status (e.g. in progress / failures / errors etc.)
- [ ] Finally, the deletion of a Kyma created namespace has to happen (but only if no resources created by the customer exist in the namespace).
- [ ] A component reconciler can specify selectors / API groups for resources which will be considered by the default-deletion logic and additionally deleted (only if no custom deletion logic is used)
- [ ]  Quick deletion of resources is supported (deletion by namespace with `--force --timeout 0`) and finalizers (if some resources are not deletable)

**Reasons**

Support of a clean deletion process for KYMA.

**Notes**

**Comment by clebs** [comment]
Hi @rakesh-garimella,
thanks for the feedback on this issue! As we discussed, to solve this problem we would need a garbage collector feature and I have created an issue for it here: #332.

**Comment by clebs** [comment]
Fast deletion mentioned in the AC and by @pbochynski will be done in a separate story as agreed in the team.
The new task to track this can be fond here: #333

**Comment by dariadomagala** [comment]
Hello,

I undeployed and then deployed Kyma again, and the installation failed at the cluster essentials step.
The `cluster-essentials` resources that I have:
```
NAME                                            TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE
service/cluster-essentials-pod-preset-webhook   ClusterIP   100.69.211.246   <none>        443/TCP   84m

NAME                                                    READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/cluster-essentials-pod-preset-webhook   0/1     0            0           84m

NAME                                                               DESIRED   CURRENT   READY   AGE
replicaset.apps/cluster-essentials-pod-preset-webhook-568869cdd6   1         0         0       84m
```
