### ISSUE TITLE
Add CI pipeline to run integration tests for any commits to main branch

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#206]
**Description**

Currently, the reconciler integration tests (triggered when calling `make test-all`) are not executed when merging new features to main-branch.

We need urgently a Prow  pipeline which

1. creates a dedicated Kubernets cluster (e.g. K3d cluster running on a VM instance etc.)
2. runs the reconciler integration tests

Only if the pipeline succeeds, PRs to main branch can be merged.

AC:

* dedicated Prow pipeline is implemented to run reconciler integration-tests
* pipeline has to be triggered before a PR can be merged to main-branch of reconciler repository
* this pipeline is a hard quality gate in Github and merges are only allowed if the pipeline succeeded successfully
* the pipeline executes the integration-tests of the reconciler (e.g. by calling `make test-all' )
* the tests are epxecing a pre-configured `KUBECONFIG` env-variable - it should point to a dedicated K8s cluster (e.g. running on a temporarily created VM instance)
* After the test is executed, any created additional resources (e.g. VM instances) have to be properly erased (cost reduction)

**Reasons**

Establish extended functional tests before merging to main branch.

**Attachments**

**Comment by suleymanakbas91** [comment]
https://github.com/kyma-project/test-infra/pull/4200

**Comment by suleymanakbas91** [comment]
With kyma-project/test-infra#4200, `pre-main-reconciler-integration-k3d` job has been created and made mandatory for all the PRs.
