### ISSUE TITLE
Add throttling mechanism to limit the amount of fire request/sec to Kuberentes API server  in component reconciler

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#237]
**Description**

To be reduce the amount of requests fired to a Kubernetes API server, the amount of requests per seconds have to be configurable. A throttling mechanism is required, which ensures that a particular threshold won't be exceed during the reconciliation of a Kyma component.

Goal is to avoid quotas or being able to reduce the load on clusters with a low-performing API server.

IT's recommended, to add such a throttling to the Kubernetes-Client API ([see here](https://github.com/kyma-incubator/reconciler/tree/main/pkg/reconciler/kubernetes/adapter)). It should make sure that it's not firing more requests as configured per second. 

AC:

* Threshold of fired requests/sec is configurable per component-reconciler
* The Kubernetes client is taking care, that its not sending more requests as defined per second.

**Reasons**

Give more control of the amount of fired requests to the Kubernetes API server.

**Attachments**

**Comment by janmedrek** [comment]
Functionalities of the Reconciler were migrated to the new architecture, this issue will not be worked on.
