### ISSUE TITLE
Reconciler doesn't report failures properly

### ISSUE THREAD

**Issue by pbochynski** [kyma-incubator/reconciler#240]
**Description**

Permanent failures caused by chart misconfiguration should be reported and should stop `kyma deploy` command (or at least return failure exit code).
If you disagree and you want the reconciler to finish other components despite permanent make such behavior optional (e.g. `--ignore-failures` flag)

**Expected result**
When some kyma can't be deployed process should **exit with error code** and the execution of pipeline should be **stopped**.

**Actual result**

This is the output from the installation that failed:
```
2021-10-07T15:48:21.400Z	INFO	step/log.go:62	Kyma deployed successfully!
2021-10-07T15:48:21.400Z	INFO	step/log.go:62	Install Kyma certificate locally

Kyma is installed in version:	local
Kyma installation took:		0 hours 9 minutes
Kyma is running at:		grdxr6zqo.kyma-prow.shoot.canary.k8s-hana.ondemand.com
```

Example 1:
https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/12300/pre-main-kyma-gardener-azure-alpha-eval/1446135613949480960/build-log.txt (broken logging chart)

Example 2:
https://storage.googleapis.com/kyma-prow-logs/logs/kyma-integration-k3d-compass-dev/1445993681881403392/build-log.txt (not existing chart)

**Comment by tobiscr** [comment]
> Hint for the fix: after the worker-pool is finished, all operations of the reconciliation have to verified (this step should happen here: https://github.com/kyma-incubator/reconciler/blob/main/pkg/scheduler/service/run.go#L105). Logic from Bookkeeper can be reused (see [reconciliationResult](https://github.com/kyma-incubator/reconciler/blob/main/pkg/scheduler/service/bookkeeper.go#L139) entity).
> 
> If one or more operations are in error state, return an error (please add the error-message of these operations to the returned error so that the caller gets the information why the ops were failing).

We agreed with @skhalash to return instead of an error a result entity which includes all details about the reconciliation:

* all applied operations incl. their results
* the aggregated result of the reconciliation

The reconciliationResult entity could be use for such purposes by making it public.
