### ISSUE TITLE
Istio-reconciler doesn't apply any changes for the same version of istio

### ISSUE THREAD

**Issue by pbochynski** [kyma-incubator/reconciler#247]
**Description**

Istio reconciler doesn't apply the configuration passed to the component istio-configuration when istio in the current version is already installed (update operation).
See the fragment of canUpdate function that returns `false` if istio is installed in the same version:
https://github.com/kyma-incubator/reconciler/blob/1d6082e73f9d679047a36c566443aa03c6ee15c6/pkg/reconciler/instances/istio/action.go#L169-L172

**Expected result**

When configuration applied in the cluster is different than the one provided to the reconciler `istioctl upgrade` command is invoked. Some configuration verification happens (e.g. https://istio.io/latest/docs/setup/install/istioctl/#verify-a-successful-installation)

**Actual result**

Configuration passed to istio-reconciler is ignored.

**Steps to reproduce**

```
kyma deploy
kyma deploy --value istio-configuration.components.ingressGateways.config.service.loadBalancerIP=${GATEWAY_IP_ADDRESS}
```
And check the configuration of istio ingress gateway service.

**Comment by mjakobczyk** [comment]
CLI has been bumped and stable release has been made.
