### ISSUE TITLE
K3d CI pipeline has in case of failures to dump all pod logs

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#251]
**Description**

We are recognising flacky tests and their analysis can be very hard if no logs of the pod are available. 

To mitigate this problem, the K3d CI pipeline should in case of a failed test-run dump all logs of the pods before destroying the cluster.

AC:

* If the `make test-all` command failed, the pipline connects to the K8s cluster and dumps all logs of the pods

**Reasons**

Enable analysis of failing `make test-all` runs

**Attachments**

**Comment by janmedrek** [comment]
Functionalities of the Reconciler were migrated to the new architecture, this issue will not be worked on.
