### ISSUE TITLE
Kitbag: simple simulation of failing reconciliations / operations

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#268]
**Description**

In cases of failing reconciliation or failing operations, our operational tooling (KCP CLI + Reconciler CLI) should support the analysis as much as possible.

**=> Use Kitbag for applying it**

Feature for the Reconciler CLI:

* The Reconciler CLI has support the execution of a reconciliation run by the cluster configuration as parameter (e.g. by enriching the `./bin/mothership mothership local` command to accept provided `cluster.State` definitions), like `./bin/mothership mothership local --cluster '{json-definition-of-the-cluster-state}' --kubeconfig <stringToKubeconfig> ...` (cluster can also be passed as file if's simpler to handle)

Feature in Kitbag:

* retrieve cluster entity as JSON from KCP CLI and store it as file in temporary folder
* if user wants to simulate just a single operation, drop all other components from the cluster JSON
* show the user the JSON and ask whether it contains any sensitive configuration data: if NO, proceed otherwise open VIM for editing it
* call `mothership local` command and pass cluster entity as JSON to it

AC:
* Kitbag provides a convenient way to simulate locally a failed reconciliation by providing just the scheduling-ID
* Kitbag provides a convenient way to simulate locally a failed operation by providing just the correlation-ID
* User can verify the retrieve cluster-JSON for sensitive data before it's triggering the local reconciliation run

**Reasons**

Simplify debugging and reproduce failing reconciliations/operations.

**Attachments**

**Comment by kwiatekus** [comment]
@tobiscr Any ideas fro cluster specific config?

I.e domainName configuration will not be apliable on SRE troubleshhoting runtime

**Comment by kwiatekus** [comment]
As agreed last friday we will try to include [kitbag](https://github.tools.sap/I539990/kitbag/tree/master) in the tooling for operators. 
@tobiscr 
I wonder if we should wait with this one until kcp-cli is already kitbag-enabled module

**Comment by jeremyharisch** [comment]
All PRs are merged, can this be clsoed?
