### ISSUE TITLE
Istio reconciler - delete action

### ISSUE THREAD

**Issue by strekm** [kyma-incubator/reconciler#271]
**Description**

As Istio component is installed via istioctl binary it should have also action to remove istio from a cluster. Istioctl is used to delete istio:
`istioctl x uninstall <your original installation options> --purge` (experimental feature)
or
` istioctl manifest generate <your original installation options> | kubectl delete -f -`

AC:
- [x] istioctl is used to delete istio
- [x] istio-system namespace is deleted
- [ ] istio resources are not blocking ns deletion
- [ ] delete additional resources (dashboards, destination rules and so on)

**Reasons**

Istio as a part of kyma should be gracefully removed as a part of kyma deletion.

**Attachments**

https://istio.io/latest/docs/setup/install/istioctl/

**Comment by strekm** [comment]
waiting for feedback how to integrate test it, initial review done

**Comment by strekm** [comment]
applying review fixes

**Comment by veichtj** [comment]
Successful retest on SKR
