### ISSUE TITLE
Enable access to the overrides sent to the component

### ISSUE THREAD

**Issue by mjakobczyk** [kyma-incubator/reconciler#272]
**Description**

Please consider the following scenario:
_As a developer / As a cluster admin, I want to know what overrides were sent to the component for reconcilation._

**Reasons**

Without information about overrides a developer can not simply reproduce the problem of component reconciliation failure.

**Attachments**

N/A

**Comment by tobiscr** [comment]
Such data will become available via KCP CLI (see https://github.com/kyma-incubator/reconciler/issues/433).
