### ISSUE TITLE
Create operational documentation (troubleshooting guides etc.)

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#275]
**Description**

The reconciler requires a detailed documentation how trouble shooting has to happen and how issues can be analysed.

This has to include issue with the reconciler itself but also problems caused by the reconciliation.

**Area**

Internal documentation

**Reasons**

Required for operational readiness.

**Assignees**

@kyma-project/technical-writers
@tobiscr 

**Attachments**

**Comment by tobiscr** [comment]
Relates to https://github.tools.sap/kyma/backlog/issues/1390

**Comment by tobiscr** [comment]
* Operational test cases are [tracked in the Wiki](https://wiki.wdf.sap.corp/wiki/display/kyma/Reconciler+operational+test).
* Troubleshooting guides and test protocols are available in the [documentation repository](https://github.tools.sap/kyma/documentation/tree/main/on-call-guides/runtime-4).

**Comment by ruanxin** [comment]
The issue for test case 19: #466
