### ISSUE TITLE
Add cluster status ' skipped'

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#277]
**Description**

Cluster configurations which will never be reconciled (because they got faster outdated as they could be reconciled) should receive the cluster status `skipped` instead staying endless in `reconcile_pending` status.

The change to the `reconcile_skipped` status should happen by the cluster-inventory (inside one DB-transaction):

1. query for cluster-status which are set to `reconcile_pending` for the particular cluster (SQL pseudo statement: `select * from inventory_cluster_config_statuses where status='reconcile_pending' and cluster_version=123`)
2. create for each `cluster_config` a new status which is `reconcile_pending`

AC:
* A new cluster version provided by KEB will update the status of any other cluster-configurations which are in status `reconcile_pending` to `reconcile_skipped`

**Reasons**

Simplify analysis for human users.

**Attachments**

**Comment by janmedrek** [comment]
Functionalities of the Reconciler were migrated to the new architecture, this issue will not be worked on.
