### ISSUE TITLE
Merge InventoryWatcher into Scheduler

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#279]
**Description**

The `InventoryWatcher` struct should be merged into the `Scheduler` and finally be remove. As components in the current architecture are pulling repositories without using dedicated Watcher entity: the same approach should also be used for the scheduler.

AC:

* `Scheduler` is pulling `ClusterInventory` directly without using a Watcher
* `InventoryWatcher` is not longer used and related code is deleted

**Reasons**

Align approach for pulling date from repositories in `Scheduler` to reduce complexity and establish a consistent approach for gathering data changes.

**Attachments**

**Comment by janmedrek** [comment]
Functionalities of the Reconciler were migrated to the new architecture, this issue will not be worked on.
