### ISSUE TITLE
Create CI pipeline to generate nightly CLI builds which are using always the latest reconciler API version

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#283]
**Description**

A CI pipeline is required which generates each night a build of the Kyma CLI which is using the latest available reconciler API version. The CLI has finally to be verified whether it's compiling and also a short sniff test of the deploy/undeploy command has to happen.

AC:

The new CLI job was to cover following steps:

   1. Create CI job which upgrades the Kyma CLI to use the latest reconciler API version and builds the Kyma CLI binary 
   2. Run the CLI deploy / undeploy command (e.g. by using a K3d cluster) which installs KYma on a cluster
   3. Run the fast integration tests for Kyma
   4. Uninstall Kyma via the CLI
   5. If the deployment, testing and deletion was successfully finished, the upgrade of the reconciler API has to be pushed to the Kyma CLI main branch

**Reasons**

* Establish nightly integration between CLI and reconciler API to identify breaking changes immediatelly

**Attachments**

**Comment by pxsalehi** [comment]
If the job succeeds, the CLI builds are uploaded to https://storage.googleapis.com/kyma-cli-unstable

**Comment by tobiscr** [comment]
QQ: are the pipelines (`nightly-main-reconciler-publish-unstable-cli`) already published on PROW?
