### ISSUE TITLE
Istio reconciler - wait for proxies after reset

### ISSUE THREAD

**Issue by mjakobczyk** [kyma-incubator/reconciler#294]
**Description**

Istio component reconciler should not finish upgrade reconciliation action after performing proxies reset before making sure that all the objects that were supposed to be restarted are ready.

**Reasons**

Istio resets proxies from the cluster that can be in any namespace. If any next component relies on objects that contain proxies they not be healthy and ready.

**Attachments**

Active waiting should be implemented only in the upgrade part after performing reset in `pkg/reconciler/instances/istio/action.go:75`:

```go
err = a.performer.ResetProxy(context.KubeClient.Kubeconfig(), ver, context.Logger)
if err != nil {
	return errors.Wrap(err, "Could not reset Istio proxy")
}
```

**Comment by strekm** [comment]
working on making tests green

**Comment by cnvergence** [comment]
Also we have created an follow-up issue: https://github.com/kyma-incubator/reconciler/issues/348

**Comment by cnvergence** [comment]
In the meantime, there was another feature developed by the Reconciler team, we should take a look at: #369
