### ISSUE TITLE
OpsTest Finding: Add support for autoscaling to reconcilers

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#310]
**Description**

Depending on the saturation of the resources, another pod should be started for mothership or component reconciler.

For all reconcilers is the saturation of the worker pool relevant + CPU/RAM allocation. For the mothership has the max-scaled pods limit to be defined by considering the max. amount of open connections defined on Postgres side (to avoid more open connections than the DB is able to handle).

AC:

* Trigger for creating another replica is based on resource saturation of the pod and on the number of available workers in the worker pool (have a loon on https://keda.sh/)
* Downscaling has to happen after a pod was >5min below the defined saturation levels
* Max. scaled pods of mothership reconciler has to be defined based on the max. open connection limit of the Postgres DB. Max. number of replicas can be be calculated using the max-DB connection limit and the DB-connection pool size per pod: `max replicas = floor(max connection limit of DB / connection-pool size per pod)`

**Reasons**

Scale application depending on given load.

**Attachments**

**Comment by tobiscr** [comment]
For testing this feature the implementation of #329 is required.

**Comment by janmedrek** [comment]
Functionalities of the Reconciler were migrated to the new architecture, this issue will not be worked on.
