### ISSUE TITLE
Setup E2E CI pipeline for reconciler

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#32]
**Description**

The reconciler has to be executed continuously and end2end tests have to be executed.

The test should include:

1. Create a new cluster in Gardner
2. Simulate the KEB REST-call to the reconciler and register the cluster in the reconciler's inventory
3. Wait until reconciler installed Kyma on the new cluster: in between, check the /metrics-URL of the reconciler, the amount of clusters in transition has to increase / decrease (after cluster was reconciled)
4. Modify Kyma resources on the cluster and wait for reconciliation of them
5. Simulate the KEB REST-call for the reconciler and upgrade the cluster in the reconciler's inventory
6. Wait until the reconciler upgraded Kyma on the cluster
7. Simulate the KEB REST-call to the reconciler and delete the cluster in the inventory
8. Modify Kyma resources on the cluster and ensure reconciler won't revert the change
9. Erase the created cluster in Gardener

**Reasons**

Continuous testing as best practise development approach.

**Attachments**

**Comment by suleymanakbas91** [comment]
The skeleton of the job is ready: https://github.com/kyma-project/test-infra/pull/3907. It only provisions a Gardener cluster, builds and runs the reconciler for now.

**Comment by suleymanakbas91** [comment]
Will be implemented in https://github.com/kyma-incubator/reconciler/issues/75.
