### ISSUE TITLE
OpsTest: Detect enc-key changes which lead to non-decryptable db-rows during mothership bootstrap

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#321]
**Description**

The mothership has to verify whether the provided encryption-key was changed without having a clean rotation of existing encrypted values to the new key. If such inconsistency is detected, the bootstrap of the mothership reconciler has to fail.

AC:

* A flag can be set on the CLI to enable the enc-key consistency check
* The consistency check is verifying whether the provided enc-key can be used to decrypt an encrypted value
* If one key could not be decrypted, the bootstrap has to fail with a clear error message

**Reasons**

Detect changes of encryption-key without applying a proper enc-key rotation up-front.

**Attachments**

**Comment by janmedrek** [comment]
Functionalities of the Reconciler were migrated to the new architecture, this issue will not be worked on.
