### ISSUE TITLE
Change reconciler logic to replace kubernetes resources instead of patching them

### ISSUE THREAD

**Issue by varbanv** [kyma-incubator/reconciler#330]
**Description**
Change the logic to use replace instead of patch method when updating kubernetes resources.

**Reasons**
Currently, we update kubernetes resources by patching them using the desired configuration. However, we have identified cases, where an annotation created on a resource outside of the reconciliation process can break the cluster and patching the affected resource does not fix the problem because it doesn't remove the annotation. 
That is why we need to switch to replacing the resources to make sure any additional modifications are actually removed.

**Attachments**

**Comment by m00g3n** [comment]
Can we consider a different approach to solve annotation/label problem?
The switch from `patch` to `replace` may not be needed.

**Comment by pbochynski** [comment]
The patch cannot be used in the reconciler as it undermines the fundamental principle of reconciliation. We need to bring cluster to the desired state. With `patch`, you cannot achieve it at all. Take another example that popped up today:  https://github.com/kyma-project/kyma/issues/12543
