### ISSUE TITLE
High severity vulnerability reported for istio component reconciler

### ISSUE THREAD

**Issue by varbanv** [kyma-incubator/reconciler#331]
**Description**

High severity vulnerability for Command_Injection/pkg/reconciler/instances/istio/istioctl/commander.go:204-171

**Comment by mjakobczyk** [comment]
In Istio Reconciler we need an istioctl binary. We pass it as a path to the executable binary in such format: https://github.com/kyma-incubator/reconciler/blob/f4d5fef837f38fdddc15e8ed52d524b3f822ee1b/pkg/reconciler/instances/istio/istioctl/commander.go#L204
In Kyma SKRs path to the `istioctl` is set in stone in Dockerfile, from which containers are ran. In open-source Kyma we export the ENV to the desired binary that we have on our local machine.

This vulnerability considers `OS Command Injection`.

**Comment by mjakobczyk** [comment]
Summary:
- in SKRs scenario we download `istioctl` binary on-the-fly when spinning up new container from our image so there is no way to replace it anyhow (we store out images in our registry and have control what they are like)
- in open source scenario Kyma CLI downloads `istioctl` binary on-the-fly on basis of what the input `Istio-configuration` chart is (downloading version matching the one from the chart) and there is no way to override this binary for example using my own, custom exposed env from the shell @jeremyharisch 

If these are are true then in my opinion we are not exposed to any external malicious command execution through injecting binary.

**Comment by jeremyharisch** [comment]
@mjakobczyk Since, I was only involved in the CLI part of this topic, I can only confirm it for the CLI scenario

**Comment by strekm** [comment]
@varbanv it was discussed with security expert that this situation is not a thread for us. i think we can close this one

**Comment by PK85** [comment]
Security dashboard looks ok, closing
