### ISSUE TITLE
Garbage collector

### ISSUE THREAD

**Issue by clebs** [kyma-incubator/reconciler#332]
**Description**

Often clusters have orphaned resources that can not be reconciled nor deleted by the reconciler since they lost the connection to the chart they belong to and can't be properly identified.

***Example:***
A pod belonging to a deployment in a chart looses the selector label/s (usr accidentally deleted them). IN this case the reconciler will reapply the deployment resulting in a new pod although the old one is still running.

***Proposal:***
Create a garbage collector feature that is capable of cleaning up orphaned resources before/after a reconciliation. A proposed idea would be to use annotations to mark resources as "created by reconciler" and then analysing them.

**Reasons**
Orphaned resources should be removed from a cluster when a reconciliation/deletion happens to ensure correct functioning of Kyma and not waste compute power.

**Comment by tobiscr** [comment]
Could become part of #333

**Comment by tobiscr** [comment]
Related to #367

**Comment by clebs** [comment]
Issue is no longer valid in the operator based reconciliation model.
