### ISSUE TITLE
Deletion reconciler: enable clean deletion of a Kyma installation

### ISSUE THREAD

**Issue by clebs** [kyma-incubator/reconciler#333]
**Description**

The deletion of Kyma has to happen in multiple steps of following sequence:

1. [delete-cr] Call deletion reconciler: remove custom resources
2. Call all component reconciler and 
     1. let them delete their manifests/execute custom deletion logic
     2. delete CRDs (done by base-reconciler)
3. [delete-ns] Call again deletion reconciler again and remove namespaces: if they don't get deleted after a timeout, remove finalisers and enforce deletion of namespace

AC:
* Deletion of Kyma removes all Kyma managed resources (incl. CRDs, CRs and any deployed resource)
* After deleting all Kyma resources, a new installation can Kyma is possible without any additonal steps

**Reasons**

Enable proper uninstallation of Kyma on a cluster.

**Comment by tobiscr** [comment]
Hint from PB:

* `undeploy --force --timeout 0`
   - delete all resources from all apigroups with kyma (plus other well known). Actively remove finalizers

**Comment by tobiscr** [comment]
Caused by current time pressure, it would be good to have following functionality in the first PR:

1. Deletion reconciler is called at the end of the regular deletion
2. Deletion reconciler is executing the existing deletion logic which the Kyma CLI is using

In next iteration, it would be great to get the flow as described in the ticket i place.

**Comment by tobiscr** [comment]
Current status:
  - @Tomasz-Smelcerz-SAP  : Move CLI delete leftovers logic to reconciler:
        - no longer need to delete the `istio-system` namespace
        - No longer need to delete CRDs manually in custom logic
        - Add `kyma-system` hack
      - @clebs : Open CLI PR (needs reconciler bump only) and should work once the reconciler is ready
      - @tobiscr :
          - Merge Tomasz’s PR
          - Bump reconciler in CLI PR
          - Merge CLI PR
