### ISSUE TITLE
In cluster read-only config

### ISSUE THREAD

**Issue by clebs** [kyma-incubator/reconciler#334]
**Description**
The configuration applied to each component on a reconciliation needs to be stored in the cluster as a readonly secret.

The current implementation proposal is having the component reconciler runner write the configuration of a component after it has been successfully reconciled into a predefined secret.
The secret will contain a map for which each key contains the configuration of one component.

For this feature, security and privacy restrictions have to be considered and redacted out of the readable config.

**Reasons**
- Enable clients that do not have access to the reconciler to apply the configuration should something go wrong.
- Historical data for analysis purposes.
- Transparency for customers so they can see what exactly was installed in their clusters.

**Comment by tobiscr** [comment]
Would be good to encrypt the infomration stored on the SKR cluster so that its not public readable anymore.

For clusters which are are installed via KYma CLI, we store the encrption-key inside of the cluster. For managed clusters (SKrs) the key is not stored in the cluster and part of the cluster-configuration of the reconciler so that customers cannot read these information.

**Comment by clebs** [comment]
As discussed, the solution consists of the following steps after a successful reconciliation:
1. Create a JSON representation of the config
2. Create a new encryption key
3. Encrypt the config and store it in a secret in the cluster with a reference to its corresponding clusterConfigID
4. Inventory stores the encryption key accordingly (on the cluster itself in case of Kyma CLI)

**Comment by tobiscr** [comment]
Hint from PB:

* Reconciler produces last applied configuration as a secret (because it contain sensitive data) - it can be used for constructing values for kyma deploy command, but it is not read by reconciler (write only)

**Comment by tobiscr** [comment]
Agreement on the implementation:

**Changes in code:**
1. Move Encryption logic from Bookkeeper to Reconciler (to store config per component)
2. Enhance cluster model: add ”Backup Key” field (do not store it in IN DB!)
3. Enrich the model used between mothership-reconciler and comp-reconciler (add „Backup Key“ to it)

**Flow in CLI Use-Case:**
1. Retrieved Backup-Key from HOME directory  or passed via CLI parameter
    * If no key can be found (either in HOME directory or via CLI param): create new enc-key 
2. Check if MD5-checksum of Backup Key (stored in secret in cluster, see step3) is matching provided BackupKey 
   * 1. If MD5-checksum does not exist in cluster:  Add Checksum of BackupKey to secret if missing (to verify that later provided backup-keys are valid) 
3. CLI sets cluster-model flag “Backup Key” 
4. Comp-reconciler checks if „Backup Key“ is defined: 
    1. If No: do nothing 
    2. If Yes:
        * Create secret if missing
        * Add cluster-config to the secret: „component-name = compConfigAsSha256string“

**Comment by tobiscr** [comment]
Another proposal for detecting the resources we have to delete is to use label-selectors.

**Comment by tobiscr** [comment]
Extension for #1012
