### ISSUE TITLE
Support for removing resources absent in the new version of the component manifest set

### ISSUE THREAD

**Issue by ebensom** [kyma-incubator/reconciler#344]
**Description**

reconciler shall support cleaning up resources which were present in the previous, persisted component manifest set, but are absent from the new applied version of the manifest set.

Scenarios where this functionality is relevant:

1. Let's assume in ory component, there was Deployment called `ory-temp` . Now in the new version of Kyma, this deployment does not exist any more in the ory component chart, and hence in the rendered manifest. This resource shall be removed by reconciler after applying the new manifest set.
2. In the new version of Kyma component, a Deployment called `oldname/kyma-system` has been renamed to `newname/kyma-system` . Calling replace and/or create will create the new Deployment with newname for sure, reconciler should detect that the Deployment called `oldname` is not in the rendered manifest set any more, and delete after applying the new manifest set.

**Comment by pbochynski** [comment]
We should not delete resources without explicit statement. See my comment here: https://github.com/kyma-incubator/reconciler/issues/200#issuecomment-949431745
Renaming, removing can be handled also by component reconciler.
