### ISSUE TITLE
Istio reconciler - Istio Proxy Reset should handle other update strategies

### ISSUE THREAD

**Issue by cnvergence** [kyma-incubator/reconciler#348]
**Description**

Currently Istio Proxy Reset expects that every k8s objects have Rolling Update strategy, we should decide whether we want to handle other strategies or just skip executing on those.

**Reasons**

**Attachments**

**Comment by tobiscr** [comment]
@strekm  / @cnvergence : Based on the ticket description, it's not yet decided whether this ticket has to be implemented. Is here anything open or can we close the ticket?

**Comment by strekm** [comment]
@tobiscr this ticket is related to istio reconciler, which handles workloads restarts after istio bump and it is valid.

**Comment by strekm** [comment]
istio reconciler will be reworked into istio manager
