### ISSUE TITLE
istio reconciler should support downgrades

### ISSUE THREAD

**Issue by strekm** [kyma-incubator/reconciler#365]
**Description**

At this moment istio reconciler is not supporting downgrades. This can lead to situation that on managed kyma customer can bump istio to newer version before kyma supports it. In such situation istio reconciler should downgrade istio to istio supported in kyma. 

AC:
- [x] istio downgrade is supported within one minor version

**Reasons**

Reconciler should always apply desired state, in this case managed kyma istio.

**Attachments**

**Comment by raypinto** [comment]
Cli is bumped. Tested with the kyma-cli and it works as expected!
