### ISSUE TITLE
kubeClientAdapter delete does not delete namespace specific objects

### ISSUE THREAD

**Issue by veichtj** [kyma-incubator/reconciler#367]
**kubeClientAdapter delete does not delete namespace specific objects**

For the istio reconciler component we used the kubeClientAdapter.delete() method to clean up all istio related objects like grafana dashboards, a part of the objects is located in the istio-system namespace and the other part relates to kyma-system namespace.
When calling the delete() method we pass the istio-configuration chart manifest with all that objects, as namespace we pass "istio-system". We would have assumed that the delete cleans up all objects within the manifest, but it does only delete those who having the given namespace ("istio-system"). 

**Expected result**
All objects within the manifest gets deleted, not only those matching the passed namespace

**Actual result**

**Steps to reproduce**

- Check out https://github.com/veichtj/reconciler.git switch to branch istio-uninstall-test
- configure your path to ISTIOCTL and verify your kubeconfig 
- run test cmd/reconciler/start/service/integration_test.go  
- ConfigMap istio-service-grafana-dashboard should be deleted, it is part of the istio-configuration chart, but not located in istio-system namespace
  

**Troubleshooting**

The istio component reconciler calls the kubeClientAdapter.delete() two times, one time for istio-system and once for kyma-system namespace to clean up all istio related objects

**Comment by tobiscr** [comment]
could become obsolete when #600 is ready - will leave ticket open to verify that this behaviour is supported with the new deletion mechanism.

**Comment by tobiscr** [comment]
Will be solved with #600
