### ISSUE TITLE
OpsTest: Validate configuration of mothership and component reconciler during bootstrapping

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#377]
**Description**

The mothership and component reconcilers have to validate their configuration during the bootstrap (check for in-proper values etc.) and fail if the validation was not successful with a clear error message.

AC:

* The allowed value for each configuration value is documented in code
* The different configuration parameters are reviewed by the developers and validation rules are defined for the value
* During the bootstrap (e.g. in MS-reconciler it can be done by the Runtime builder) of the component, the configuration-values are validated. An error is fired in case of an invalid value.

**Reasons**

Fast response in case of a misconfiguration.

**Attachments**

**Comment by janmedrek** [comment]
Functionalities of the Reconciler were migrated to the new architecture, this issue will not be worked on.
