### ISSUE TITLE
Code generator: call them in Docker containers or install them automatically

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#386]
**Description**

Currently the Makefile expects the code generator tools ([oapi-codegen](https://github.com/deepmap/oapi-codegen), [spectral](https://github.com/stoplightio/spectral) ) to be installed on the local machine.

For avoiding any installation efforts and gaining more flexibility in case of upgrades, these tools should be called via Docker:

* Spectral: https://hub.docker.com/r/stoplight/spectral
* Oapi-Gen: Check if tool is installed otherwise install if if missing (by specifying the specific version which should be used - don't install the latest otherwise comments in generated files can change as they include the version-nr)

AC:
* the `make oapi` target can be called without any pre-installed tooling

**Reasons**

Execution of Makefile should not cause any pre-requisites on the local system (beside GO tooling).

**Attachments**

**Comment by janmedrek** [comment]
Functionalities of the Reconciler were migrated to the new architecture, this issue will not be worked on.
