### ISSUE TITLE
Workspace factory has to clone into Home-directory per default

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#405]
**Description**

Currently the workspace factory expects to retrieve the storageDir from the caller which has the side-effect that unit-tests are cloning the same sources (e.g. Kyma repo) multiple times into different locations.

To solve this, the workspace factory should per default clone the Kyma sources into the users-Home directory. Passing a storage directory should still be possible but no longer a mandatory parameter.

A similar change was already made in #246 but could be simplified by changing the default behaviour in the workspace factory.

A possible method signature for [`newWorkspaceFactory`](https://github.com/kyma-incubator/reconciler/blob/main/pkg/reconciler/workspace/factory.go) could be:

     type Config struct {
          kymaRepository *reconciler.Repository
          storageDir string
     }

     func (c *Config) validate() {
         if c.storageDir == "" { c.storageDir = c.homeDir() }
         if c.kymaRepository == nil { c.kymaRepository = &reconciler.Repositroy{url:kymaRepoURL} }
      }

     func NewFactory(logger *zap.SugaredLogger, config &Config{}) (*DefaultFactory, error) {
         if err := config.validate(); err != nil { return nil, err}
         ...
     }

As final cleanup of this change, following parts should be removed from the code:

* the `reconciler.RefreshGlobalWorkspaceFactory` function has to be removed as a global workspace isn't allowed to be changed later on as it can lead to race-conditions during runtime.
* tests should no longer set the workspace-directroy to $HOME explicitly (happens currently in [provider_test.go](https://github.com/kyma-incubator/reconciler/pull/246/files#diff-55aa578bf4f38f5401d61a0d0fd9a834d262f8141bd93fa57eec4bd58732bb73R21), [runner_test.go](https://github.com/kyma-incubator/reconciler/pull/246/files#diff-e4c69c73af5053e61617cb410a94467c946e51649589c6fd5a3bf95d2df4337dR28) and [factory_test.go](https://github.com/kyma-incubator/reconciler/pull/246/files#diff-25ed461ca976ecc0f7ec9ee1dc7e0a3920aa4d3247dca36a6b54b413bc008cdaR18))

**Reasons**

Code simplification and cleanup.

**Attachments**

**Comment by janmedrek** [comment]
Functionalities of the Reconciler were migrated to the new architecture, this issue will not be worked on.
