### ISSUE TITLE
Retry clusters in error state if the previous reconciliation was successful and no cluster-config changes were happening

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#406]
**Description**

If a cluster is switching into an error state, the reconciliation should be retried if 

* the cluster was previously successfully reconcilied
* no configuration changes were happening between the current and previous reconciliation

The number of max-retries and retry-delay has to be configurable.

_Hint for the implementation:_

The `Bookkeeper` could be enhanced to support such retry-logic. If the bookkeeper identifies a reconciliation which is in error state, it can verify whether the last successful reconciliation of the cluster was using the same cluster-configuration. If this is the case, it will mark the cluster to require another reconciliation (if the max-retries isn't reached) and increasing the retry-count on the cluster-entity (<< this field doesn't exist yet but can be easily added ).

Would be worth to introduce another cluster state (e.g. `transient_error`) which indicates that the cluster needs a reconciliation because it failed before. Such a new cluster state enables also the `cluster inventory` to identify such clusters when it's searching for clusters which require a reconciliation. Base don the number of counted retires, the inventory can calculate the retry-delay and return the cluster only if the retry-delay was reached.

AC:

* A cluster which is switching into error state will be retried if
     * the previous successful reconciliation was using the same cluster configuration
     * the amount of max-retires isn't reached for this cluster
* If the number of max retries is reached, the cluster is marked to be in `error` state
* Max-retries and retry-delay has to be configurable
* The retry of clusters which are in a transient error state, has to consider a delay which gets doubled with each retry (e.g. 1min, 2min, 4min, 8min, 16min waiting period before the next retry happens)

**Reasons**

Reduce the risk to set a cluster into `error` state if the error seems to be transient.

**Attachments**

**Comment by tobiscr** [comment]
Agreed with SRE to track cutover actions in the [internal Wiki](https://wiki.wdf.sap.corp/wiki/display/kyma/Kyma+2.0+rollout+cutover+plan).

**Comment by pbochynski** [comment]
We talked about other option: we do not stop reconciliation automatically. It is always on, and you can disable reconciliation with kcp CLI if needed.

**Comment by tobiscr** [comment]
By changing to continues reconciliation even in error-cases, we don't need this feature anymore. New ticket will be created to change the scheduling logic to consider also clusters in error state.
