### ISSUE TITLE
Exclude Jobs from updates in reconciler

### ISSUE THREAD

**Issue by varbanv** [kyma-incubator/reconciler#420]
**Description**

The reconciler should not use replace for Jobs. They should just be created once and not be touched later by the reconciler.

AC:

- Particular resources have to be excluded from the reconciliation (they should be created if they don't exist, but not be updated/replaced later on)

**Reasons**

- Several components should not be modified after they were created

**Attachments**

**Comment by tobiscr** [comment]
Replacement of StatefulSet is partially possible, see #423

**Comment by tobiscr** [comment]
fix will be provided in https://github.com/kyma-incubator/reconciler/pull/426
