### ISSUE TITLE
SKR reconciliation deletion process fails

### ISSUE THREAD

**Issue by varbanv** [kyma-incubator/reconciler#422]
**Description**

The reconciliation deletion process in SKR fails:

 - busola-migrator: dependencies are missing: 'istio-configuration' 
 - eventing: dependencies are missing: 'istio-configuration' 
 - rma: Failed to get manifest for component 'rma' in Kyma version '2.0.0-rc5': Error downloading Git repository (https://storage.googleapis.com/kyma-mps-dev-artifacts/rma-1.1.0.tgz): Failed to clone the repository: 'authorization failed': authorization failed
 - connectivity-proxy: Failed to get manifest for component 'connectivity-proxy' in Kyma version '2.0.0-rc5': Error downloading Git repository (connectivity-proxy): Failed to clone the repository: 'exec: "git": executable file not found in $PATH': exec: "git": executable file not found in $PATH

**Expected result**

Deletion process completes.

**Actual result**

Several components fail.

**Steps to reproduce**

Delete an SKR in DEV

**Troubleshooting**

**Comment by tobiscr** [comment]
The past two points will be addressed by fixing the general download-mechanism in the reconciler: https://github.com/kyma-incubator/reconciler/issues/395

**Comment by tobiscr** [comment]
See also #2044 - issue when deleting RMA
