### ISSUE TITLE
Reconciler Change detection

### ISSUE THREAD

**Issue by k15r** [kyma-incubator/reconciler#424]
**Description**

The reconciler should download resources before trying to update / replace existing resources. This will allow us to notify from within the reconciler that a resource was modified. 

Consider this scenario:
- user deletes a resource from the cluster
- user creates a new resource similar to the previous one (same name ..) but some immutable fields set to different values
- reconciler cannot revert those changes 
- reconciler does not fail as it filters the fields (the ones it wants to modify to not even attempt to modify immutable fields )

Without this feature it will be hard to figure out why a cluster is in a not supported state but still reported operational ok.

**Acceptance**

- [ ] Reconciler lists changes for all expected resources

**Comment by tobiscr** [comment]
Related to #601

**Comment by janmedrek** [comment]
Reconciler has moved to the new architecture, this issue will not be worked on.
