### ISSUE TITLE
Git-client should support git-V2 protocol and mulit-ack to be compatible with Azure DevOps

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#432]
**Description*** 

Goal is to simlify our internal GIT library in the reconciler. Currently, the interface is not well design and not offering a meaningful simplification of the underneath used go-git library.

Refactoring should:

* Verify what the required GIT use-cases are the reconciler has (probably support of converting branches to revision, clone and fetch GIT repos)
* Reduce the API to support these type of GIT actions
* Remove the dependnecy to K8s-API as it's coupling the GIT library to K8s runtimes which makes technially no sense (instead doing credential-lookups in GIT by reading K8s-secrets, pass the credentials to the GIT API cal)

Last nice-to-have feature would be to support GIT v2 protocol:

The used `go-git` library [isn't support git v2 protocol and also not handling multi-ack](https://github.com/go-git/go-git/issues/64) which makes it incompatible with common external products like Azure DevOps. This limitation can become a drawback for open source customers and we should replace the used go-GIT library with a newer implementation (see linked ticket for proposed alternatives).

Verify the effort of changing to a different go-GIT implementation which doens't have such limitations.

AC:

* Simplify GIT API to the use cases the reconciler requires (clone, fetch, convert automatically branch to revs etc.)
* Remove dependency to K8s library

Nice to have:
* Replace used git-library with an alternative GIT implementation which offers the same features as currently required in the reconciler (git clone, checkout particular branch etc.)
* Ensure implementation works with Github + Azure DevOps

**Reasons**

Simplify GIT library and provide an interface which is focusing on the required use-cases. Improve maintainability of the internal GIT lib.

**Attachments**

**Comment by janmedrek** [comment]
Functionalities of the Reconciler were migrated to the new architecture, this issue will not be worked on.
