### ISSUE TITLE
KCP CLI: show component configuration in `reconciliation info` output 

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#433]
**Description**

The list of components it not part of the generated JSON output which makes it hard to verify the parameters used for a reconciliation run.

**Expected result**

JSON output also includes the cluster components and their parameters.
It should be list of components and their configuration (they are part of the cluster-config entity) 

**Actual result**

Cluster components are shown as emtpy array in JSON.

**Steps to reproduce**

On KCP DEV execute:

`kcp reconciliations info --scheduling-id be30affb-1779-4e87-a8ec-d4061b2ea59e--9d544e34-318d-481f-b893-957b60031626 -o json`

Output is attached as file.

[dump_kcp.txt](https://github.com/kyma-incubator/reconciler/files/7558149/dump_kcp.txt)

**Troubleshooting**

**Comment by kwiatekus** [comment]
We will investigate why components is empty
We consulted @ebensom about the response structure for the info command
`kcp rc info -i {scheduling-id} -o json`
```json
{
    "status" : "",
    "created" : "",
    "updated" : "",
    "finished" : "",
    "kymaConfig":{
          "components": [{
            "URL" : "",
            "component" : "serverless",
            "configuration" : [
                {}
            ],
            "namespace" : "",
            "version" : "",
          }],
          "profile": "Production",
          "version": "2.0.0-rc4"
    },
    "operations": [
        {}
    ]
}
```

**Comment by kwiatekus** [comment]
changes in the reconciler API in review -> https://github.com/kyma-incubator/reconciler/pull/437
changes in CLI in progress -> https://github.com/kyma-project/control-plane/pull/1114

**Comment by kwiatekus** [comment]
Everything merged.
Deployment of that is still pending due to audit-log pvc config problem
https://github.com/kyma-project/control-plane/pull/1137
Lets keep open until its deployed to dev landscape
