### ISSUE TITLE
Kubeconfig has to be passed from KEB-contract model to reconciler-DB entity

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#44]
**Description**

The kubeconfig is currently not passed to the reconciler from KEB and missing in the contract.

The contract has to be adjuted and the kubeconfig-value has to be considered when creating new cluster entities in the reconciler.

See `inventory.createCluster` function for further details.

**Expected result**

Kubeconfig is another attribute of a `ClusterEntity` and stored in the DB.

**Actual result**

Kubeconfig is missing in models and in DB.

**Steps to reproduce**

**Troubleshooting**

**Comment by tobiscr** [comment]
Please review TODO comment in https://github.com/kyma-incubator/reconciler/pull/78/files#diff-f921d302f6db810d79d7007b3c8a95dc107a6a7e4da95f92f3a96cbb6f6589aaL88 when working on this ticket

**Comment by suleymanakbas91** [comment]
Implemented in #83.
