### ISSUE TITLE
Introduce sanity checks to reconciler

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#448]
**Description**

The reconciler has to to be able to apply sanity checks before starting a reconciliation. Sanity checks have to be executed before any reconciliation starts. A non-fulfilled sanity check leads to a failing reconciliation and has to fire an alert on SRE side.

Such a sanity check can be either globally (e.g. used K8s servcie-account has sufficient permissions) or component specific. Global sanity checks have to be executed for any reconciliation. Component specific sanity checks have only to run if the cluster configuration includes the related component.

Please review all issues which are labels with `outage-scenario` (see ops-test page in Wiki) for potential edge-cases which should be verified by a sanity check.

AC:
* Sanity checks can be defined globally or per component: global sanity checks are always executed, component specific sanity checks only if the cluster configuration includes the component.
* Sanity checks are executed before any reconciliation runs
* A failing sanity check will mark the cluster to be in error state (maybe worth to introduce a new error state like `sanitycheck_error`or similar?).
* SREs will be notified about such problems via monitoring (existing alerting/reporting approach of reconciler can be reused).

**Reasons**

Identify non-recoverable reconciliation issues up-front.

**Attachments**

**Comment by janmedrek** [comment]
Functionalities of the Reconciler were migrated to the new architecture, this issue will not be worked on.
