### ISSUE TITLE
Workspace factory: deletion of external component not working

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#450]
**Description**

The deletion of an external component is not removing the sources on disk (currently is is using the `Delete` command for Kyma which isn't working for external components as the name of workspace-folder is differently created for a Kyma workspace).

A dedicated delete function for external components is required which is removing the folder-name used for external components.

**Expected result**

Deleting an external component has to remove the workspace-folder used for the external component.

**Actual result**

Removing an external component tries to removes the workspace-folder which would be used for Kyma download.

**Steps to reproduce**

**Troubleshooting**

**Comment by tobiscr** [comment]
requires #462 + #463

**Comment by ralikio** [comment]
Related to #469

**Comment by tobiscr** [comment]
@ralikio: how is this issue related to the #469- this bug was created because we could not delete workspaces in our unit-tests when caling the `Delete` function of the workspace factory. This `Delete`-fct us currently not used somewhere else afaik.

**Comment by ralikio** [comment]
@tobiscr Issue removed.
