### ISSUE TITLE
Extend the eventing removenatsoperator preaction with kyma version check

### ISSUE THREAD

**Issue by VladislavPaskar** [kyma-incubator/reconciler#453]
**Description**

Currently the preaction step `removenatsoperator` in the eventing component reconcile is being executed in every reconciliation step. However this change is attached to the kyma 2.x release and should not be performed on kyma 2.x+ clusters. Therefore a check for kyma version is required. 

This [PR](https://github.com/kyma-incubator/reconciler/pull/431) already contains the placeholder for this check and a test scenario

**Steps:** 

- Wait until this check will be introduced, https://github.com/kyma-incubator/reconciler/issues/334 is a pre-requisite for that
- skip the step for the 2.x cluster using the commented placeholder code and test case

**Comment by janmedrek** [comment]
Reconciler has moved to the new architecture, this issue will not be worked on.
