### ISSUE TITLE
Micro-Delivery: setup develop-branch and adjust CI/CD system

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#458]
**Description**

For getting full control of the changes we rollout to production, the team decided to continue with two branches:

* `main` branch stays the mainstream and is used for releasing the reconciler
* `develop` contains the latest changes and is used to merge new features

The defined quality gates in Github have CI/CD system has to support both branches and defined quality gates apply for both.

AC:
* develop branch created and marked to be non-deletable in Github
* the same CI/CD jobs are also executed for changes applied on the develop branch
* Github considers the same quality-gates for the `develop`-branch which are already in place for the `main`-branch

**Reasons**

Give more control in shipping new features.

**Attachments**

**Comment by jeremyharisch** [comment]
`develop` branch is set up and configured!

**Comment by jeremyharisch** [comment]
https://github.com/kyma-project/test-infra/pull/4610 introduced new Pre-/Post-PR jobs.

To set up nightly-/daily Jobs a follow-up Issues will be created.

**Comment by jeremyharisch** [comment]
Close it, due to follow up issue
