### ISSUE TITLE
Improve Eventing reconciler logs

### ISSUE THREAD

**Issue by marcobebway** [kyma-incubator/reconciler#460]
**Description**

Improve the following logs in the `RemoveNatsOperator` pre-action step:
- It should log when it finishes execution.
- It should log if it skips execution.
- It should not log the deletion of NATS CRDs if they were not found on the cluster (See: pkg/reconciler/instances/eventing/preaction/removenatsoperatorstep.go).
  ```golang
  // func removeNatsOperatorCRDs
  
  if err == nil {
      logger.Debugf("Deleted %s CRD from %s namespace", crdName, namespace)
  }
  ```

**Comment by k15r** [comment]
no complaints since one year. closing
