### ISSUE TITLE
Reconcile also clusters in error state

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#464]
**Description**

_WHY:_

To ensure that transient errors won't lead to non-reconciled clusters, it was agreed to not stop the reconciliation if a cluster is switching into an error state (e.g. `error`).

The reconciliation will continue and pickup the cluster regularly as part of the reoccurring reconciliation cycles. The only state in which a cluster will not be reconciled is:

* either a temporary state (e.g. `reconciling`, `deleting`)
* the cluster is disabled from the reconciliation (state `reconcile_disabled`) 
* the last reconciliation append before the reconciliation-interval was reached again 
* the cluster is in a final state (e.g. `deleted`, `delete_error`)

_AC:_

* Cluster which are in state `error` are still reconciled after they reached the configured reconcile-interval
* Number of re-tries should be counted
* Alerting for an cluster in error state should happen after the X retries happened (X should be configurable)
* ~~Retires should happen with increasing delay, e.g. 2, 4, 8, 16min.. etc. (the delay should be configurable)~~ <- descoped!
* Alerting has to stop after first successful reconciliation was possible

_Implementation hint:_

* Update the filter-logic in `inventory.GetClustersToReconcile()` function

**Reasons**

Address transient / temporary issues which can cause a cluster to switch into the error state by reconciling it.

**Attachments**

**Comment by vvxxvvxx** [comment]
Hi Tobias, just to understand the current logic..
Now if the operation status is not `OperationStateDone` or `OperationStateError`, for every kyma component to be reconciled, they will be reconciled until timeout(default 10min) or MaxRetries (default 5), right? 
Status for all operations will be tracked and collected, then summarized to the ClusterStatus (9 statuses), right?


so from the above `AC`, only this one hasn't been implemented?  
- Retires should happen with increasing delay, e.g. 2, 4, 8, 16min.. etc. (the delay should be configurable)

**Comment by tobiscr** [comment]
> Hi Tobias, just to understand the current logic.. Now if the operation status is not `OperationStateDone` or `OperationStateError`, for every kyma component to be reconciled, they will be reconciled until timeout(default 10min) or MaxRetries (default 5), right? Status for all operations will be tracked and collected, then summarized to the ClusterStatus (9 statuses), right?
> 
> so from the above `AC`, only this one hasn't been implemented?
> 
> * Retires should happen with increasing delay, e.g. 2, 4, 8, 16min.. etc. (the delay should be configurable)

Hi @varbanv ,

for operations, we retry currently 5 times with exponential delay. Both values are configurable.
Yes, after the reconciliation is over, we process the results of the operation outcomes and update the cluster state accordinly.

**Comment by pbochynski** [comment]
It is fixed now.

**Comment by tobiscr** [comment]
Causing #528
