### ISSUE TITLE
Support PATCH strategy for Kubernetes resources which cannot be updated via REPLACE

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#465]
**Description**

Replacing resources in Kubernetes does not work for few resource types (e.g. Jobs, Pod, PVCs and Statefulsets which include PVCs, [Service-Accounts](https://github.com/kyma-incubator/reconciler/issues/467)). These resources have to be updated using Patching.

AC:

* The reconciler has to verify whether the current resource is of type PVC or Statefulset and includes a PVC. In this case, the update of this resource has to happen by  the Kubernetes client via PATCH instead REPLACE.
* The Interceptors which are excluding these resources from reconciliation have to be dropped after we support patching of such resources.

**Reasons**

Support PATCHING  for resources which cannot be REPLACE in Kubernetes to support a reconciliation of these resources.

**Attachments**

**Comment by tobiscr** [comment]
@pbochynski : QQ - should we exclude resource we intentionally don'T want to reconcile from the scope of this ticket (e.g. Pods, Jobs)?

**Comment by pbochynski** [comment]
I would exclude pods and jobs.

**Comment by veichtj** [comment]
Unfortunately retest of #459 failed, after changing the postgres image within ory there is no update happening after reconciling ory

**Comment by pbochynski** [comment]
@cnvergence  Can you contact @tobiscr and reproduce together the issue?

**Comment by varbanv** [comment]
Still troubleshooting.

**Comment by tobiscr** [comment]
Fix provided in #535 (switching o HELM kube-client)

**Comment by raypinto** [comment]
Retested #459 - after changing the postgres image within ory, the `ory-postgresql-0` pod reconciles successfully!

**Comment by raypinto** [comment]
Retested #459 with the latest reconciler - and the change in postgres image within ory does not reconcile `ory-postgresql-0` pod

**Comment by tobiscr** [comment]
I'm try install ORY on my local K3d and it's not possible for me. It stucks starting `ory-hydra-...` pods

     kyma-system    ory-hydra-maester-5667c9dc6-2ghrh                       0/3     PodInitializing   0          2m2s
     kyma-system    ory-hydra-765b558996-88h68                              0/2     PodInitializing   0          2m2s

**Comment by tobiscr** [comment]
Issue with ORY should be fixed with #597
