### ISSUE TITLE
Secrets for service account tokens get duplicated when replacing service account-entries

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#467]
**Description**

Secrets which include service account credentials are re-created by K8s in another secret when replacing the service-account resource.

**Expected result**

Service accounts should not be re-created during the reconciliation.

**Actual result**

A new secret gets created when a service account gets replaced during the reconciliation.

**Steps to reproduce**

**Troubleshooting**

**Comment by kwiatekus** [comment]
Depends on https://github.com/kyma-incubator/reconciler/issues/465

**Comment by pbochynski** [comment]
Tracked in #465

**Comment by pbochynski** [comment]
I can observe the problem again. Stage env, shoot: c-056642e

**Comment by clebs** [comment]
this issue will be fixed together with #582.

**Comment by pbochynski** [comment]
It is not happening now.
