### ISSUE TITLE
Add automatic integration test for Connectivity Proxy reconciler

### ISSUE THREAD

**Issue by franpog859** [kyma-incubator/reconciler#475]
**Why**

Some time ago we added a [Connectivity Proxy reconciler](https://github.com/kyma-incubator/reconciler/tree/main/pkg/reconciler/instances/connectivityproxy). We'd love to have an automatic integration test for this component to avoid doing it manually all the time. This area seems to be quite unstable so we don't want to adjust it all the time too

**What**

The test should be triggered every PR to the reconciler repository (or eventually control-plane repo, where the images are being bumped) and should test added functionality, so installing Connectivity Proxy when the Connectivity Service ServiceBinding is created in the SKR. It should also uninstall everything needed when the SKR is being deleted

1. Check where to put this test. There are two potential places - [some Go integration tests for Reconciler](https://github.com/kyma-incubator/reconciler/search?q=integration) or [the fast-integration tests running after the reconciliation ](https://github.com/kyma-project/test-infra/blob/main/prow/scripts/cluster-integration/reconciler-e2e-gardener.sh). Consult it with the Reconciler Team, they will probably have some valuable insights on it
2. Implement the test that ensures that the Connectivity Proxy is successfully installed after the Connectivity Service ServiceBinding (and secret) creation. Consider using some dummy ServiceBinding as we don't really plan to test the Connectivity functionality here, only the reconciliation part. It should also check if it's uninstalled correctly while deprovisioning

Feel free to comment on this issue to specify acceptance criteria better or to discuss this topic

**Comment by janmedrek** [comment]
Please specify what type of chart should be installed and how it can be realized in our testing infrastructure.

**Comment by franpog859** [comment]
An integration test that uses the real chart checks the flow from the beginning, so from obtaining the tools secret to installing the real chart on the SKR with all the nuances, for example filling the values from service binding. It sounds like a true integration test for me as the responsibility of the Connectivity Proxy Reconciler is to install this specific chart when the conditions are met
An integration test that uses some dummy binding checks only the installation part of the flow, which is already tested with some unit tests. However it would test it in an integration environment, so it's valuable too

I'd go for the real chart if it's possible. If it's not possible, let's go with the dummy one. I don't know how it can be realized in our testing infrastructure. It's the first point in the to-do list from the issue description. Some investigation or a dialogue between teams is definitely needed

**Comment by janmedrek** [comment]
We can think of verifying the installation via a simple call, for example to one of the Virtual Services exposed by the Connectivity Proxy.

**Comment by franpog859** [comment]
14.04.20222 idea:
Implement a separate pipeline that creates a cluster, installs Istio on it (and everything else that is needed for Connectivity Proxy Component Reconciler to work correctly) and Connectivity Proxy Component Reconciler, creates a Service Binding on the same cluster (and everything else that is needed for the Reconciler to install the Connectivity Proxy), and checks if Connectivity Proxy is installed (and later removed) correctly

**Comment by janmedrek** [comment]
Should be solved by: https://github.com/kyma-project/kyma/issues/15524
