### ISSUE TITLE
Avoid failing E2E CI/CD pipeline by switching to 'dynamic' nightly-cluster names

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#493]
**Description**

Currently, the reconciler E2E CI/CD pipeline is failing caused by reaching the [LetsEncrypt certificate rate limit](https://letsencrypt.org/docs/rate-limits/):

https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/nightly-main-reconciler-e2e

A longterm solution would be to use to use differnet cluter-names per day, e.g. 

* Monday = rec-nightly1
* Tuesday = rec-nightly2
* Wednesday = rec-nightly3
* ...

**Expected result**

E2E tests don't exhaust the LetsEncrypt certificate creation threshold by using each day a different cluster names.

**Actual result**

E2E test pipeline temporarily fails because the LetsEncrypt certificate threshold is reached by reusing the cluster-name every day.

**Steps to reproduce**

**Troubleshooting**

**Comment by suleymanakbas91** [comment]
Fixed in https://github.com/kyma-project/test-infra/pull/4527.

**Comment by tobiscr** [comment]
@suleymanakbas91 : QQ - this failure from Friday evening is already known? 

     2021/12/03 17:00:51 UTC [INFO] *************************************************************************************
     2021/12/03 17:00:51 UTC [INFO] * Connecting to nightly cluster
     2021/12/03 17:00:51 UTC [INFO] *************************************************************************************
     Error from server (NotFound): secrets "rec-night.kubeconfig" not found

https://storage.googleapis.com/kyma-prow-logs/logs/nightly-main-reconciler-e2e/1466814546730553344/build-log.txt
