### ISSUE TITLE
Implement database migration approach which supports execution of custom logic

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#498]
**Description**

The database migration has to support the execution of custom logic steps. Custom logic should be executable after each DB migration step.

See possible implementation approach (not tested yet): #442 

AC:

* Migration is no longer execute as a monolithic step, instead each migration task is executed one after another
* After the execution of a migration step, the logic verifies whether a custom logic should be executed and executes it
* It has to be able to start multiple migrations in parallel (e.g. caused by starting multiple mothership reconcilers at the same time) and it has to be ensured that each migration step is executed just once - be aware that the DB migration framework support DB locking out of the box).

**Reasons**

* Allow data migration during bootstrap by executing custom logic.

**Attachments**

**Comment by janmedrek** [comment]
Functionalities of the Reconciler were migrated to the new architecture, this issue will not be worked on.
