### ISSUE TITLE
Security: improve SQL injection detection mechanism

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#503]
**Description**

The existing SQL injection detection unit-test has to be updated and the latest SQL statements used by the mothership-reconciler have to be evaluated. 

As the current implementation has known limits, it should also be verified whether a change to a Golang SQL parter library could simplify the implementation (see examples / few available libs here: https://github.com/blastrain/vitess-sqlparser).

AC:
* SQL injection detection is tested with latest mothership-reconciler SQL statements (unit test defined)
* Review of available SQL parser libs happend to verify whether a change to a parser-library can simplify the injection detection and avoid the currently used complex SQL regexps.

**Reasons**

Increase security by optimised SQL injection detection and improve code maintainability.

**Attachments**

**Comment by janmedrek** [comment]
Functionalities of the Reconciler were migrated to the new architecture, this issue will not be worked on.
