### ISSUE TITLE
CI/CD pipelines for reconciler failing since to night (e2e and upgrade test)

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#504]
**Description**

Two CI/CD pipelines are broken:

* https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/nightly-main-reconciler-e2e
* https://status.build.kyma-project.io/?job=periodic-main-kyma-incubator-reconciler-kyma1-kyma2-upgrade

Both pipelines stopped working tonight and seem to fail all at the step of calling an OAuth2 endpoint during the fast-integration tests.

IN some tests, we are getting a 401 response, other return with a connection-reset issue.

      1) Upgrade test tests
       function should be reachable through secured API Rule:
     Error: Error when requesting bearer token from https://oauth2.grdzbwgsl.kyma-prow.shoot.canary.k8s-hana.ondemand.com/oauth2/token: 401 Unauthorized
      at OAuthToken.getToken (lib/oauth.js:69:27)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async checkFunctionResponse (test/fixtures/commerce-mock/index.js:123:23)
      at async Context.<anonymous> (upgrade-test/upgrade-test-tests.js:29:5)

       CommerceMock tests
         function should be reachable through secured API Rule:
     Error: Error when requesting bearer token from https://oauth2.rec-night.kyma-prow.shoot.canary.k8s-hana.ondemand.com/oauth2/token: Error: read ECONNRESET
      at OAuthToken.getToken (lib/oauth.js:71:27)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async checkFunctionResponse (test/fixtures/commerce-mock/index.js:123:23)
      at async Context.<anonymous> (test/1-commerce-mock.js:57:7)

**Expected result**

Both CI/CD pipelines are critical for making release decision of the reconciler.

**Actual result**

Above mentioned pipelines are failing during the execution of the fast integration tests (E2E and Upgrade)

**Steps to reproduce**

**Troubleshooting**

**Comment by pbochynski** [comment]
Test passed once and the next execution failed on monitoring test:
```
  1) Monitoring test
       There should be no firing critical Prometheus alerts:
     AssertionError: Following alerts are firing: KubeHpaMaxedOut: expected [ 'KubeHpaMaxedOut' ] to be empty
      at Context.<anonymous> (monitoring-test/monitoring-test.js:71:12)
```
The next test failed on reconciliation of monitoring component:
```
{"level":"DEBUG","time":"2021-12-01T05:24:01.087Z","message":"Bookkeeper evaluated reconciliation (schedulingID:6f8ec1bc-f300-4f00-bb65-6fec5dcd0ba5--cb939766-dd8e-4a4c-ab71-752823e73256) for cluster '6f8ec1bc-f300-4f00-bb65-6fec5dcd0ba5' to cluster status 'error': Done=cluster-essentials,CRDs,eventing,kiali,certificates,istio-configuration,tracing,service-catalog,service-catalog-addons,rafter,serverless,api-gateway,helm-broker,application-connector,cluster-users,ory,logging / Error=monitoring[error: context deadline exceeded] / Other="}
{"level":"INFO","time":"2021-12-01T05:24:01.090Z","message":"Reconciliation for cluster with runtimeID 6f8ec1bc-f300-4f00-bb65-6fec5dcd0ba5 and clusterConfig 1 failed, reconciliation will be retried. Count of retries: 0"}
```

**Comment by pbochynski** [comment]
When I deleted replica set `monitoring-auth-proxy-grafana-7f9f7c9f96` reconciliation succeeded.

**Comment by pbochynski** [comment]
The issue for reconciler to ignore replica sets with desired pods equal 0: https://github.com/kyma-incubator/reconciler/issues/513

**Comment by ruanxin** [comment]
But is it make sense to remove those old replicaset instances? So that we always have one replicaset controlled by deployment `monitoring-auth-proxy-grafana`?

Seems `.spec.revisionHistoryLimit` can do it, if we configured to 0 (default is 10), the old replica set will be cleaned up, but we lost the ability to rollback, but do we need to versioning this resource?
https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#revision-history-limit

**Comment by a-thaler** [comment]
The monitoring problem should be fixed by https://github.com/kyma-project/kyma/pull/12766

**Comment by pbochynski** [comment]
> But is it make sense to remove those old replicaset instances? So that we always have one replicaset controlled by deployment `monitoring-auth-proxy-grafana`?
> 
> Seems `.spec.revisionHistoryLimit` can do it, if we configured to 0 (default is 10), the old replica set will be cleaned up, but we lost the ability to rollback, but do we need to versioning this resource? https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#revision-history-limit
> 
> We are use default value 10
> 
> ```
> kubectl get deployment monitoring-auth-proxy-grafana -n kyma-system -o yaml | grep revisionHistoryLimit
>   revisionHistoryLimit: 10
> ```

Yes - I think it can work. We do not have rollback right now in the reconciler. I am just thinking if it is the best approach. The solution proposed by Tobias will work regardless of the history limits and we do not need to modify all the charts now. 
It can be hard to track if someone is not introducing the deployment with history limit grater than zero.

**Comment by pbochynski** [comment]
Right now the plan fails with ory installation:
```
{"level":"DEBUG","time":"2021-12-02T13:07:50.754Z","message":"Bookkeeper evaluated reconciliation (schedulingID:6f8ec1bc-f300-4f00-bb65-6fec5dcd0ba5--a131cbf3-31db-46a2-b2f8-c10d09bebf43) for cluster '6f8ec1bc-f300-4f00-bb65-6fec5dcd0ba5' to cluster status 'error': Done=CRDs,certificates,cluster-essentials,istio-configuration,service-catalog,helm-broker,serverless,rafter,api-gateway,tracing,application-connector,monitoring,logging,kiali,cluster-users,eventing,service-catalog-addons / Error=ory[error: context deadline exceeded] / Other="}
{"level":"INFO","time":"2021-12-02T13:07:50.755Z","message":"Reconciliation for cluster with runtimeID 6f8ec1bc-f300-4f00-bb65-6fec5dcd0ba5 and clusterConfig 1 failed, reconciliation will be retried. Count of retries: 1"}
```

**Comment by tobiscr** [comment]
Requires #493 to avoid side effects with failing certificates etc.

**Comment by pbochynski** [comment]
Pipelines are green again.

**Comment by tobiscr** [comment]
update #493 to use each day a different cluster name to avoid exhausted LetsEncrypt certificates.

**Comment by tobiscr** [comment]
Issue with `401 Unauthorised` errors are tracked in https://github.com/kyma-project/kyma/issues/12776
