### ISSUE TITLE
DB transaction handling is broken in mothership reconciler

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#507]
**Description**

The DB transaction handling is not correctly working in mothership reconciler. Rollbacks don't revert applied changes, caused by missing call to the EXEC-fct of the transaction entity ([see code](https://github.com/kyma-incubator/reconciler/blob/main/pkg/db/transaction.go#L22)).

DbOps functions have to use the provided TX-object to execute DB changes and not use the non-TX aware connection for executing queries.

**Expected result**

DB transaction scope is properly handled and rollback / commit works as atomic unit.

**Actual result**

A transaction is created but not executing the queries inside of the DB operation. This doens't enable proper rollback/commit behaviour.

**Steps to reproduce**

**Troubleshooting**

**Comment by tobiscr** [comment]
@jeremyharisch : please let's have a quick sync before starting with the fix. This requires an adjustment in DB layer and in the base-implementation of the [repository](https://github.com/kyma-incubator/reconciler/blob/main/pkg/repository/repository.go).

**Comment by jeremyharisch** [comment]
Fixed with #562
