### ISSUE TITLE
Kyma resilience: Introduce component testing support in reconciler

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#523]
**Description**

The progress tracking of a component (checking if a K8s resource was reaching the READY status) is not expressive and does not ensure that the component really works.

The reconciler has to provide an option to retrieve quality indicators for a component and to make a decision about next actions (e.g. reconcile-component, trigger self-healing mechanisms etc.) 

AC:
* Define options to measure the correct installation of a component (e.g. using Prometheus metric, further healtch checks, running an external test suite etc)
* Agree on the support options the reconciler will offer to verify that a component got correctly installed
* Enhance the reconciler to support automated component checks (could require contract extension with KEB to provide also the information how to test a component to reconciler)
* Implement integration tests to verify that component testing works properly

**Reasons**

Establish more reliable approach to measure the "health" status of a deployed component.

**Attachments**

**Comment by tobiscr** [comment]
Follow-up action from retrospective meeting.

**Comment by tobiscr** [comment]
We agreed during the PO call today to not investigate into it as we have first to gather some experiences whether the currently used readiness-probes aren't working out for us.

**Comment by janmedrek** [comment]
Functionalities of the Reconciler were migrated to the new architecture, this issue will not be worked on.
