### ISSUE TITLE
Reconciler terminates scaled pods

### ISSUE THREAD

**Issue by veichtj** [kyma-incubator/reconciler#524]
**Description**

Kyma 2.0 is installed successfully via reconciler.
ORY oathkeeper pods are deployed within production profile with a min replica of 3, also the hpa sepc says min 3, max 10.
When k8s hpa scales up the oathkeeper pods to more than 3, because of more load on the cluster, during a reconciler run all pods that were scaled up are going into termination. After reconciler run is finished, the hpa again scales up. This potentially leads to interruption and also additional load with pod starting and terminating.

**Expected result**

Reconciler does not terminate additional scaled up pods

**Actual result**
Reconciler applies the default set for scaling.

**Steps to reproduce**

- Kyma 2.0 installed with production profile
- check ory-oathkeeper pods (should be 3 per default)
- create load on ory-oathkeeper for e.g. calling vs
- check hpa should scale up additional pods for ory-oathkeeper
- run reconciler for ory component
- check ory-oathkeeper pod status, you see Terminating for additionally scaled ones
- after reconciler is finished, again additional Pods are initialized

**Troubleshooting**

**Comment by cnvergence** [comment]
https://github.com/kubernetes/website/pull/29739

**Comment by cnvergence** [comment]
Helm seems to have templated this setting: https://github.com/helm/helm/pull/7381
Will prepare PR on our side @tobiscr

**Comment by cnvergence** [comment]
When investigating this issue with the adjusted Helm chart I have still encountered this problem.
This is happening to any HPA configuration with minimum Replicas setting larger than one.
The same issue apply also to application-connector - central-application-gateway deployment.

**Comment by tobiscr** [comment]
We agreed with @cnvergence  to come up with a kind of interceptor which is able to iterate through the manifest of a component with following functionality:

1. Search for HPA
     1. YES: continue at step 2
     2. NO: done
2. Check if referenced resource in HPA is already deployed in cluster
     1. NO: check if referenced resource (deployment etc.) includes already a `replica` field
          1. YES: done
          2. NO: set field `replica` using the `minValue` from HPA resource
     2.  YES: retrieve value of `replica` field from the deployed resource and set this value in the manifest of the referenced resource

**Comment by tobiscr** [comment]
Implementation hint:

To avoid different types of interceptor interfaces, we could enrich the existing interceptor interface like

     type ResourceInterceptor interface {
          Intercept(resource []*unstructured.Unstructured, namespace string) (InterceptionResult, error)
          SupportedKinds() []string
     }

The `SupportedKinds` could return the list of resource the interceptor is interested in. If the list is empty, it will retrieve all manifests, if the list include the kinds, it will retrieve only these `unstructured.Unstructured` resources which were returned by the `SupportedKinds` function.
