### ISSUE TITLE
Remove usage of github.com/pkg/errors

### ISSUE THREAD

**Issue by ruanxin** [kyma-incubator/reconciler#526]
With the upcoming Go2 error proposals this package is moving into maintenance mode. The roadmap for a 1.0 release is as follows:

    0.9. Remove pre Go 1.9 and Go 1.10 support, address outstanding pull requests (if possible)
    1.0. Final release.
https://github.com/pkg/errors

AC: remove the usage of this package handle error wrap.

**Comment by janmedrek** [comment]
Functionalities of the Reconciler were migrated to the new architecture, this issue will not be worked on.
