### ISSUE TITLE
Add new cluster status `error_retryable` and `delete_error_retryable` to KEB contract

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#528]
**Description**

Adding a retry for reconciliations and deletions is introducing two new cluster status:

* error_retryable
* delete_error_retryable

Both cluster states have to be added to the [KEB contract](https://github.com/kyma-incubator/reconciler/blob/main/openapi/external_api.yaml#L495-L504) and the contract models have to be re-generated.

**Expected result**

Cluster status `error_retryable` or `delete_error_retryable` are valid enums in contract between KEB and reconciler.

**Actual result**

KEB model does not support `error_retryable` or `delete_error_retryable` and causes a 500er HTTP error.

**Steps to reproduce**

**Troubleshooting**

**Comment by jeremyharisch** [comment]
The adaptions have been made on reconciler side with this pr: #531 

Furthermore,  we have to update kcp command line tool and extend list of possible statuses [here](https://github.com/kyma-project/control-plane/blob/main/tools/cli/pkg/command/reconciliations.go#L57-L59). To do this we have update oapi generated types first [here](https://github.com/kyma-project/control-plane/blob/main/components/reconciler/makefile#L25).
This part will be done by @pPrecel
