### ISSUE TITLE
Reconciler pipelines are consistently failing

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#545]
**Description**

E2E pipeline is failing caused by ORY component after  a few successful reconciliations (repeats each day);

https://status.build.kyma-project.io/?job=nightly-main-reconciler-e2e
https://status.build.kyma-project.io/?job=periodic-main-kyma-incubator-reconciler-kyma1-kyma2-upgrade

**Expected result**

Pipeline has to be green.

**Actual result**

Pipelines are completely instable.

**Steps to reproduce**

**Troubleshooting**

**Comment by tobiscr** [comment]
Based on the logs of the failing E2E pipeline, it looks like to be a problem with the PG deployment:

1.  either with the stability of the deployed PG instance (liveness probe fails and PG gets re-started and looses all old data)
2. an old PG instance is still running and used by the mothership at the beginning and the PG instance get's removed / re-deployed after the mothership was running (which leads to a missing DB schema as the DB-migration happens during the bootstrap of the mothership-reconciler)

See logs:

1. DB was available and migrated by mothership reconciler:

         {"level":"DEBUG","time":"2021-12-09T01:35:48.913Z","message":"Using configuration file 'mothership-configuration/reconciler.yaml'"}
         {"level":"INFO","time":"2021-12-09T01:35:48.920Z","message":"Postgres isolation level is: read committed"}
         {"level":"INFO","time":"2021-12-09T01:35:48.937Z","message":"Database migrated"}

2. DB became unavailable (~4 min after mothership was up):

        {"level":"ERROR","time":"2021-12-09T01:39:18.947Z","message":"Postgres Query() error: dial tcp 100.69.177.163:5432: connect: connection refused"}
        {"level":"ERROR","time":"2021-12-09T01:39:18.947Z","message":"Bookkeeper failed to retrieve currently running reconciliations: dial tcp 100.69.177.163:5432: connect: connection refused"}

3. After DB was available again (~1,5min later), the DB schema no longer exists (DB probably completely empty):

        {"level":"ERROR","time":"2021-12-09T01:40:48.958Z","message":"Postgres Query() error: pq: relation \"scheduler_operations\" does not exist"}
        {"level":"WARN","time":"2021-12-09T01:40:48.958Z","message":"Worker pool failed to retrieve processable operations: pq: relation \"scheduler_operations\" does not exist"}

**Comment by ruanxin** [comment]
For database issue, seems we haven't persistent database volume, fixed in https://github.com/kyma-project/control-plane/pull/1188

For upgrade test, to deploy kyma, it always fetch latest kyma version, and I believe since kyma 2 git tag exists, this job always install v2.x instead of v1.x, so this job not doing the thing as expected since then...
fixed in https://github.com/kyma-project/test-infra/pull/4544
