### ISSUE TITLE
Refactoring: remove `utils` package from `reconciler/instances` pkg

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#549]
**Description**

There was a `utils` package added to the `pkg/reconciler/instances` package which includes some K8s-specific helper functions.

As `utils` packages are in general a bit weird, I would challenge whether the code shouldn't be moved into an existing pkg.

Currently, this `utils` pkg causes also the side-effect, that the `reconcilerctl.sh` script misbehaves and includes this `utils` pkg into the `loader.go`which is unnecessary.

**Expected result**

* Utils pkg should not be a sub-package of the `instances` pkg as its code looks more like helper-functions which can become part of an existing pkg (e.g. `reconciler/kubernetes`) or moved to a component-reconciler specific code (if it's only used by one comp-reconciler).

**Actual result**

The `reconciler/instances/utils` pkg causes wrongly rendered `loader.go` file when using `reconcilerctl.sh` script.

**Steps to reproduce**

**Troubleshooting**

**Comment by janmedrek** [comment]
Functionalities of the Reconciler were migrated to the new architecture, this issue will not be worked on.
