### ISSUE TITLE
Align configuration parameter handling: ensure consistency of exposed CLI-flags with config-file parameters and fix precedence of configuration parameters

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#552]
**Description**

We have to ensure that each configuration parameter of the reconcilers can be set in the configuration-file (`reconcilers.yaml`) can also be defined as CLI-flags OR ENv-variables.

It as to be ensured that the precedence of the configuration values is considered. Ordering of the precedence is (highest to lowest):

* CLI Flags
* ENV-vars
* config-file

**Expected result**

The mothership supports the configuration of each conifg-parameter via CLI, Env-var or config-file entry and the values are used as defined by their precedence.

**Actual result**

Values defined in confiugration value are used even if other parameter were provided via CLI (e.g. different port). Just a few parameters can be defined via CLI flags/env-vars and are not overriding values defined in the config-file.

**Troubleshooting**

**Comment by janmedrek** [comment]
Functionalities of the Reconciler were migrated to the new architecture, this issue will not be worked on.
