### ISSUE TITLE
Improve Istio Reconciler codebase automation

### ISSUE THREAD

**Issue by mjakobczyk** [kyma-incubator/reconciler#566]
**Description**

Istio Reconciler should have following things managed:

1. Function `validatePath` from `pkg/reconciler/instances/istio/bootstrap.go` should have automated tests defined.
```go
func validatePath(path string) error
```

2. Struct `TestCommanderResolver` should have a mock generated by `mockery`. For now it does not because of circular import dependency problem.

**Reasons**

Istio Reconciler test automation should cover the most crucial points and follow the general convention of mocking.

**Attachments**

Follow-up of: https://github.com/kyma-incubator/reconciler/pull/497
See: https://github.com/kyma-incubator/reconciler/issues/270

**Comment by mjakobczyk** [comment]
Update:
1. this point is no longer applicable. The function was renamed and covered with tests in scope of [this PR](https://github.com/kyma-incubator/reconciler/pull/953).
2. this point is still applicable.

**Comment by strekm** [comment]
istio reconciler will be reworded into istio manager
