### ISSUE TITLE
Refactoring: Rename preComponent to priorityList and improve priority handling in mothership reconciler

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#567]
**Description**

Any kind of component can have a higher priority than others without being a pre-component. The configuration of the mothership-reconciler should provide a more expressive and flexible component priority handling.

The configurable priority-list in the mothership-reconciler should support a defined order but also a 'wildcard' priority group:

         priorityList:
          - [cleanup]
          - [CRDs]
          - [cluster-essentials, istio-configuration, certificates]
          - [*]
          - [deleteCRs]

Components which are not explicitly listed in one of the priority-groups have to be added to the wildcard group. If no wildcard group is defined, the wildcard group will implicitly be added at the end of the priority list.

Example:

         priorityList:
          - [a]
          - [b]
          - [c, d, e]
          
If no wilcard group was defined in the priorityList, it will be implicitly added to the end:
          
         priorityList:
          - [a]
          - [b]
          - [c, d, e]
          - [*]

**Reasons**

Make pre-components more self-explaining and provide a higher flexibility on defining the reconciliation order of components.

**Attachments**

**Comment by janmedrek** [comment]
Functionalities of the Reconciler were migrated to the new architecture, this issue will not be worked on.
