### ISSUE TITLE
Reconciler pipelines are failing consistently (E2E and upgrade pipeline)

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#571]
**Description**

Both reconciler pipelines are again failing with different errors:

**E2E pipeline: https://status.build.kyma-project.io/?job=nightly-main-reconciler-e2e**

         CommerceMock tests
      ✓ Listing all pods in cluster
     Error: Wait for VirtualService commerce-mock timeout (20000 ms)
         at Timeout._onTimeout (/home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/utils/index.js:407:18)
         at listOnTimeout (internal/timers.js:557:17)
         at processTimers (internal/timers.js:500:7)
           1) CommerceMock test fixture should be ready
           2) in-cluster event should be delivered (structured and binary mode)

_=> Sorted out as ORY issue caused by disappearing cluster-role binding (cluster-role has namespace defined which leads to deletion/re-creation of the cluster-role-binding resource). Fix in ORY chart required._

**Upgrade pipeline: https://status.build.kyma-project.io/?job=periodic-main-kyma-incubator-reconciler-kyma1-kyma2-upgrade**

     error: timed out waiting for the condition on shoots/grdjmb416
     2021/12/14 07:10:45 UTC [ERROR] AN ERROR OCCURED! Take a look at preceding log entries.
     Error from server (Forbidden): nodes is forbidden: User "system:serviceaccount:garden-kyma-prow:gardener-kyma-prow"           cannot list resource "nodes" in API group "" at the cluster scope
     Error from server (Forbidden): unknown (get services http:heapster:)
     Error from server (Forbidden): unknown (get services http:heapster:)
     2021/12/14 07:10:46 UTC [INFO] Job is finished (exit status: 1)

_=> Sorted out as temporary certificate issue (limites in LetsEncrypt exceeded), no furhter investigation happening_

     {"level":"DEBUG","time":"2021-12-14T05:34:25.883Z","message":"Bookkeeper evaluated reconciliation (schedulingID:6f8ec1bc-f300-4f00-bb65-6fec5dcd0ba5--d97776c6-33f4-4144-be2e-8edb2a85fc58) for cluster '6f8ec1bc-f300-4f00-bb65-6fec5dcd0ba5' to cluster status 'reconciling': Done=cluster-users,CRDs,istio-configuration,certificates,cluster-essentials / Error= / Other=application-connector,tracing,kiali,eventing,service-catalog-addons,ory,logging[error: kubeClient failed to update StatefulSet 'logging-loki' (namespace: kyma-system): All attempts fail:\n#1: cannot patch \"logging-loki\" with kind StatefulSet: StatefulSet.apps \"logging-loki\" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden\n#2: cannot patch \"logging-loki\" with kind StatefulSet: StatefulSet.apps \"logging-loki\" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden\n#3: cannot patch \"logging-loki\" with kind StatefulSet: StatefulSet.apps \"logging-loki\" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden],rafter,serverless,service-catalog,api-gateway,monitoring,helm-broker"}

_=> issue releated to #568 , Statefulsets with PVCs have also to be excluded from reconciliation - tracked in #572_

**Expected result**

Pipelines have to be green.

**Actual result**

Both pipelines are failing.

**Steps to reproduce**.

**Troubleshooting**

**Comment by tobiscr** [comment]
An issue is reported about broken API rules which could be related to the issues we see in the E2E pipeline: https://github.tools.sap/kyma/backlog/issues/2155

**Comment by Tomasz-Smelcerz-SAP** [comment]
This PR https://github.com/kyma-project/kyma/pull/12864 should have fixed it.

**Comment by suleymanakbas91** [comment]
They are green again.
