### ISSUE TITLE
Cluster cannot be enabled after they were disabled

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#588]
**Description**

If a cluster is disabled, all later cluster changes are automatically mapped to disabled but the enabled-call should be excluded to enable the cluster reconciliation later again.

Currently, after disabling a cluster it's no longer possible to enable it.

Beside the fix, the unit-test of the inventory has to be enhanced to verify the correct behaviour.

**Expected result**

After disabling a cluster it's also possible to enable it.

**Actual result**

After disabling a cluster, it's no longer possible to enable it.

**Steps to reproduce**

**Troubleshooting**

**Comment by kwiatekus** [comment]
I noticed that clusters for  which I disabled reconciliation are not being deleted during deprovisioning. Looks like disabling reconciliation also disables deletion.
KEB shows status `deprovisioning` but the clusters are not going anywhere.

**Comment by tobiscr** [comment]
That's intended.. deletions or reconciliations are ignored. Maybe we should make here an exception and let delete-requests overwrite the disabled state as the cluster is no longer needed.

**Comment by kwiatekus** [comment]
> That's intended.. deletions or reconciliations are ignored. Maybe we should make here an exception and let delete-requests overwrite the disabled state as the cluster is no longer needed.

Ok. thanks. 
Yes, I believe user dont need to understand the nuts and bolts (that deletion is in fact reconciliation operation and reconciliation must be enabled to delete) and that cluster deletion request should be allowed

**Comment by tobiscr** [comment]
OK, final decision: 

**Even if a cluster is disabled, the DELETE call is always allowed and will be accepted even if the cluster is disabled**

**Comment by tobiscr** [comment]
Found following pod which isn't coming up:

`kyma-system        ory-hydra-7c668444ff-mlfhz                                        0/2     Init:0/3    0          37m`

**Comment by tobiscr** [comment]
Fix merged in https://github.com/kyma-incubator/reconciler/pull/608

Bump PR to KCP DEV is https://github.com/kyma-project/control-plane/pull/1224
