### ISSUE TITLE
 CI/CD piplines of reconciler and CLI have to send Slack notifications in case of failures

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#593]
**Description**

The CI/CD pipelines used for developing and testing reconciler and CLi should send a Slack message to a Jellyfish-owned channel (e.g. #kyma-reconciliation or a new create channel) whenever they fail.

Following pipelines should report failures actively:

_Reconciler:_
* Reconciler E2E: nightly-main-reconciler, nightly-main-reconciler-e2e
* Reconciler Upgrade: periodic-main-kyma-incubator-reconciler-kyma1-kyma2-upgrade
* Reconciler Upgrade images: reconciler-control-plane-image-bump

_CLI:_
* CLI Publish unstable (with latest reconciler lib): nightly-main-reconciler-publish-unstable-cli
* CLI Publish stable: rel-kyma-cli, stable-kyma-cli
* kyma-upgrade-gardener-kyma-to-kyma2
* kyma-upgrade-gardener-kyma2-to-main
* kyma-upgrade-k3d-kyma-to-kyma2
* kyma-upgrade-k3d-kyma2-to-main

**Reasons**

Get notified in case of pipeline interruptions / instability.

**Attachments**

**Comment by tobiscr** [comment]
@suleymanakbas91 : please review the list above and feel free to extend it with other critical jobs

**Comment by suleymanakbas91** [comment]
The failure notifications are being sent to the `jellyfish-notifications` channel.
