### ISSUE TITLE
Deletion II: clean removal process for Kyma (CR removal, no finalisers dropped etc.)

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#600]
**Description**

The deletion of Kyma has to happen in multiple steps of following sequence:

1. Cleanup Reconciler: Remove CRs
2. Component Reconcilers: delete components by manifest /execute custom deletion actions
3. Base Reconciler: delete CRDs 
4. Cleanup Reconciler: delete resources by labels
5. Cleanup Reconciler: remove namespaces: if they don't get deleted after a timeout, remove finalisers and enforce deletion of namespace

AC:

* Deletion of Kyma happens by following a clean removal approach (drop CRs -> drop resources -> drop CRDs/namespaces) without having a need to remove finalisers from namespaces
* Installation of Kyma on a cluster which had previously Kyma installed works without issues

**Reasons**

Support clean Kyma removal / deletion process.

**Attachments**

**Comment by janmedrek** [comment]
Functionalities of the Reconciler were migrated to the new architecture, this issue will not be worked on.
