### ISSUE TITLE
Refactoring: do not use init-functions for loading component reconcilers

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#602]
**Description**

Currently are init-fcts used to initialise component reconcilers which has the drawback, that the initialisation is always triggered even in test-cases. This limits the flexibility to run other custom code before a component reconciler gets loaded.

Goal of this change is to call not for each component reconciler an init-fct. Instead, the initialisation should happen only by the loader and the component reconciler should just offer a pre-defined callback-fcts which trigger their initialisation.

Example:

In component reconciler is per convention a public fct defined to initialise the particular component reconciler:

     busolaInit = func() error { .... }
      
The loader.go (which is generated by a script) calls these init-fcts inside using a init() fct:

     init() {
        log = logger.NewLogger(false)
        if err != nil busolaInit(); err != nil { log.Error(err) }
        if err !=nil { panic("bootstrap failed") }
     }

Alternative and recommended approach would be to enhance the registry to register the init-fct there and invoke these registered fcts in a loop:

https://github.com/kyma-incubator/reconciler/blob/main/pkg/reconciler/service/registry.go

Like:

     # Before
     func RegisterReconciler(reconcilerName string, reconciler *ComponentReconciler) {
	     reconcilers[reconcilerName] = reconciler
     }
     
     # After
     func RegisterReconciler(reconcilerName string, initFct func() (*ComponentReconciler, error)) error {
            reconciler, err := initFct()
            if err ==nil {
                reconcilers[reconcilerName] = reconciler
            }
	   return err
     }
     

**Reasons**

Increase flexibility when calling component reconcilers by avoid automatically executed logic during loading time of the component reconciler package.

**Attachments**

**Comment by janmedrek** [comment]
Functionalities of the Reconciler were migrated to the new architecture, this issue will not be worked on.
