### ISSUE TITLE
OpsTest II: apply remaining operational test cases for reconciler

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#605]
**Description**

Following operation tests have to be applied before going live:

See https://wiki.wdf.sap.corp/wiki/display/kyma/Reconciler+operational+test

Please create Ops-Test and troubleshooting guides in documentation repository (on-call guides, runtime-4).

* 21
* 23
* 26
* 27
* 28
* 30
* outage-sceanrios (see link in Wiki page at top of the table)

AC:
* Test case protocol created and reviewed for each missing test case
* Trouble shooting guide written and reviewed for incident-cases

**Reasons**

Share operational experiences in the team, get read for on-call shifts.

**Attachments**

**Comment by adityabhatia** [comment]
Please add remaining test case nos. here https://github.com/kyma-incubator/reconciler/issues/1033
