### ISSUE TITLE
Enhance Swagger API docs and generate documentation from swagger doc

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#612]
**Description**

The description  / example fields of the Swagger API specs have to be filled out / enriched to make their purpose obvious and self-explaining. 

See https://github.com/kyma-incubator/reconciler/tree/main/openapi

A markdown document should be generated by using this Swagger doc (like [here](https://goswagger.io/usage/markdown.html)) to offer a simpler way for reading the specification.

AC:
* the description fields are containing a description with a summary what its purpose and how  the endpoint/field it could / should be used
* examples fields are added which include meaningful example-data 
* calling the code-generator for Swagger (see `Makefile`) has also to trigger a re-generation of the markdown file (consider using a Docker container to run the markdown-generator to avoid that developers have to install additional tools on their local system)

**Reasons**

Improve documentation and simplify usage by providing examples.

**Attachments**

**Comment by janmedrek** [comment]
Functionalities of the Reconciler were migrated to the new architecture, this issue will not be worked on.
