### ISSUE TITLE
Use "evaluation" profile consistently in reconciler upgrade pipelines when using `mothership local` command

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#620]
**Description**

Pipelines which are calling the `mothership local` command to trigger a reconciliation have to use the "evaluation" profile per default. This becomes mandatory before we can merge https://github.com/kyma-incubator/reconciler/pull/611.

It has to be verifed, that all existing pipelines are explicitly setting the `--profile evaluation` flag when calling the `mothership local` command.

This is require to get all existing upgrade-pipeline properly working.

**Expected result**

Pipelines which are executing `mothership local` are explicitly using the `evalutation` profile.

**Actual result**

Currently is not confirmed that all CI/CD pipelines are using the `evaluation` profile.

**Steps to reproduce**

**Troubleshooting**

**Comment by dbadura** [comment]
I couldn't find a place where we run `mothership local`.
In e2e upgrade test we are using `Evaluation` profile: https://github.com/kyma-project/control-plane/blob/95cfea92e170016143fb5060d01bf491196b7ce2/tools/reconciler/e2e-test/template.json#L14

**Comment by janmedrek** [comment]
Functionalities of the Reconciler were migrated to the new architecture, this issue will not be worked on.
