### ISSUE TITLE
Micro-Delivery: Setup nightly Jobs for Develop Branch incl. Refactoring of existing Jobs

### ISSUE THREAD

**Issue by jeremyharisch** [kyma-incubator/reconciler#622]
**Description**

In https://github.com/kyma-incubator/reconciler/issues/458 the `develop` branch was created and pre-/post-PR jobs have been created. Due to the current implementation of the Reconciler e2e and CLI Upgrade pipelines, the implementation of the same pipelines for the `develop` branch have been moved to this follow-up issue.

Currently the CLI Upgrade pipelines are not using the latest reconciler main branch.  Currently they are implemented to use the [latest released CLI version](https://github.com/kyma-project/test-infra/blob/main/prow/scripts/lib/kyma.sh#L126). But they should use the CLI with the latest Reconciler version, thus using the [stable CLI](https://github.com/kyma-project/test-infra/blob/main/prow/scripts/lib/kyma.sh#L101) would also not be sufficient. These need to be refactored in a way that it can also be easily adopted in new jobs to also run the same scenarios for the `develop` branch. These jobs also need to be implemented.

The implementation for the Reconciler e2e test are currently based on the image which is stated inside of the reconciler chart in [the control-plane](https://github.com/kyma-project/control-plane/blob/main/resources/kcp/values.yaml#L5). This image currently needs to be updated by merging a PR created by Kyma-Bot after a PR in the Reconciler repo gets merged. Maybe consider coming up with a different approach, to also have a similar job in place for testing the scenarios with the latest Reconciler develop branch.

**AC:**

- [x] Implement Reconciler test pipelines:

    1.  [x] `nightly-main-reconciler` is creating one-day running cluster instances (see also #773 ) - Just sued for cluster creation, please give the created cluster a reasonable name including the weekday
    2. [x] `pre-commit-main-reconciler-e2e` which runs for each open PR to `main`-branch in reconciler repository a test cycle using reconciler build from the PR, it should use the cluster from `nightly-main-reconciler` job **this should be required job for PR (can't merge PR if failed)** --> Done with [pre-main-control-plane-reconciler-e2e](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/pr-logs/directory/pre-main-control-plane-reconciler-e2e)
- [x] Run the `nightly-main-reconciler-publish-unstable-cli` pipeline after a merge to reconciler `main`-branch happened; 
- [x] Refactor the following pipelines to actually use the unstable Kyma CLI (the one which is published by `nightly-main-reconciler-publish-unstable-cli`)
    - kyma-upgrade-gardener-kyma-to-kyma2
    - kyma-upgrade-gardener-kyma2-to-main
    - kyma-upgrade-k3d-kyma-to-kyma2
    - kyma-upgrade-k3d-kyma2-to-main
- [ ] Implement the following pipelines also for the develop branch in reconciler repo; So they should do the exact same as the origin pipelines (the ons above), but instead using the latest published unstable CLI, they should clone the CLI repo, upgrade the reconciler dependency to develop branch of reconciler repo, and run the tests; Furthermore, come up with sufficient names to have a better distinction between the job from unstable CLI and develop branch of reconciler repo
    - kyma-upgrade-gardener-kyma-to-kyma2
    - kyma-upgrade-gardener-kyma2-to-main
    - kyma-upgrade-k3d-kyma-to-kyma2
    - kyma-upgrade-k3d-kyma2-to-main
- [x] Update Wiki page regarding all pipelines 

Implementation Hint:
For the refactoring of the CLI upgrade Jobs maybe consider using the pushed binaries of the `nightly-main-reconciler-publish-unstable-cli` job, to always use the latest main version. Plus refactor the script of this job, so it can bump the reconciler version to latest main and develop, and thus implement a job for pushing unstable develop binaries. Use these binaries then for the new jobs.

**Comment by tobiscr** [comment]
Related to #784

**Comment by ruanxin** [comment]
I will first implement `pre-commit-main-reconciler-e2e`

**Comment by ruanxin** [comment]
The PR for `nightly-develop-reconciler` and `nightly-develop-reconciler-e2e` https://github.com/kyma-project/test-infra/pull/4920

**Comment by Tomasz-Smelcerz-SAP** [comment]
I will work on:

-    kyma-cli-dev-upgrade-gardener-kyma2-to-main
-   kyma-cli-dev-upgrade-k3d-kyma2-to-main

**Comment by jeremyharisch** [comment]
Reopened, since we want to implement the develop branch

**Comment by jeremyharisch** [comment]
Missing steps will be fixed with: https://github.com/kyma-project/test-infra/pull/5031
Regarding: 
```
Implement the following pipelines also for the develop branch in reconciler repo; So they should do the exact same as the origin pipelines (the ons above), but instead using the latest published unstable CLI, they should clone the CLI repo, upgrade the reconciler dependency to develop branch of reconciler repo, and run the tests; Furthermore, come up with sufficient names to have a better distinction between the job from unstable CLI and develop branch of reconciler repo

kyma-upgrade-gardener-kyma-to-kyma2
kyma-upgrade-gardener-kyma2-to-main
kyma-upgrade-k3d-kyma-to-kyma2
kyma-upgrade-k3d-kyma2-to-main
```

A follow-up issues will be openend

**Comment by jeremyharisch** [comment]
https://github.com/kyma-project/test-infra/pull/5031

Some small changes fixed with this. But since we will not implement the dev branch, will close this issue
