### ISSUE TITLE
Modifications to Gateway resource does not reconcile

### ISSUE THREAD

**Issue by raypinto** [kyma-incubator/reconciler#626]
**Description**

When the Gateway resource is modified, the reconciler does not reconcile the resource to the original state. This is a problem because when the port is modified, then the APIRules are not reachable. Only deletion of the gateway resource, reconciles it properly.

**Expected result**

Modified gateway resource reconciles it to the original state.

**Actual result**

The Gatway resource is not reconciled.

**Steps to reproduce**

- Install Kyma 2.0.
- Create an APIRule and make sure it is reachable.
- Modify the port value for the `kyma-gateway` resource using the command: `kubectl edit gateway kyma-gateway -n kyma-system`. The APIRule would no longer be reachable
- Run the reconciler.
- The APIRule is still not reachable.

**Troubleshooting**

**Comment by pbochynski** [comment]
Please provide a troubleshooting guide that in such case you can delete the resource to have it reinstalled.

**Comment by mmitoraj** [comment]
Please find a follow-up for the troubleshooting guide here -> https://github.com/kyma-project/kyma/issues/12950

**Comment by tobiscr** [comment]
Chance is high that this issue is related to #678
