### ISSUE TITLE
Modifications and deletions of Istio-healthz VS are not reconciled properly

### ISSUE THREAD

**Issue by Kaktusowy500** [kyma-incubator/reconciler#631]
**Description**
When `istio-healthz` virtual service is deleted, reconciler restores it into a wrong namespace(`kyma-system` instead of `istio-system`). Also when port property of Istio-healthz is changed, reconciliation doesn't restore it to original value. Only deletion of Istio-healthz, reconciles port number properly(resource is still in wrong namespace). Istio-healthz resource was added in this [PR](https://github.com/kyma-project/kyma/pull/12754)(it is not available in kyma 2.0.0).

**Expected result**
During reconciliation Istio-healthz is restored into Istio-system namespace and port property is restored to original value. 

**Actual result**
During reconciliation Istio-healthz is restored into kyma-system namespace, port property is not restored to original value. 

**Steps to reproduce**
- Install kyma from: `main` using reconciler `./bin/mothership-darwin local --value=global.domainName=<domain_name>  --profile=production`
- delete istio-healthz VS: `k delete virtualservice istio-healthz -n istio-system`
- reconcile certificates: `./bin/mothership-darwin local --value=global.domainName=<domain_name> --components certificates  --profile=production`
- check virtual services: `k get virtualservices.networking.istio.io --all-namespaces`
- istio-healtz VS is restored into kyma-system namespace
- change port property in Istio-healthz and reconcile again
- port is not restored to original value

**Troubleshooting**

**Comment by clebs** [comment]
Checked with the team and this seems to not be an issue anymore.
