### ISSUE TITLE
Delete: Finalisers still get stuck and gardener can't deprovision

### ISSUE THREAD

**Issue by clebs** [kyma-incubator/reconciler#647]
**Description**

After adding the temporary cleanup after deletion it is still not working as expected. Resources need to be removed so that finalisers do not get stuck.

**Expected result**
After delete reconciliation gardener can deprovision the cluster without issues.

**Actual result**
Gardener can not deprovison the cluster because of stuck finalisers/namespaces.

**Steps to reproduce**

1. Provision a gardener cluster
2. Install Kyma via reconciler (e.g. `kyma deploy`)
3. Delete Kyma via reconciler (e.g. `kyma undeploy`)
4. Delete the cluster on gardener and check if it gets stuck.

**Troubleshooting**
Suggested way to find out the resources that block the deprovisioning:
- Do the steps to reproduce
- When deprovisioning gets stuck, check on gardener UI which will tell what resurce is blocking the deprovisioning.

**Comment by Tomasz-Smelcerz-SAP** [comment]
I have found the following error in Gardener using the procedure:
```
Flow "Shoot cluster deletion" encountered task errors: [task "Cleaning Kubernetes resources" failed: 1 error occurred:
	* retry failed with context deadline exceeded, last error: remaining objects are still present: [*v1.PersistentVolumeClaim kyma-system/data-helm-broker-etcd-stateful-0 *v1.PersistentVolumeClaim kyma-system/data-ory-postgresql-0 *v1.PersistentVolumeClaim kyma-system/prometheus-monitoring-prometheus-db-prometheus-monitoring-prometheus-0 *v1.PersistentVolumeClaim kyma-system/storage-logging-loki-0]
```

**Comment by tobiscr** [comment]
Conclusion: detect orphan resources and remove them

1. query for all resources which are terminating for a particular time
2. delete these resources by dropping their finalizers

**Comment by Tomasz-Smelcerz-SAP** [comment]
Another error to consider, this one may be transient:
```
Action required
 Cleaning up the cluster failed as some resource are stuck in deletion. Please remove these resources properly or a forceful deletion will happen if this error persists. 

task "Cleaning extended API groups" failed: 1 error occurred:
	* retry failed with context deadline exceeded, last error: remaining objects are still present: [*v1.CustomResourceDefinition /clusterassets.rafter.kyma-project.io *v1.CustomResourceDefinition /clusterbuckets.rafter.kyma-project.io *v1.CustomResourceDefinition /clusterservicebrokers.servicecatalog.k8s.io]

```

**Comment by Tomasz-Smelcerz-SAP** [comment]
Another cluster, Azure:
```
Action required
 Cleaning up the cluster failed as some resource are stuck in deletion. Please remove these resources properly or a forceful deletion will happen if this error persists. 

task "Cleaning Kubernetes resources" failed: 1 error occurred:
	* retry failed with context deadline exceeded, last error: remaining objects are still present: [*v1.PersistentVolumeClaim kyma-system/data-helm-broker-etcd-stateful-0 *v1.PersistentVolumeClaim kyma-system/data-ory-postgresql-0 *v1.PersistentVolumeClaim kyma-system/prometheus-monitoring-prometheus-db-prometheus-monitoring-prometheus-0 *v1.PersistentVolumeClaim kyma-system/storage-logging-loki-0]

```

**Comment by Tomasz-Smelcerz-SAP** [comment]
It turns out you can't drop finalizers from PVCs. I tried different code and even kubectl, but k8s controller immediatelly restores it - at least that is how it looks like, because I don't get any errors on update operation.

**Comment by Tomasz-Smelcerz-SAP** [comment]
Probably we need to delete the PV first. With Pods gone and no PV, PVC should be recclaimed automatically during delete.
Removing PV's automatically is dangerous though - these are data volumes.

**Comment by Tomasz-Smelcerz-SAP** [comment]
All my attempts failed so far :( I even have a problem to do it manually with kubectl. I have found [this](https://stackoverflow.com/questions/54629660/kubernetes-how-do-i-delete-pv-in-the-correct-manner), I will try these hints. 
However, Helm seems to have no problem to delete PV and related PVC. The problem is, not all our components are managed by Helm. The one with custom reconcilers leak PV/PVC.

**Comment by tobiscr** [comment]
**For SKR:**
We DROP ALL CRs - independent where they come from, technically doable by:

retrieve CRDs from cluster
loop through the list and delete all of them

**For OS:**
We DROP ONLY CRs from Kyma, technically doable by:

retrieve CRS from Kyma sources
loop through the list and delete all of them

**Comment by Tomasz-Smelcerz-SAP** [comment]
PR: https://github.com/kyma-incubator/reconciler/pull/712

**Comment by Sawthis** [comment]
There are no problems with deprovisioning now.
