### ISSUE TITLE
Kubernetes Secret not updated by reconciler during a Kyma upgrade

### ISSUE THREAD

**Issue by chrkl** [kyma-incubator/reconciler#650]
**Description**

When upgrading a Kyma cluster from version 1.24.8 to 2.0 using KEB with the reconciler, the `monitoring-auth-proxy-grafana` Secret in the `kyma-system` namespace should be updated and Dex related environment variables removed (e.g., the `OAUTH2_PROXY_OIDC_ISSUER_URL` reference to the DEX service).

**Expected result**

The Secret should be upgrade according to the [template](https://github.com/kyma-project/kyma/blob/main/resources/monitoring/charts/grafana/templates/kyma-additions/auth-proxy-secret.yaml) in the 2.0 release.

**Actual result**

The mentioned Secret has been processed by the reconciler in some way since it has the `reconciler.kyma-project.io/managed-by-reconciler-disclaimer` annotation and `reconciler.kyma-project.io/*` labels after the upgrade. However, the data part still contains the `OAUTH2_PROXY_OIDC_ISSUER_URL` environment variable, which can only originate from the Kyma 1.x charts (compare the Kyma [1.24](https://github.com/kyma-project/kyma/blob/release-1.24/resources/monitoring/charts/grafana/templates/kyma-additions/auth-proxy-secret.yaml) and [2.0](https://github.com/kyma-project/kyma/blob/release-2.0/resources/monitoring/charts/grafana/templates/kyma-additions/auth-proxy-secret.yaml) templates).  The auth-proxy cannot reach Dex and turns to a crash loop.

**Steps to reproduce**

- Create a Kyma 1.24.8 cluster using KEB
- Trigger upgrade to Kyma 2.0.0
- Check state of the kyma-system/monitoring-auth-proxy-grafana Pod and kyma-system/monitoring-auth-proxy-grafana Secret

**Troubleshooting**

This happens only using KEB. Upgrading a cluster using `kyma deploy` works (activate the auth-proxy on Kyma 1.x before the upgrade for testing)

**Comment by chrkl** [comment]
Some additional investigations have shown that the Secret contains entries from both the Kyma 1.24.x and 2.0 charts after the upgrade. The Secrets have been merged.

**Comment by tobiscr** [comment]
Ok, but that's intended after we were moving back to PATCH instead REPLACE strategy in the reconciler.

We have to challenge how we want to deal with delete/delta cases in the long term. Right now we merge things like `kubectl apply` would do it

**Comment by chrkl** [comment]
We mitigated the issue with upgrading the monitoring chart by renaming the Secret. I'm fine to close this ticket.

**Comment by pbochynski** [comment]
We need to document what is the reconciliation strategy and stick to it. Right now our discussion went into the direction that reconciler is not deleting resources/attributes. Therefore removal of attributes won't be implemented. I will kee the ticket open until we have clear strategy documented.
