### ISSUE TITLE
upgrade: can't change monitoring resource requests/limits

### ISSUE THREAD

**Issue by clebs** [kyma-incubator/reconciler#662]
**Description**

When executing an upgrade containing different resource requests or limits for prometheus, they remain unchanged.

**Expected result**

Resources have the new values given in the upgrade.

**Actual result**

Resources remain unchanged and have the values previous to the upgrade.

**Steps to reproduce**

1. Install kyma on a cluster (e.g. `kyma deploy` on `k3d`)
2. Run an upgrade on monitoring with changed resource request for CPU (`kyma deploy --component monitoring --value "prometheus.prometheusSpec.resources.requests.cpu=150m"`)

**Troubleshooting**

**Comment by tobiscr** [comment]
Verified our upgrade behaviour for resource limits, no issue could be found so far.

**Comment by a-thaler** [comment]
It must be `kyma deploy --component monitoring --value "monitoring.prometheus.prometheusSpec.resources.requests.cpu=150m"`

**Comment by clebs** [comment]
Issue is caused by K8s not supporting CRs in patch strategy:
https://github.com/redhat-cop/resource-locker-operator/issues/63

We need to discuss how to deal with this scenario.

**Comment by clebs** [comment]
After discussing with the team, we will build a configuration into the strategy resolver so that specific resources (group, kind, name) can be configured to use the desired strategy.

**Comment by tobiscr** [comment]
Fixed in https://github.com/kyma-incubator/reconciler/pull/679

**Comment by a-thaler** [comment]
I verified it with the CLI 2.0.3 release containing the related reconciler fixed and it worked well.
