### ISSUE TITLE
Support automated DB migration script testing in CI/CD pipeline

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#666]
**Description**

The CI/CD pipeline used for validating PRs has to be enhanced to start additional testing routines if a [DB migration script](https://github.com/kyma-incubator/reconciler/tree/main/configs/db/postgres) was added / modified.

The validation should include:

* usage of Postgres DB
* Import a dump of a reconciler DB (e.g. from our DEV landscape) which contains a bigger amount of test data
* Update the content of the `inventory_cluster.kubeconfig` column (mandatory to avoid that the CI/CD pipeline starts interfering with exiting Kyma clusters on DEV) and let them point to a test cluster
* run `migrate` command and migrate DB up
* run `migrate` command and migrate DB down
* run `migrate` command and migrate DB up
* run integration tests using Postgres DB

AC:
* CI/CD runs special test-routines if a PR includes DB migration scripts
* CI/CD validates the `migrate up/down` to ensure the migration scripts have no problems on Posgres

**Reasons**

Ensure DB migration script are validated before deployed on KCP landscapes.

**Attachments**

**Comment by jakobmoellersap** [comment]
Looking into feasability of DB Dump before proceeding

**Comment by janmedrek** [comment]
Functionalities of the Reconciler were migrated to the new architecture, this issue will not be worked on.
