### ISSUE TITLE
Kitbag: implement command to dump reconciler DB from KCP to local DB

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#667]
**Description**

For development purposes it can be necessary to test the mothership reconciler using production-comparable data sets. The Kitbag tool should support this use case by offering a command which:

1. Dump the DB content from KCP DEV to local disc
2. Imports it to a local Postgres DB
3. Replaces the content of `inventory_cluster.kubeconfig` column with the local kubeconfig

AC:
* A new command or plugin is added to Kitbag which supports dumping, importing and the KCP reconciler DB content into a local Postgres DB
* The naming and place of the command is aligned with the Kitbag command structure
* The command replaces the content of the `inventory_cluster.kubeconfig` column with the local kubeconfig content

**Reasons**

Simplify DB data dump and import into local Postgres instances for development purposes.

**Attachments**

**Comment by janmedrek** [comment]
Functionalities of the Reconciler were migrated to the new architecture, this issue will not be worked on.
