### ISSUE TITLE
K8s API error patching CRs is not caught

### ISSUE THREAD

**Issue by clebs** [kyma-incubator/reconciler#670]
**Description**

K8s does not support patch strategy for CRs and kubectl des return an error when trying to patch a CR. But for an unknown reason the reconciler does not.

**Expected result**

Error is returned when patching a CR and process is stopped.

**Actual result**

Reconciler returns success and CR does not have the changes applied.

**Steps to reproduce**

1. Deploy Kyma into a cluster
2. Upgrade a component containing a CR (e.g. monitoring) having changes on the CR
3. Check the CR after the update and see that it is not updated.

**Troubleshooting**
Issue was discovered in: #662
See https://github.com/kubernetes/kubernetes/issues/97423

**Comment by tobiscr** [comment]
We are facing some weird error messages after Helm call was trying to patch a CR:

    #1: unable to build kubernetes objects from current manifest: unable to recognize "": Get "https://api.c-64c814d.stage.kyma.ondemand.com/api?timeout=32s": dial tcp: lookup api.c-64c814d.stage.kyma.ondemand.com on 192.168.178.1:53: no such host
    #2: Failed to get manifest for component 'monitoring' in Kyma version '2.0.0': failed helm client render: loader failed to load helm chart: Chart.yaml file is missing


    2022-01-14T15:30:36.676+0100	DEBUG	invoker/localinvoker.go:107	Local invoker is updating operation (schedulingID:local--64506ecc-f620-446c-80e3-135f3a312edf/correlationID:local--0311a26a-a048-40aa-ab97-ebea3c83e1df) to state 'failed': Failed to get manifest for component 'monitoring' in Kyma version '2.0.0': failed helm client render: loader failed to load helm chart: open /Users/d069409/.kyma/sources/2.0.0/resources/monitoring/.helmignore: too many open files


We assume these issues are side-effects of the failed patch call.

**Comment by tobiscr** [comment]
This issue is probably obsolete since #678 is in place.

**Comment by tobiscr** [comment]
Has to be verified if this was an error at all. Issue was probably caused by wrong call of the Helm Client when processing CRDS.

@clebs  / @ruanxin  - can you confirm this assumption? If yes, let's close this issue as obsolete.

**Comment by clebs** [comment]
Yes, that was the case. This can be closed.
