### ISSUE TITLE
Reconciler down on KCP Staging/Canary

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#674]
**Description**

Reconciler is down on Staging. Hint from @ebensom : the liveness probe was restarting the pod before the migration was finished. This would also explain the why during the investigation of issue  #659 the issue didn't occur when running the migration locally.

The issue is happening caused by the huge amount of operations-data in the DB and should not occur again when #668 is implemented.

Options to solve the issue:

_Option A:_
1. Take DB backup
2. Edit deployment of mothership-reconciler and increase temporarily the liveness probe delay to ensure the liveness probe runs after the migration, e.g. 30min 
3. Downgrade to schema version 7 
4. Start mothership reconciler to trigger another migration to schema 8

_Option B:_
1. Take DB backup
2. Connect to DB (e.g. via deploying a [dbproxy](https://github.com/kyma-incubator/reconciler/files/7865505/dbproxy.yaml.zip)) and verify manually the applied DB migration steps - apply the missing steps manually
3. Remove dirty-flag for this schema from DB migration table
4. Start mothership reconciler 

**Expected result**

Mothership reconciler can be deployed on Canary landscape without issues.

**Actual result**

Pod gets restarted on Canary because migration script takes too long and liveness probe fails.

**Steps to reproduce**

**Comment by ebensom** [comment]
Together with @I553979 (Ali) we applied a hybrid of _Option A_ and _B_ . The migration in mothership-reconciléer could finish in 14 minutes and the pod could become ready

**Comment by ebensom** [comment]
All running well now.
