### ISSUE TITLE
Run DB migration in init-container to avoid false-positive liveness-probes

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#677]
**Description**

The DB migration can take several minutes for a fully productive mothership reconciler as the amount of data can become quite huge.

In the past, we had the challenge that the K8s liveness-probe was triggered while a DB migration was ongoing and reported the mothership-pod to be down. This caused a restart of the pod while the DB migration was still ongoing, and caused finally a dirty/incomplete DB schema migration.

To avoid this issue, we decided to move the DB migration step into an init-container. The init-container is not considered by the liveness-probe, and we can avoid such colliding situations. We agreed on the following approach:

1. Mothership reconciler gets extended by a flag (e.g. `--stop-after-migrate` or similar) which lead the mothership-reconciler to stop after the DB migration is finished.
2. The K8s deployment of the mothership-reconciler gets extended by an init-container which runs the mothership-reconciler and sets also the `--stop-after-migrate` (or similar, see step 1). This will run the DB migration up-front and allows even to run custom logic between migration steps without being considered by the liveness-probe.
3. The GCP cloud_sql_proxy container gets extracted to a separate deployment and service, and the mothership reconciler configuration is adapted to point to the new service for the cloud_sql_proxy 

AC:
* Mothership reconciler has to be extended by a flag which lets the mothership-reconciler process stop after the DB migration is finished.
* GCP cloud_sql_proxy container is deployed separately, and the mothership deployment is configured to communicate with the DB using the cloud_sql_proxy service.
* An init container is added to the K8s deployment of the mothership-reconciler, which starts the mothership-reconciler and sets the new flag  to ensure the process stops after it has migrated the DB schema.

**Reasons**

Solve issue that mothership-reconciler gets restarted by failing liveness-probe if a long-running DB migration is happening.

**Attachments**

**Comment by janmedrek** [comment]
Functionalities of the Reconciler were migrated to the new architecture, this issue will not be worked on.
