### ISSUE TITLE
Update CR resources in K8s without replacing them

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#678]
**Description**

As result of #662 we realized that CRs are not updated when using a pure Patch strategy. The reconciler has to come upwith a solution for updating CRs.

We have to define an approach which identifies deltas between the CR defined in the manifest and the CR on the server. It The differences have to be updated on the server by the values defined in the manifest (e.g. by sending [JSON patch](http://jsonpatch.com/#replace) calls which replace the differences in the CR).

AC:
* CRs are excluded from being patched via the Helm client (because pure patch calls are not working and even leading to weird behaviours, see comments in #670 )
* Differences between the CR defined in the manifest and the CR on the server are detected and overwritten with the values defined in the manifest (e.g. by sending Json+Patch calls).
* The changes applied in #662 (is a hack which was just applied to unblock us, see `UpdateStrategyResolver`) have to be removed

**Reasons**

Support updating CRs by the reconciler.

**Attachments**

**Comment by rakesh-garimella** [comment]
The CR for peer authentication is not being touched at all after the upgrade. I see following annotation missing:
```
reconciler.kyma-project.io/managed-by-reconciler-disclaimer:
```

Below is the CR after upgrade
```
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  annotations:
    meta.helm.sh/release-name: monitoring
    meta.helm.sh/release-namespace: kyma-system
  creationTimestamp: "2022-01-27T12:02:31Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
  name: monitoring-grafana-policy
  namespace: kyma-system
  resourceVersion: "9014"
  uid: 5b71a6f9-3fa0-4c5e-99cc-1d0a262fc322
spec:
  mtls:
    mode: PERMISSIVE
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana
```

**Comment by ruanxin** [comment]
PR: https://github.com/kyma-incubator/reconciler/pull/748
