### ISSUE TITLE
Delete: finalizer get stuck again

### ISSUE THREAD

**Issue by Wawrzyn321** [kyma-incubator/reconciler#683]
**Description**

We cannot remove the [nkyma cluster](https://dashboard.garden.canary.k8s.ondemand.com/namespace/garden-kyma-prow/shoots/nkyma/), as it waits for some PVCs to be deleted. Somehow the `kyma-system` namespace is deleted, but PVCs residing inside are not.

**Expected result**

Cluster shuts down with no problems.

**Actual result**

Cluster gets stuck, waiting for those PVCs' finalizers.

**Steps to reproduce**

It happens on Mondays (17.01 & 10.01).

**Troubleshooting**

```
kubectl create ns kyma-system || true
kubectl -n kyma-system patch pvc data-helm-broker-etcd-stateful-0 -p '{"metadata":{"finalizers": []}}' --type=merge || true
kubectl -n kyma-system patch pvc data-ory-postgresql-0 -p '{"metadata":{"finalizers": []}}' --type=merge || true
kubectl -n kyma-system patch pvc storage-logging-loki-0 -p '{"metadata":{"finalizers": []}}' --type=merge || true
kubectl -n kyma-system patch pvc prometheus-monitoring-prometheus-db-prometheus-monitoring-prometheus-0 -p '{"metadata":{"finalizers": []}}' --type=merge || true
```

**Comment by Wawrzyn321** [comment]
Possibly connected to #682

**Comment by valentinvieriu** [comment]
The Deletion of the cluster is stuck. See logs 
https://storage.googleapis.com/kyma-prow-logs/logs/kyma-weekly-gardener-gcp-busola-kyma/1482910731522281472/build-log.txt

And in Gardener you see the error
![image](https://user-images.githubusercontent.com/478866/149743842-836a6e39-f212-433f-82ae-f2c4ae3537f7.png)

**Comment by tobiscr** [comment]
Should actually already be fixed in #647

**Comment by tobiscr** [comment]
Stable CLI was outdated and didn't include the latest reconciler fixes. The coming CLi stable version is using an udpated version and issue should be gone.

**Comment by tobiscr** [comment]
@Wawrzyn321: are you using the CLI or KCP-DEV reconciler for deleting the cluster?

**Comment by Wawrzyn321** [comment]
Hi, I didn't delete that cluster - it was already stuck on deletion when I noticed the issue. If I were to delete a cluster, I'd use Gardener.

**Comment by Wawrzyn321** [comment]
I asked around, this cluster is removed via Kyma CLI.

**Comment by Wawrzyn321** [comment]
(Kyma CLI version: Kyma CLI version: stable-22362b8)

**Comment by Halamix2** [comment]
- CLI 22362b8 uses Reconciler in version fe5f865b7552, which doesn't contain https://github.com/kyma-incubator/reconciler/pull/669 fix

**Comment by m00g3n** [comment]
The reconciler was bumped up to this [commit](https://github.com/kyma-incubator/reconciler/commit/5903eae79353211385943d862dac02d9921879f5) in the `CLI repo`: [74cabfe](https://github.com/kyma-project/cli/pull/1143).
