### ISSUE TITLE
Well defined actions for Istio reconciler

### ISSUE THREAD

**Issue by strekm** [kyma-incubator/reconciler#705]
**Description**

Istio reconciler should have well defined actions which represents flow of Istio installation / upgrade.

**AC**
- [x] sanity checks which are pre action responsible for checking version mismatch on the cluster and client compatibility
- [x] Istio reconcile command which is main action responsible for installation / upgrade of Istio
- [x] mutating webhook configuration patch command responsible for applying proper sidecar injection configuration
- [x] proxy reset command which is post action responsible for reseting sidecars

**Reasons**

Having single responsibility components and getting rid of technical debt

**Attachments**

https://github.com/kyma-incubator/reconciler/issues/543

**Comment by mjakobczyk** [comment]
During the conversation with @werdes72 we did the following:
- checked the actions flow of the Reconciler runner - when any action fails then full chain is repeated from scratch (not only failed action)
- as a result we decided that sanity checks for Istio can be done as a separate action not to be repeated every time
- still Istio status should be fetched in every reconciler action (not once for the chain)
- main reconcile action should be about handling Istio itself so it should manage installation and upgrade
- there can be two post actions - the first one for webhook and second one for proxy reset
- Acs were updated appropriately
