### ISSUE TITLE
CP Reconciler Improvements

### ISSUE THREAD

**Issue by ralikio** [kyma-incubator/reconciler#706]
**Description**

* ~~Git Repo Cache - check if caching is in place, If not consider implementing one.~~ - Reconciler does not clone repo if one with correct version is already in place.
* ~~Specific Version Cloning - check if git clone supports version branches.~~ - irrelevant - one can use fork repository with frozen version.
* Manifest Comparison - Trigger installation if at least one resource disappears from the cluster. Make installation dependent on all resources from rendered manifests (not on a single one). Remember about release version workaround to fix corrupted (e.g. removed) components.

**Comment by Disper** [comment]
@I542535 please provide more context using [issue template](https://github.com/kyma-incubator/reconciler/issues/new?assignees=&labels=&template=feature-request.md)

**Comment by ralikio** [comment]
I verified first 2 points and they are not problematic as explained above. Third issue moved to https://github.com/kyma-incubator/reconciler/issues/716. @Disper  "Reasons" and "Attachments" sections do not bring any value. Description is self-explanatory.

**Comment by Disper** [comment]
@ralikio While it's not always possible to provide anything in the **Attachments** area, I would disagree that **Reasons** is meaningless. The one you've provided in #716 explains nicely **why** someone should work on the issue and without it and should  help with the prioritisation and finding the right solution.
