### ISSUE TITLE
Re-create cluster used in nightly-main-reconciler-e2e

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#713]
**Description**

The Prow job ` nightly-main-reconciler-e2e` is failing since Friday afternoon caused by timeout issue in CommerceMock tests:

      Executing Standard Testsuite:
        CommerceMock Tests:
           ✓ Listing all pods in cluster
     Error: Waiting for lastorder function timeout (90000 ms)

See job logs attached:  [build-log-e2e.txt.zip](https://github.com/kyma-incubator/reconciler/files/7937381/build-log-e2e.txt.zip)

Proposal from @pbochynski is to recreate the cluster to ensure it's not an infrastructure issue.

**Expected result**

Job should not end up in a timeout when waiting for a last order.

**Actual result**

Tests are consistently failing when waiting for last order. 

**Steps to reproduce**

**Troubleshooting**

**Comment by pPrecel** [comment]
This test was failing because of the same reason as the Issue [here](https://github.com/kyma-project/control-plane/issues/1296) and it's already fixed
