### ISSUE TITLE
Make sure all pipelines are using newest released Kyma version

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#714]
**Description**

We are running a bunch of CI/CD pipelines which use the CLI to deploy a Kyma cluster. These CLIs versions are currently hardcoded and not cluster-wide defined.

New CLi versions require always an upgrade of multiple CI/CD pipelines. Goal of this task it to verify whether we can centralise the version of the used CLI (e.g. using a env-var ) and if possible to adjust our PROW jobs to ensure the used CLI fits to this version.

AC:
* Figure out how PROW wide variables can be confiugred
* If PROW wide variables are supported:
     * define a central configuration variable which includes the CLI version our CI/CD jobs have to use
     * adjust our CI/CD jobs to use this centralized version of the CLI (download it if missing)

**Reasons**

Consolidate our CI/CD job structure and make the CLI version globally configurable for all Jellyfish jobs (simplify maintenance of our pipelines).

**Attachments**

**Comment by jeremyharisch** [comment]
Two pipelines needed to be adapt, which is fixed with this PR: https://github.com/kyma-project/test-infra/pull/4828

Our Wiki page has been updated with more information regarding our periodic pipelines.

**Comment by jeremyharisch** [comment]
PR got merged. will updated our wiki
