### ISSUE TITLE
Cleaner reconciler runs on non-delete reconciliations

### ISSUE THREAD

**Issue by clebs** [kyma-incubator/reconciler#715]
**Description**
The `cleaner` internal component is added to the reconciliation sequence always when starting a reconciliation. But it should only be added to "delete" reconciliations.

**Expected result**

Cleaner does not run on regular reconciliations, only when deleting.

**Actual result**

Cleaner always gets added to the reconciliation sequence regardless of the type of reconciliation.

**Steps to reproduce**
Do a reconciliation in either the CLI or SKR and see cleaner component being deployed.

**Troubleshooting**
When creating the reconciliaiton sequence we only have to add the component when it is a delete reconciliation.

**Comment by jakobmoellersap** [comment]
relates to https://github.com/kyma-project/cli/pull/1205
