### ISSUE TITLE
Connectivity Proxy Reconciler must be able to restore changes made by user

### ISSUE THREAD

**Issue by ralikio** [kyma-incubator/reconciler#716]
**Description**

Connectivity Proxy action installs the chart if the following conditions are met:
- Connectivity Proxy binding exist
- Requested chart version is not equal to the version installed on the cluster

As a result Connectivity Proxy action will not restore changes made by the user if the chart version is not changed. In order to ensure correct behaviour the action should only check whether the binding exists.

**Expected result**

Connectivity Proxy reconciliation action must always be able to restore changes made by the user. 

**Actual result**

Changes done by the user (k8s objects removal or modification) won't be reverted if Connectivity Proxy chart version is the same as installed on the cluster.  

**Steps to reproduce**
1. Install a new cluster with Connectivity Proxy.
2. Create Connectivity Proxy instance and binding on the cluster.
3. Remove some k8s objects  (e.g. service) created by applying Connectivity Proxy chart.
4. Wait for next reconciliation (or force it). Notice that removed objects were not restored.

**Comment by janmedrek** [comment]
I've found another edge case in which the whole thing breaks:
- Create Service Instance
- Wait for the Proxy to be installed
- Quickly remove and recreate Service Instance and Binding

This breaks the connection, there are different values in Service Key and the secret in the `kyma-system` namespace, we should verify whether the values in both of those are aligned.

**Comment by janmedrek** [comment]
Will be solved in: https://github.com/kyma-project/kyma/issues/15524
