### ISSUE TITLE
Connectivity Proxy Reconciler - Api Prefix Cleanup

### ISSUE THREAD

**Issue by ralikio** [kyma-incubator/reconciler#720]
**Description**

Remove leftover `api` prefix from [url](https://github.com/kyma-incubator/reconciler/blob/8faf0c044873c6dc8f6ee34e6ba4aa5687bc9c8d/pkg/reconciler/instances/connectivityproxy/action.go#L23) that points to cluster domain. 

**Reasons**

- Current value contains `api` that points to Kubernetes Server.

**Attachments**

- No Attachments

**Comment by janmedrek** [comment]
@ralikio why do we need to remove the prefix? I cannot see it done right now and the functionalities work as expected.

**Comment by Disper** [comment]
@ralikio could you elaborate on the reasons?
