### ISSUE TITLE
Flaky CI/CD pipeline: reports positive-false results (show success but pipeline failed)

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#723]
**Description**

The pipeline `kyma-upgrade-k3d-kyma2-to-main` reports failing runs to be successful (positive-false). Currently, all jobs are failing but some of the are still shown to be successfully finished:

<img width="895" alt="Screen Shot 2022-01-27 at 16 00 29" src="https://user-images.githubusercontent.com/73824711/151384612-53595ef5-3dbf-473f-8ce1-39f6ca17af69.png">

All jobs are failing during the upgrade to main:

     2022/01/26 18:10:27 UTC [INFO] ### Upgrade Kyma to main
     - A Kyma installation with version '2.0.4' was found. Proceeding with upgrade to 'main' in non-interactive mode. 
     - Using Kyma from the workspace directory: /root/.kyma/sources
     - Installed Prerequisites
     Deploying Kyma
     - Component 'cleaner' deployed
     - Component 'CRDs' deployed
     - Component 'certificates' deployed
     - Component 'cluster-essentials' deployed
     - Component 'istio-configuration' deployed
     - Component 'service-catalog-addons' deployed
     - Component 'cluster-users' deployed
     - Component 'helm-broker' deployed
     - Component 'rafter' deployed
     - Component 'service-catalog' deployed
     - Component 'tracing' deployed
     - Component 'eventing' deployed
     - Component 'monitoring' deployed
     - Component 'ory' deployed
     - Component 'serverless' deployed
     - Component 'kiali' deployed
     X Component 'application-connector' failed. Retrying...
     kubeClient failed to update Job 'application-connector-certs-setup-job' (namespace: kyma-integration): All attempts fail:
     #1: cannot patch "application-connector-certs-setup-job" with kind Job: Job.batch "application-connector-certs-setup-job" is invalid: spec.template: Invalid value: core.PodTemplateSpec{ObjectMeta:v1.ObjectMeta{Name:"application-connector-certs-setup-job", GenerateName:"", Namespace:"kyma-integration", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"app.kubernetes.io/instance":"application-connector", "app.kubernetes.io/managed-by":"Helm", "app.kubernetes.io/name":"application-connector", "controller-uid":"ad48bc89-0eb7-4dd1-922d-67d2a796eea5", "helm.sh/chart":"application-connector-1.0.0", "job-name":"application-connector-certs-setup-job", "release":"application-connector"}, Annotations:map[string]string{"sidecar.istio.io/inject":"“false”"}, OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, Spec:core.PodSpec{Volumes:[]core.Volume(nil), InitContainers:[]core.Container(nil), Containers:[]core.Container{core.Container{Name:"application-connector-certs-setup-job", Image:"eu.gcr.io/kyma-project/application-connectivity-certs-setup-job:PR-13170", Command:[]string(nil), Args:[]string{"/app/appconnectivitycertssetupjob", "--connectorCertificateSecret=kyma-integration/connector-service-app-ca", "--caCertificateSecret=istio-system/kyma-gateway-certs-cacert", "--caCertificate=", "--caKey=", "--caCertificateSecretToMigrate=istio-system/app-connect

**Expected result**

Pipeline should fail if the upgrade fails.

**Actual result**

Pipeline is not showing a failure even if the upgrade failed.

**Steps to reproduce**

**Troubleshooting**

**Comment by Tomasz-Smelcerz-SAP** [comment]
The reason for that is a bug in CLI - it returns a zero exit code (success) on timeout: https://github.com/kyma-project/cli/issues/1166

**Comment by Tomasz-Smelcerz-SAP** [comment]
https://github.com/kyma-project/cli/pull/1167

**Comment by jeremyharisch** [comment]
Pr got merged, will close issues.
