### ISSUE TITLE
Helm-Broker fails frequently in CI/CD pipelines

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#724]
**Description**

Helm component fails frequently in CI/CD pipeline [`kyma-upgrade-gardener-kyma-to-kyma2`](https://status.build.kyma-project.io/?job=kyma-upgrade-gardener-kyma-to-kyma2):

     Deployed Components: 16/17
     Could not deploy the following components:
     - helm-broker
     
     Error: Kyma deployment failed.

Issue happens in following runs:

* https://storage.googleapis.com/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma-to-kyma2/1486670526389686272/build-log.txt
* https://storage.googleapis.com/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma-to-kyma2/1486610157105319936/build-log.txt

**Expected result**

Helm-broker could be successfully deployed.

**Actual result**

Component fails (temporarily - maybe flakiness?)

**Steps to reproduce**

**Troubleshooting**

**Comment by ksputo** [comment]
03.01 summary:

- The problem with `helm-broker` not being deployed:
```
Deployed Components: 16/17
Could not deploy the following components:
- helm-broker
``` 

is still happening after merging https://github.com/kyma-incubator/reconciler/pull/748 - this suggests that this is not problem with the CR, but still is hard to reproduce - in last 6 run it happened once [here](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma-to-kyma2/1488814660193882112)

- Other point of failure is waiting for ServiceClass: - [example](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma-to-kyma2/1488844859589529600)
```
       Helm Broker test fixture should be ready:
     Error: Waiting for testing service class timeout (90000 ms)
```

Right now I'm running the customised pipeline without the cleanup part to check the exact helm-broker behaviour when dealing with created resources.

- Last but not least - the pipeline tends to fail right now with error - [example](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma-to-kyma2/1489116554606940160):
```
2022/02/03 06:38:11 UTC [INFO] Running post-upgrade Kyma Fast Integration tests
/home/prow/go/src/github.com/kyma-project/test-infra/prow/scripts/lib/gardener/azure.sh: line 331: pushd: /home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration: No such file or directory
2022/02/03 06:38:11 UTC [ERROR] AN ERROR OCCURED! Take a look at preceding log entries.
```

^ this one is not related with the helm-broker stability and won;t be part of this issue's investigation.

**Comment by tobiscr** [comment]
Thanks @ksputo for your first investigation. The issue you metioed about about non-found fast-integration tests was fixed yesterday.

We are still facing failing updates caused by non-installed helm-broker component:

* https://storage.googleapis.com/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma2-to-main/1489479065785077760/build-log.txt

      Deployed Components: 8/9
      Could not deploy the following components:
      - helm-broker

**Comment by PK85** [comment]
I've never see that error in the skr pipelines, for example: https://storage.googleapis.com/kyma-prow-logs/logs/kyma-preview-integration-dev/1490475395487633408/build-log.txt

**Comment by piotrmiskiewicz** [comment]
this job was green 8 times in a row, looks ok
