### ISSUE TITLE
Pipelines failing because events cannot be sent

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#725]
**Description**

Several pipelines are failing when during the fast-integration test execution when they try to send events:

* [`skr-kyma-to-kyma2-upgrade-aws-dev`](https://storage.googleapis.com/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma2-to-main/1486700725625950208/build-log.txt):

       1) in-cluster event should be delivered
       ✓ function should be reachable through secured API Rule
        Cannot send event, the response from event gateway:
        {
          error: 'Problem while sending event: Kyma application API responded with status 503 "no healthy upstream"'
        }

* [`periodic-main-kyma-incubator-reconciler-kyma1-kyma2-upgrade`](https://storage.googleapis.com/kyma-prow-logs/logs/periodic-main-kyma-incubator-reconciler-kyma1-kyma2-upgrade/1486715825309093888/build-log.txt)

            ✓ in-cluster event should be delivered
            ✓ function should be reachable through secured API Rule
        Cannot send event, the response from event gateway:
        {
          error: 'Error: Client network socket disconnected before secure TLS connection was established'
        }

**Expected result**

Fast integration tests are passing the event-sending check.

**Actual result**

Fast integration tests are failing when trying to send events.

**Steps to reproduce**

**Troubleshooting**

**Comment by veichtj** [comment]
@tobiscr : result after first quick analysis:
Both pipelines are failing because of an introduced issue in kyma / main branch, not 100% sure yet what exactly it is.

But I noticed that the pipeline: `periodic-main-kyma-incubator-reconciler-kyma1-kyma2-upgrade` is not upgrading to kyma 2 instead to kyma main, as already discussed with @jeremyharisch, please checkout this ticket: https://github.com/kyma-incubator/reconciler/issues/694. I noticed that because in the reconciled cluster istio images from solo.io are used, and we not only have them on kyma main, not on kyma 2.

Will update the ticket once I know what exactly changed on kyma main and cause the pipeline failing.

**Comment by veichtj** [comment]
Could not spot any service-mesh related issues, forwarded to eventing team @k15r

**Comment by mfaizanse** [comment]
I faced the same issue on SKR upgraded cluster from 1.24.9 to 2.0.4:
```
Error: Client network socket disconnected before secure TLS connection was established
```

Logs from commerce-mock pod:
```
{"label":"app-connector","level":"debug","message":"Received Body: {\n  \"event-type\": \"order.created\",\n  \"event-type-version\": \"v1\",\n  \"event-time\": \"2022-01-28T15:29:21.424Z\",\n  \"data\": {\n    \"orderCode\": \"76272727\"\n  },\n  \"event-tracing\": true\n}"}
{"label":"app-connector","level":"debug","message":"Sending Header: {\n  \"Content-Type\": \"application/json\",\n  \"x-b3-sampled\": \"1\"\n}"}
{"label":"app-connector","level":"debug","message":"Calling POST on https://gateway.c-7173b37.stage.kyma.ondemand.com/mp-tunas-rt204u/v1/events"}
{"label":"api-server","level":"error","message":"Failed to send legacy event: RequestError: Error: Client network socket disconnected before secure TLS connection was established\n    at new RequestError (/app/node_modules/request-promise-core/lib/errors.js:14:15)\n    at Request.plumbing.callback (/app/node_modules/request-promise-core/lib/plumbing.js:87:29)\n    at Request.RP$callback [as _callback] (/app/node_modules/request-promise-core/lib/plumbing.js:46:31)\n    at self.callback (/app/node_modules/request/request.js:185:22)\n    at Request.emit (events.js:400:28)\n    at Request.onRequestError (/app/node_modules/request/request.js:877:8)\n    at ClientRequest.emit (events.js:400:28)\n    at TLSSocket.socketErrorListener (_http_client.js:475:9)\n    at TLSSocket.emit (events.js:400:28)\n    at emitErrorNT (internal/streams/destroy.js:106:8)\n    at emitErrorCloseNT (internal/streams/destroy.js:74:3)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21) {\n  cause: [Error],\n  error: [Error],\n  options: [Object],\n  response: undefined\n}"}
{"label":"api-server","level":"info","message":"POST /events, status: 500","meta":{"req":{"headers":{"accept":"application/json, text/plain, */*","accept-encoding":"gzip, deflate, br","accept-language":"en-US,en;q=0.9","content-length":"179","content-type":"application/json","host":"commerce.c-7173b37.stage.kyma.ondemand.com","origin":"https://commerce.c-7173b37.stage.kyma.ondemand.com","referer":"https://commerce.c-7173b37.stage.kyma.ondemand.com/","sec-ch-ua":"\" Not;A Brand\";v=\"99\", \"Google Chrome\";v=\"97\", \"Chromium\";v=\"97\"","sec-ch-ua-mobile":"?0","sec-ch-ua-platform":"\"macOS\"","sec-fetch-dest":"empty","sec-fetch-mode":"cors","sec-fetch-site":"same-origin","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36","x-envoy-attempt-count":"1","x-envoy-external-address":"100.96.0.1","x-forwarded-client-cert":"By=spiffe://cluster.local/ns/default/sa/default;Hash=0d5f93529d90d1e8f20048d39f6f3d15d2d4dd6e9246343a81aa7f3988aad642;Subject=\"\";URI=spiffe://cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account","x-forwarded-for":"100.96.0.1","x-forwarded-host":"commerce.c-7173b37.stage.kyma.ondemand.com","x-forwarded-proto":"https","x-request-id":"4e3e2ac2-68b2-4ad5-a394-688b100e4643"},"httpVersion":"1.1","method":"POST","originalUrl":"/events","query":{},"url":"/events"},"res":{"statusCode":500},"responseTime":222}}
```

openssl check:
```
╰─ openssl s_client -connect gateway.c-7173b37.stage.kyma.ondemand.com:443
CONNECTED(00000006)
4619142828:error:140040E5:SSL routines:CONNECT_CR_SRVR_HELLO:ssl handshake failure:/System/Volumes/Data/SWE/macOS/BuildRoots/5b2e67f8af/Library/Caches/com.apple.xbs/Sources/libressl/libressl-75.60.3/libressl-2.8/ssl/ssl_pkt.c:585:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 0 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID:
    Session-ID-ctx:
    Master-Key:
    Start Time: 1643384318
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
---
```

The request doesn't even reached eventing-publisher-proxy. Seems like eventing is not involved at this level.

**Comment by janmedrek** [comment]
For your information: I have tested the upgraded (1.24.9 - 2.0.4) SKR with both Commerce and C4C, could not receive any event as well - serverless functions were not even triggered.
Checked for logs in eventing-publisher-proxy and found none, there were also no errors in the eventing controller.

Unfortunately, I was not able to fetch logs from Commerce/C4C, but I assume the reason is the same as stated by @mfaizanse in the previous comment.

**Comment by janmedrek** [comment]
Tried with the manual flow - I have generated certificates and made a call to the eventing gateway with curl:
```
> curl https://gateway.c-7173b37.stage.kyma.ondemand.com/mp-frog-commerce-mock/v1/events --key generated.key --cacert generated.crt -k -v
*   Trying 35.158.155.24:443...
* Connected to gateway.c-7173b37.stage.kyma.ondemand.com (35.158.155.24) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: generated.crt
*  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to gateway.c-7173b37.stage.kyma.ondemand.com:443
* Closing connection 0
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to gateway.c-7173b37.stage.kyma.ondemand.com:443
```

**Comment by janmedrek** [comment]
Ok, I think I've got this, this is the mTLS gateway used for eventing:
```
kcs get gateways.networking.istio.io kyma-gateway-application-connector -oyaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  annotations:
    meta.helm.sh/release-name: application-connector
    meta.helm.sh/release-namespace: kyma-integration
  creationTimestamp: "2022-01-27T12:02:09Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: application-connector
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: application-connector
    helm.sh/chart: application-connector-1.0.0
    release: application-connector
  managedFields:
  - apiVersion: networking.istio.io/v1alpha3
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:helm.sh/chart: {}
          f:release: {}
      f:spec:
        .: {}
        f:selector:
          .: {}
          f:istio: {}
        f:servers: {}
    manager: kyma-operator
    operation: Update
    time: "2022-01-27T12:02:09Z"
  name: kyma-gateway-application-connector
  namespace: kyma-system
  resourceVersion: "8628"
  uid: 3bc93f0c-1cfb-4f98-bbe2-b0a8807229e3
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - gateway.c-7173b37.stage.kyma.ondemand.com
    port:
      name: https-app-connector
      number: 443
      protocol: HTTPS
    tls:
      cipherSuites:
      - ECDHE-RSA-CHACHA20-POLY1305
      - ECDHE-RSA-AES256-GCM-SHA384
      - ECDHE-RSA-AES256-SHA
      - ECDHE-RSA-AES128-GCM-SHA256
      - ECDHE-RSA-AES128-SHA
      credentialName: app-connector-certs
      minProtocolVersion: TLSV1_2
      mode: MUTUAL
```

The secret `app-connector-certs` is missing, there is no such secret on the cluster - that's why the mTLS calls fail with the TLS error.

I wonder why it's gone. Will follow up in the Runtime Agent, but honestly I have no idea why it's not there.

**Comment by janmedrek** [comment]
Another finding:
```
time="2022-01-28T13:58:50Z" level=info msg="Migrating secret. Source: istio-system/app-connector-certs , target=istio-system/kyma-gateway-certs-cacert."
```

This means that Compass Runtime Agent upon initialization migrated the contents of `istio-system/app-connector-certs` which would suggest that it existed before the upgrade.

@tobiscr do you have any insights on what may cause the issue?

**Comment by janmedrek** [comment]
Tried with the manual flow - I have generated certificates and made a call to the eventing gateway with curl:
```
> curl https://gateway.c-7173b37.stage.kyma.ondemand.com/mp-frog-commerce-mock/v1/events --key generated.key --cacert generated.crt -k -v
*   Trying 35.158.155.24:443...
* Connected to gateway.c-7173b37.stage.kyma.ondemand.com (35.158.155.24) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: generated.crt
*  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to gateway.c-7173b37.stage.kyma.ondemand.com:443
* Closing connection 0
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to gateway.c-7173b37.stage.kyma.ondemand.com:443
```

**Comment by janmedrek** [comment]
Ok, I think I've got this, this is the mTLS gateway used for eventing:
```
kcs get gateways.networking.istio.io kyma-gateway-application-connector -oyaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  annotations:
    meta.helm.sh/release-name: application-connector
    meta.helm.sh/release-namespace: kyma-integration
  creationTimestamp: "2022-01-27T12:02:09Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: application-connector
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: application-connector
    helm.sh/chart: application-connector-1.0.0
    release: application-connector
  managedFields:
  - apiVersion: networking.istio.io/v1alpha3
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:helm.sh/chart: {}
          f:release: {}
      f:spec:
        .: {}
        f:selector:
          .: {}
          f:istio: {}
        f:servers: {}
    manager: kyma-operator
    operation: Update
    time: "2022-01-27T12:02:09Z"
  name: kyma-gateway-application-connector
  namespace: kyma-system
  resourceVersion: "8628"
  uid: 3bc93f0c-1cfb-4f98-bbe2-b0a8807229e3
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - gateway.c-7173b37.stage.kyma.ondemand.com
    port:
      name: https-app-connector
      number: 443
      protocol: HTTPS
    tls:
      cipherSuites:
      - ECDHE-RSA-CHACHA20-POLY1305
      - ECDHE-RSA-AES256-GCM-SHA384
      - ECDHE-RSA-AES256-SHA
      - ECDHE-RSA-AES128-GCM-SHA256
      - ECDHE-RSA-AES128-SHA
      credentialName: app-connector-certs
      minProtocolVersion: TLSV1_2
      mode: MUTUAL
```

The secret `app-connector-certs` is missing, there is no such secret on the cluster - that's why the mTLS calls fail with the TLS error.

I wonder why it's gone. Will follow up in the Runtime Agent, but honestly I have no idea why it's not there.

**Comment by janmedrek** [comment]
Gateways in the OS version we've tested a few days ago use `credentialName: kyma-gateway-certs`.

This one exists in the SKR, same for the `kyma-gateway-certs-cacert` which gets updated by Compass Runtime Agent periodically.

There is a YAML file for this Gateway here: https://github.com/kyma-project/kyma/blob/main/resources/application-connector/templates/application-connector-gateway.yaml#L22. It uses the proper secret, which was changed over 5 months ago.

So the question to the @veichtj and @tobiscr is, how did we get there? I can see the same situation on different clusters in the Canary environment (such as `ed72781`). Does the reconciler use a **very** old version of this file and introduce regression to the clusters?

**Comment by janmedrek** [comment]
Anoher though, I've found in the Compass Runtime Agent the following log:
```
time="2022-01-28T13:58:50Z" level=info msg="Migrating secret. Source: istio-system/app-connector-certs , target=istio-system/kyma-gateway-certs-cacert."
```

This would suggest, that the secret existed in 1.24.9, later was removed in the 2.0.4 upgrade process, and the Gateway was not updated properly, could that be a case?

**Comment by veichtj** [comment]
@janmedrek - we could also reproduce, that for upgraded clusters the secret in `kyma-gateway-application-connector` is not as expected `kyma-gateway-certs` instead it stays `app-connector-certs`, for new kyma 2 installations it's fine.
Looks like reconcilation for the gateway and the related job is not working properly.

**Comment by pbochynski** [comment]
It means we should include Gateway CR in the upgrade process (reconciler)

**Comment by jeremyharisch** [comment]
The `periodic-main-kyma-incubator-reconciler-kyma1-kyma2-upgrade` pipeline is fixed since yesterday: https://status.build.kyma-project.io/?job=periodic-main-kyma-incubator-reconciler-kyma1-kyma2-upgrade
