### ISSUE TITLE
CI/CD mechanism required which ensures that reconciler list in KCP deployment is in sync with reconciler instances

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#727]
**Description**

The K8s deployment of the mothership reconciler is using a [static list](https://github.com/kyma-project/control-plane/blob/main/resources/kcp/values.yaml#L50-L61) for generating the configuration for reconcilers. This list can run out of sync when new [reconciler instances](https://github.com/kyma-incubator/reconciler/tree/main/pkg/reconciler/instances) are added (users usually don't know that they have to update the KCP deployment as well).

This should be addressed by establishing a CI/CD job which runs (either once a day or when a change in the `pkg/reconciler/instances` happens) and verifies that the list of configured reconcilers is in sync with the available reconcilers defined in [`pkg/reconciler/instances`](https://github.com/kyma-incubator/reconciler/tree/main/pkg/reconciler/instances).

AC:
* A mechanism is established which identifies missing reconcilers in the KCP mothership-reconciler deployment and alerts the development team.

**Reasons**

Ensure configured reconcilers defined in the  KCP deployment of the mothership-reconciler is in-sync with existing reconciler instances.

**Attachments**

**Comment by janmedrek** [comment]
Functionalities of the Reconciler were migrated to the new architecture, this issue will not be worked on.
