### ISSUE TITLE
Mothership reconciler should be able to reload it's config at runtime

### ISSUE THREAD

**Issue by Tomasz-Smelcerz-SAP** [kyma-incubator/reconciler#729]
**Description**

Mothership reconciler, once started, ignores the changes in it's config file. This means in order to actually change it's configuration it has to be restarted. Adding a filewatcher or a scheduler that reloads the config (e.g: once per hour) would make maintenance of the reconciler simpler.

AC:
* Configuration can be changed during runtime
* Mothership reconciler is automatically reloading the file and using the new provided configuration values accordingly.

**Reasons**

Long-running mothership processes in managed environments can automatically adjust to any changes in the config -> simplified maintenance effort.

**Comment by tobiscr** [comment]
Very good idea - added to backlog!

**Comment by janmedrek** [comment]
Functionalities of the Reconciler were migrated to the new architecture, this issue will not be worked on.
