### ISSUE TITLE
Helm capabilities support

### ISSUE THREAD

**Issue by a-thaler** [kyma-incubator/reconciler#731]
**Description**
The helm templating mechanism has Built-In objects called `Capabilities`, see https://helm.sh/docs/chart_template_guide/builtin_objects/

That are a few well-defined objects available for checking things on the target cluster where the chart will be applied to, like the kubernetes version or if a specific api group is available. Charts which are in best case are taken 1:1 from upstream like [grafana](https://github.com/kyma-project/kyma/tree/main/resources/monitoring/charts/grafana) or even the whole monitoring chart, are using capabilities extensive. Applying them by the reconciler will make the capabilities always resolve to the defaults which then result in some action dependent on the conditional check around that (depends on if you ask for < or > k8s version). As consequence these occurrences in the charts needs to be customized always causing a mismatch with the upstream chart, making maintenance really hard. (In best case we do not copy the charts at all but just reference a cloned upstream zip file)

The goal is to ad support for the Capabilities objects in the reconcilers helm templating mechanism. Here, you could rely on the helm libraries and/or even not do apiserver calls at all but provide the responses based on the local knowledge (k8s version, CRDs installed).

**Reasons**
Getting rid of capabilities inside the kyma components is not realistic as we probably will always support some upstream charts, at least as vendor specific addons. So we need support of it to avoid customizations. Furthermore, the capabilities can be helpful even for the self-written charts.
 

**Attachments**

**Comment by janmedrek** [comment]
Reconciler has moved to the new architecture, this issue will not be worked on.
