### ISSUE TITLE
Unit test suite fails when running on Postgres

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#753]
**Description**

Unittest have to be implemented in a way that they also run on Postgres. Currently are multiple tests failing when using PG as database for the test execution:

- [x] 1. Test-Inventory

          --- FAIL: TestInventory (6.45s)
              --- FAIL: TestInventory/Get_clusters_with_particular_status (1.29s)
                 inventory_test.go:138:
            	     Error Trace:	inventory_test.go:138

         --- FAIL: TestInventory/Get_clusters_to_reconcile (3.74s)
             inventory_test.go:240:
                 	Error Trace:	inventory_test.go:240

2. TestCountRetries

            --- FAIL: TestCountRetries (5.13s)
                testfactory.go:49:
                    	Error Trace:	testfactory.go:49
              	                  				inventory_test.go:339
              	      Error:      	Received unexpected error:
              	                  	pq: cannot truncate a table referenced in a foreign key constraint
                    	Test:       	TestCountRetries

- [x] 3. TestBookkeepingTask

            --- FAIL: TestBookkeepingtask (0.40s)
                --- FAIL: TestBookkeepingtask/Mark_operations_as_orphan (0.20s)
                    bookkeepingtask_test.go:56:
                        	Error Trace:	bookkeepingtask_test.go:56
                        	Error:      	Received unexpected error:
                        	            	cluster 'runtime1' is already considered for reconciliation (schedulingID:runtime1--1c3a42a7-7ff6-40c2-95e1-b7cc1e6a9270)
                        	Test:       	TestBookkeepingtask/Mark_operations_as_orphan
                --- FAIL: TestBookkeepingtask/Finish_operations (0.20s)
                    bookkeepingtask_test.go:56:
                              	Error Trace:	bookkeepingtask_test.go:56
                              	Error:      	Received unexpected error:
                  	            	cluster 'runtime1' is already considered for reconciliation (schedulingID:runtime1--1c3a42a7-7ff6-40c2-95e1-b7cc1e6a9270)
            	Test:       	TestBookkeepingtask/Finish_operations

4. TestBookkeepingTaskParallel

            --- FAIL: TestBookkeepingtaskParallel (3.18s)
                      --- FAIL: TestBookkeepingtaskParallel/Mark_two_operations_as_orphan_in_multiple_parallel_threads (2.67s)
                    bookkeepingtask_test.go:209:
                        	Error Trace:	bookkeepingtask_test.go:209
                        	Error:      	Not equal:
                        	            	expected: 72
                        	            	actual  : 75
                        	Test:       	TestBookkeepingtaskParallel/Mark_two_operations_as_orphan_in_multiple_parallel_threads
                --- FAIL: TestBookkeepingtaskParallel/Finish_two_operations_in_multiple_parallel_threads (0.51s)
                    bookkeepingtask_test.go:161:
                        	Error Trace:	bookkeepingtask_test.go:161
                        	Error:      	Received unexpected error:
                        	            	pq: could not serialize access due to concurrent update
                        	Test:       	TestBookkeepingtaskParallel/Finish_two_operations_in_multiple_parallel_threads

5. TestRuntimeBuilder

            -- FAIL: TestRuntimeBuilder (24.98s)
                --- FAIL: TestRuntimeBuilder/Run_remote_with_success (6.26s)
                    run_test.go:159:
                  	Error Trace:	run_test.go:159
                  	            				run_test.go:66
                  	Error:      	Not equal:
                  	            	expected: 1
                  	            	actual  : 5
                  	Test:       	TestRuntimeBuilder/Run_remote_with_success
          --- FAIL: TestRuntimeBuilder/Run_remote_with_error (6.31s)
              run_test.go:159:
                  	Error Trace:	run_test.go:159
                  	            				run_test.go:70
                  	Error:      	Not equal:
                  	            	expected: 1
                  	            	actual  : 5
                  	Test:       	TestRuntimeBuilder/Run_remote_with_error

6. TestWorkerPoolMaxOpRetriesReached

                  --- FAIL: TestWorkerPoolMaxOpRetriesReached (0.29s)
                workerpool_test.go:147:
              	      Error Trace:	workerpool_test.go:147
                    	Error:      	"[OperationEntity [SchedulingID=runtime1--1c3a42a7-7ff6-40c2-95e1-b7cc1e6a9270,CorrelationID=runtime1--a4607bcb-da0c-499a-90db-      4acdbb78c1e6,RuntimeID=runtime1,ClusterConfig=177,Component=CRDs,Prio=1,State=new,Type=reconcile] OperationEntity [SchedulingID=runtime2--14f3a3c3-f021-4c13-ab01-1a7179e8e4ca,CorrelationID=runtime2--d1f49599-0d84-42ff-b700-70fd5d46760e,RuntimeID=runtime2,ClusterConfig=178,Component=CRDs,Prio=1,State=new,Type=reconcile]]" should have 1 item(s), but has 2
                    	Test:       	TestWorkerPoolMaxOpRetriesReached

- [x] 7. TestWorkerPoolParallel

            --- FAIL: TestWorkerPoolParallel (15.35s)
                --- FAIL: TestWorkerPoolParallel/Multiple_WorkerPools_watching_same_reconciliation_repository (15.35s)
                    workerpool_test.go:274:
                        	Error Trace:	workerpool_test.go:274
                        	Error:      	"[]" should have 3 item(s), but has 0
                              	Test:       	TestWorkerPoolParallel/Multiple_WorkerPools_watching_same_reconciliation_repository

**Expected result**

Unit tests have to be implemented to be repeatable on Postgres database. Currently, it seems several data don't get removed and are causing failing test cases.

**Actual result**

Unit tests are executable on SQLite and Postgres

**Steps to reproduce**

**Troubleshooting**

**Comment by Tomasz-Smelcerz-SAP** [comment]
I take `TestWorkerPoolParallel/Multiple_WorkerPools_watching_same_reconciliation_repository`

**Comment by jeremyharisch** [comment]
I like your idea @ruanxin . Using a UUID could really solve our issue

**Comment by Tomasz-Smelcerz-SAP** [comment]
I take TestWorkerPoolMaxOpRetriesReached (number 6)

**Comment by tobiscr** [comment]
Please have a look on the fixed I figured out yesterday - PR is this one: https://github.com/kyma-incubator/reconciler/pull/760/files#diff-75525cc2733cc4a1902be39807e8f7333afd245166cda66e3be7edbea121fae8

**Comment by ruanxin** [comment]
To reviewer:

Please only review this PR  https://github.com/kyma-incubator/reconciler/pull/771
