### ISSUE TITLE
Job `periodic-main-kyma-incubator-reconciler-kyma1-kyma2-upgrade` should not install `istio-resources` when upgrading to Kyma 2.0.4

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#756]
**Description**

The REST call to the mothership reconciler is the job https://status.build.kyma-project.io/?job=periodic-main-kyma-incubator-reconciler-kyma1-kyma2-upgrade includes the `istio-resources` component.

AFter a sync with @veichtj it tuned out that this component is part of Kyma 2.1 and should not be used when installing Kyma 2.0.4

**Expected result**

`istio-resources` should not be installed when upgrading to Kyma 2.0.4

**Actual result**

`istio-resources` is installed when upgradig to Kyma 2.0.4

**Steps to reproduce**

**Troubleshooting**

**Comment by jeremyharisch** [comment]
Fixed with: https://github.com/kyma-project/test-infra/pull/4868
https://github.com/kyma-project/control-plane/pull/1323

**Comment by jeremyharisch** [comment]
Will wait for pipeline to succeed, then will close issue
