### ISSUE TITLE
LogQueries flag ignored within TX context

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#758]
**Description**

Queries executed within a DB transaction context are not logged when the `logQueries` flag is enabled. The TX object is interacting with the DB transaction object directly and not considering this flag.

This has to be fixed, so that also SQL statements which are executed within a TX context will be logged properly when `logQueries` is set to `true`.

**Expected result**

When enabling the `logQueries` flag, all SQL statements executed within the DB transaction have to be logged.

**Actual result**

SQL statements outside of a DB TX context are logged, but non within a DB context.

**Steps to reproduce**

**Troubleshooting**

**Comment by janmedrek** [comment]
Functionalities of the Reconciler were migrated to the new architecture, this issue will not be worked on.
