### ISSUE TITLE
Gardener CI/CD pipelines are failing because fast-integration tests cannot be found

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#766]
**Description**

Both gardener CI pipelines are failing with an error, that fast integration test directory cannot be found:

     2022/02/03 06:19:16 UTC [INFO] ### Run pre-upgrade tests
     2022/02/03 06:19:16 UTC [INFO] Running pre-upgrade Kyma Fast Integration tests
     /home/prow/go/src/github.com/kyma-project/test-infra/prow/scripts/lib/gardener/azure.sh: line 321: pushd:      /home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration: No such file or directory
     2022/02/03 06:19:16 UTC [ERROR] AN ERROR OCCURED! Take a look at preceding log entries.

Affected pipelines are:

* https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma-to-kyma2
* https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma2-to-main

**Expected result**

Fast integration tests should be executed.

**Actual result**

Fast integration tests are not executed.

**Steps to reproduce**

**Troubleshooting**

**Comment by pbochynski** [comment]
It is also reported here: https://github.com/kyma-project/test-infra/issues/4878

**Comment by Halamix2** [comment]
This is the problem with test-infra, should be fixed in https://github.com/kyma-project/test-infra/pull/4883

**Comment by jeremyharisch** [comment]
Second Fix provided with: https://github.com/kyma-project/test-infra/pull/4884

**Comment by jeremyharisch** [comment]
This issue is fixed
