### ISSUE TITLE
Reconciliations are never finishing on KCP DEV landscape

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#768]
**Description**

Clusters on KCP DEV are not reaching a finished reconciliation and the amount of in-progress clusters is continuously increasing.

See [https://grafana.cp.dev.kyma.cloud.sap/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Pro[…]:%22Q-37b9e463-84fa-4178-ad26-9e2b8b159193-0A%22%7D%5D](https://grafana.cp.dev.kyma.cloud.sap/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Prometheus%22,%7B%22expr%22:%22reconciler_reconciliation_not_ready_total%22,%22requestId%22:%22Q-37b9e463-84fa-4178-ad26-9e2b8b159193-0A%22%7D%5D)

**Expected result**

Reconciliation get finished within max. 10min.

**Actual result**

Number of non-finished clusters is continuously increasing.

**Steps to reproduce**

**Troubleshooting**

**Comment by PK85** [comment]
KEB awaits 2h for reconciler to create kyma:
```
	log:2022-02-03T06:11:52.290919227Z stderr F {"instanceID":"e3ce3ea0-5861-4d8e-ba43-aaef6a59481f","level":"error","msg":"Process operation failed: operation has reached the time limit: 2h0m0s","operation":"e7a3690b-e21e-4c2a-a8d0-d38d28996509","planID":"5cb3d976-b85c-42ea-a636-79cadda109a9","provisioning":"manager","stage":"check_kyma","step":"Check_Cluster_Configuration","time":"2022-02-03T06:11:52Z"} kubernetes.container_name:kyma-environment-broker @timestamp:Feb 3, 2022 @ 07:11:52.291 kubernetes.pod_name:kcp-kyma-environment-broker-54b99bddd7-4fpld kubernetes.namespace_name:kcp-system kubernetes.pod_id:5a5b7aa1-ef12-4e97-baa0-4928607110b0
```
Then KEB call delete on inventory cause test is calling deprovisioning and again timeout, 1,5h:
```
log:2022-02-03T07:43:01.883205754Z stderr F {"deprovisioning":"manager","instanceID":"e3ce3ea0-5861-4d8e-ba43-aaef6a59481f","level":"error","msg":"Cluster deregistration has reached the time limit: 1h30m0s","operation":"65a71949-c8fd-4bfc-baf9-040f5fd57eba","planID":"5cb3d976-b85c-42ea-a636-79cadda109a9","step":"Check_Cluster_Deregistration","time":"2022-02-03T07:43:01Z"} kubernetes.container_name:kyma-environment-broker @timestamp:Feb 3, 2022 @ 08:43:01.883 kubernetes.pod_name:kcp-kyma-environment-broker-54b99bddd7-4fpld kubernetes.namespace_name:kcp-system kubernetes.pod_id:5a5b7aa1-ef12-4e97-baa0-4928607110b0
```

Then KEB deletes cluster by calling provisioner and after 10min, cluster is deleted cause it was empty.

**Comment by tobiscr** [comment]
We are currently having >31k clusters in the reconciliation queue which is far too many as expected (so a load test is currently accidentally also happening :) ).

     kcp rc -o json | jq '.[].runtimeID' | uniq -u | wc -l
       31468

This number is also rapidly growing. Wondering where this high load is coming from.

**Comment by tobiscr** [comment]
Ok, turned out the `kcp` CLI has a bug and marks all reconciliations to be active but in the DB they are tracked properly ([issue raised](https://github.com/kyma-incubator/reconciler/issues/769) for this finding).

Seems that 9/10 ongoing operations are stucking in deleting KYma.
<img width="812" alt="Screen Shot 2022-02-03 at 13 52 48" src="https://user-images.githubusercontent.com/73824711/152346483-980139b4-a1c4-43af-b90f-d489fb853192.png">

**Comment by tobiscr** [comment]
Turned out that these reconciliations of these clusters never go finished because the cluster was already killed by KEB. Several components are failing because the target host no longer exists (at least DNS resolution is no longer possible which I take as indicator that the host got dropped by Gardener already):

I checked two reconciliations which are in status `deleting` - they have several components which are reporting that the host is not reachable anymore:

       $> kcp rc info -i 2a79b6ac-62d5-45b1-810e-a291753ddcae--1c93b389-834e-48de-8c5c-7b827d6f9508
       serverless    2a79b6ac-62d5-45b1-810e-a291753ddcae--56e1078a-3504-471e-ae04-1aa6e0fe519b   2a79b6ac-62d5-45b1-810e-a291753ddcae--1c93b389-834e-48de-8c5c-7b827d6f9508   4          error   2022/02/03 11:34:43   2022/02/03 12:48:10   All attempts fail:
       #1: Get "https://api.c-5b48640.dev.kyma.ondemand.com/api?timeout=32s": dial tcp: lookup api.c-5b48640.dev.kyma.ondemand.com on 10.4.0.10:53: no such host
       #2: Get "https://api.c-5b48640.dev.kyma.ondemand.com/api?timeout=32s": dial tcp: lookup api.c-5b48640.dev.kyma.ondemand.com on 10.4.0.10:53: no such host
       #3: Get "https://api.c-5b48640.dev.kyma.ondemand.com/api?timeout=32s": dial tcp: lookup api.c-5b48640.dev.kyma.ondemand.com on 10.4.0.10:53: no such host
       #4: Get "https://api.c-5b48640.dev.kyma.ondemand.com/api?timeout=32s": dial tcp: lookup api.c-5b48640.dev.kyma.ondemand.com on 10.4.0.10:53: no such host
       #5: Get "https://api.c-5b48640.dev.kyma.ondemand.com/api?timeout=32s": dial tcp: lookup api.c-5b48640.dev.kyma.ondemand.com on 10.4.0.10:53: no such host
       ...
       eventing    2a79b6ac-62d5-45b1-810e-a291753ddcae--3d6ba828-9b7a-4155-95bc-ae7a3d5c2a3e   2a79b6ac-62d5-45b1-810e-a291753ddcae--1c93b389-834e-48de-8c5c-7b827d6f9508   4          error    2022/02/03 11:34:43   2022/02/03 12:47:58   All attempts fail:
       #1: Get "https://api.c-5b48640.dev.kyma.ondemand.com/api?timeout=32s": dial tcp: lookup api.c-5b48640.dev.kyma.ondemand.com on 10.4.0.10:53: no such host
       #2: Get "https://api.c-5b48640.dev.kyma.ondemand.com/api?timeout=32s": dial tcp: lookup api.c-5b48640.dev.kyma.ondemand.com on 10.4.0.10:53: no such host
       #3: Get "https://api.c-5b48640.dev.kyma.ondemand.com/api?timeout=32s": dial tcp: lookup api.c-5b48640.dev.kyma.ondemand.com on 10.4.0.10:53: no such host

One more example:

       $> kcp rc info -i 53dd3ab3-4b35-494b-b17e-4c1983ae7980--0db0786d-661f-4df6-a491-ef35c8a9c8e7

        busola-migrator       53dd3ab3-4b35-494b-b17e-4c1983ae7980--a2a4b96c-79f2-4a25-a21c-71b4a08de06d   53dd3ab3-4b35-494b-b17e-4c1983ae7980--0db0786d-661f-4df6-a491-ef35c8a9c8e7   4          error    2022/02/03         11:13:43   2022/02/03 12:26:58   All attempts fail:
        #1: Get "https://api.c-29e3928.dev.kyma.ondemand.com/api?timeout=32s": dial tcp: lookup api.c-29e3928.dev.kyma.ondemand.com on 10.4.0.10:53: no such host
        #2: Get "https://api.c-29e3928.dev.kyma.ondemand.com/api?timeout=32s": dial tcp: lookup api.c-29e3928.dev.kyma.ondemand.com on 10.4.0.10:53: no such host
        #3: Get "https://api.c-29e3928.dev.kyma.ondemand.com/api?timeout=32s": dial tcp: lookup api.c-29e3928.dev.kyma.ondemand.com on 10.4.0.10:53: no such host
        .....
        connectivity-proxy      53dd3ab3-4b35-494b-b17e-4c1983ae7980--6cb43641-c0c5-4a0b-9ec9-c7a67a33fa3c   53dd3ab3-4b35-494b-b17e-4c1983ae7980--0db0786d-661f-4df6-a491-ef35c8a9c8e7   4          error    2022/02/03         11:13:43   2022/02/03 12:27:01   All attempts fail:
        #1: Error during removal: Get "https://api.c-29e3928.dev.kyma.ondemand.com/api?timeout=32s": dial tcp: lookup api.c-29e3928.dev.kyma.ondemand.com on 10.4.0.10:53: no such host
        #2: Error during removal: Get "https://api.c-29e3928.dev.kyma.ondemand.com/api?timeout=32s": dial tcp: lookup api.c-29e3928.dev.kyma.ondemand.com on 10.4.0.10:53: no such host
        #3: Error during removal: Get "https://api.c-29e3928.dev.kyma.ondemand.com/api?timeout=32s": dial tcp: lookup api.c-29e3928.dev.kyma.ondemand.com on 10.4.0.10:53: no such host

**Comment by tobiscr** [comment]
The reconciler is currently not expecting that a host is gone before the deletion is finished. A deletion which could not be successfully finished will retried in the next reconciliation cycle. This leads to increasing reconciliation queue size on reconciler side.

**Comment by tobiscr** [comment]
But I see the KEB seems to tried a few times to get a cluster deleted on reconciler side... so, retries seems to happen by KEB. Maybe a timeout issue that the reconcile deletion didn'T happen fast enough?

Here an example of a cluster which was called a few times to get deleted (indicated by the `` cluster state):

       $> kcp rc -r 53dd3ab3-4b35-494b-b17e-4c1983ae7980
       53dd3ab3-4b35-494b-b17e-4c1983ae7980--fb61b1ab-5878-4b2a-b574-9f8ebfe31221   53dd3ab3-4b35-494b-b17e-4c1983ae7980   2022/01/21 00:56:23   2022/01/21 01:00:22   ready
       53dd3ab3-4b35-494b-b17e-4c1983ae7980--9248da35-2785-4879-820e-1bff12b49492   53dd3ab3-4b35-494b-b17e-4c1983ae7980   2022/01/21 01:05:23   2022/01/21 01:17:37   delete_pending
       53dd3ab3-4b35-494b-b17e-4c1983ae7980--31e519e4-e6f3-4b61-afe1-59bcfcf753dc   53dd3ab3-4b35-494b-b17e-4c1983ae7980   2022/01/21 01:18:23   2022/01/21 01:30:22   delete_error_retryable
       ...
       53dd3ab3-4b35-494b-b17e-4c1983ae7980--9889f764-1827-4e3e-968a-8c644cec5902   53dd3ab3-4b35-494b-b17e-4c1983ae7980   2022/01/22 00:31:49   2022/01/22 00:49:02   delete_error_retryable
       53dd3ab3-4b35-494b-b17e-4c1983ae7980--04de514a-2f16-4cdb-890f-9bc225530a27   53dd3ab3-4b35-494b-b17e-4c1983ae7980   2022/01/22 00:54:49   2022/01/22 01:13:47   delete_pending
       53dd3ab3-4b35-494b-b17e-4c1983ae7980--7977844d-4fc6-47a2-acce-d6a23e8af022   53dd3ab3-4b35-494b-b17e-4c1983ae7980   2022/01/22 01:13:49   2022/01/22 01:27:17   delete_error_retryable
       ...
       53dd3ab3-4b35-494b-b17e-4c1983ae7980--169eed39-f62d-4c6a-b152-71f27ee7367f   53dd3ab3-4b35-494b-b17e-4c1983ae7980   2022/01/22 02:57:49   2022/01/22 03:10:02   delete_error_retryable
       53dd3ab3-4b35-494b-b17e-4c1983ae7980--3bbd1570-486e-4522-b119-9df016ba7bc4   53dd3ab3-4b35-494b-b17e-4c1983ae7980   2022/01/22 03:15:49   2022/02/02 16:57:04   delete_pending
       53dd3ab3-4b35-494b-b17e-4c1983ae7980--3836882b-20f6-4b6e-adc1-ebcb0e5105b8   53dd3ab3-4b35-494b-b17e-4c1983ae7980   2022/02/02 16:57:17   2022/02/02 17:12:44   delete_error_retryable
       ...

**Comment by PK85** [comment]
Btw KEB awaits 1,5h for reconciler to delete kyma, if not then we delete cluster by calling provisioner. In that case reconciler should figure out that host is gone and stop processing that runtime as it was already deleted.

**Comment by tobiscr** [comment]
Kk, thanks for the update. Figuring out whether a host is gone or not cannot be done by the reconciler as we are not the data leader (KEB is the master of cluster data) and the reconciler has to deal with situations when clusters are temporarily not available (incidents etc.). 

We anyway have to deal with situations that KEB could not reach the reconciler (e.g. in case the reconciler is down for several hours) and that we run out of sync between the cluster-data in KEB database and in the reconciler inventory.

We would prefer to implement a synchronisation between KEB cluster-data and the reconciler cluster inventory. We expect that all data in the reconciler's cluster inventory is just a copy of the data from KEB and that any cluster-changes we are getting are recorded on KEB and we are just getting a copy of them.

Can we maybe prioritise the cluster-data sync between KEB and the reconciler? On our side, [we have it in the backlog](https://github.com/kyma-incubator/reconciler/issues/127) and would give it a higher priority if it's feasible for KEB as well.

**Comment by tobiscr** [comment]
Solving the current issue we can come up with a bash script as workaround. The script disables these clusters which are already deleted:

1. use `kcp` CLI to retreive all runtimes
2. iterate over the reconciliations of each runtime - if a `delete_pending` state exists and there are several `delete_error_retryable` before, check the operations in state `error` of the latest failed reconciliation.
3. If the field `error` includes `no such host` disable the cluster via `kcp` CLI

**Comment by tobiscr** [comment]
Script for disabling clusters with more than 10 failing delete-reconciliations:

[fixkcpdev.sh.zip](https://github.com/kyma-incubator/reconciler/files/7997200/fixkcpdev.sh.zip)

**Comment by PK85** [comment]
@tobiscr about "We anyway have to deal with situations that KEB could not reach the reconciler (e.g. in case the reconciler is down for several hours) and that we run out of sync between the cluster-data in KEB database and in the reconciler inventory." 

IF KEB cannot reach reconciiler 500 or 404 we fail deprovisioning on KEB side, and we are still in sync.

**Comment by tobiscr** [comment]
Ok, that's even better. I would anyway recommend to sync the DBs regularly to ensure the reconciler is in any case using the same set of cluster data as KEB is using.

**Comment by tobiscr** [comment]
@pbochynski : I fear we have urgently to focus on getting this scaling challenge properly handled. Right now, it seems we are exceeding the capacities and we don'T know exactly where our load-thresholds are.

Last Wednesday we had to rollback the scalling-feature as we were facing unexpected high DB transaction collisions when it was tracking the workerpool allocation. So, right now the reconciler is not capable to scale automatically and we should now heavily focus on coming up with a quick load-test to get this uncertainty solved.
