### ISSUE TITLE
Deletion of component `monitoring` failed during e2e test execution

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#782]
**Description**

Deletion of an SKR cluster failed when executing the E2E pipeline in Spinnaker:

        SCHEDULING ID                                                                RUNTIME ID                             CREATED AT            UPDATED               STATUES                  LOCK
        74a9d826-7ddf-4812-954e-ee1b43ec70cb--cfd7338a-6446-4e75-83c8-d241531bee91   74a9d826-7ddf-4812-954e-ee1b43ec70cb   2022/02/04 14:41:06   2022/02/04 14:47:04   ready
        74a9d826-7ddf-4812-954e-ee1b43ec70cb--5689af4c-979d-4be9-ac1c-1b0eb0db1561   74a9d826-7ddf-4812-954e-ee1b43ec70cb   2022/02/04 14:52:07   2022/02/04 15:04:19   delete_pending
        74a9d826-7ddf-4812-954e-ee1b43ec70cb--01902f10-e1ea-44f2-a252-349e0d51fa07   74a9d826-7ddf-4812-954e-ee1b43ec70cb   2022/02/04 15:05:06   2022/02/04 15:17:04   delete_error_retryable
        74a9d826-7ddf-4812-954e-ee1b43ec70cb--0967a307-ebe3-4b1b-94df-c94c5598014f   74a9d826-7ddf-4812-954e-ee1b43ec70cb   2022/02/04 15:22:07   2022/02/04 15:32:49   delete_error_retryable
        74a9d826-7ddf-4812-954e-ee1b43ec70cb--ce43fb0b-3dd4-44ec-a784-65f95863ef82   74a9d826-7ddf-4812-954e-ee1b43ec70cb   2022/02/04 15:38:07   2022/02/04 15:49:19   delete_error_retryable
        74a9d826-7ddf-4812-954e-ee1b43ec70cb--d5dff649-0ae2-4db6-a294-7752c7470e4b   74a9d826-7ddf-4812-954e-ee1b43ec70cb   2022/02/04 15:55:07   2022/02/04 16:05:49   delete_error_retryable

Investigation from @ebensom showed that the CRD component is timing out.

**Expected result**

Deletion should remove installed components, deletion of CRD should not fail.

**Actual result**

CRD deletion failed with timeout.

**Steps to reproduce**

**Troubleshooting**

**Comment by tobiscr** [comment]
Investigation showed following result:

      $> kcp rc -r 74a9d826-7ddf-4812-954e-ee1b43ec70cb | head -5
      SCHEDULING ID                                                                RUNTIME ID                             CREATED AT            UPDATED               STATUES                  LOCK
      74a9d826-7ddf-4812-954e-ee1b43ec70cb--cfd7338a-6446-4e75-83c8-d241531bee91   74a9d826-7ddf-4812-954e-ee1b43ec70cb   2022/02/04 14:41:06   2022/02/04 14:47:04   ready
      74a9d826-7ddf-4812-954e-ee1b43ec70cb--5689af4c-979d-4be9-ac1c-1b0eb0db1561   74a9d826-7ddf-4812-954e-ee1b43ec70cb   2022/02/04 14:52:07   2022/02/04 15:04:19   delete_pending
      74a9d826-7ddf-4812-954e-ee1b43ec70cb--01902f10-e1ea-44f2-a252-349e0d51fa07   74a9d826-7ddf-4812-954e-ee1b43ec70cb   2022/02/04 15:05:06   2022/02/04 15:17:04   delete_error_retryable
      74a9d826-7ddf-4812-954e-ee1b43ec70cb--0967a307-ebe3-4b1b-94df-c94c5598014f   74a9d826-7ddf-4812-954e-ee1b43ec70cb   2022/02/04 15:22:07   2022/02/04 15:32:49   delete_error_retryable
      ...

During the deletion, the component `monitoring` could not be installed within the given time range:

      $>  kcp rc info -i 74a9d826-7ddf-4812-954e-ee1b43ec70cb--01902f10-e1ea-44f2-a252-349e0d51fa07
      COMPONENT                CORRELATION_ID                                                               SCHEDULING_ID                                                                PRIORITY   STATE   CREATED AT            UPDATED               REASON
      serverless               74a9d826-7ddf-4812-954e-ee1b43ec70cb--5b2b3b2d-c149-4332-ac70-4dbd4f48769f   74a9d826-7ddf-4812-954e-ee1b43ec70cb--01902f10-e1ea-44f2-a252-349e0d51fa07   4          done    2022/02/04 15:05:06   2022/02/04 15:07:11
      api-gateway              74a9d826-7ddf-4812-954e-ee1b43ec70cb--dcc133db-443d-4ff0-8dca-26b59c68f74d   74a9d826-7ddf-4812-954e-ee1b43ec70cb--01902f10-e1ea-44f2-a252-349e0d51fa07   4          done    2022/02/04 15:05:06   2022/02/04 15:06:07
      service-manager-proxy    74a9d826-7ddf-4812-954e-ee1b43ec70cb--ffd623d4-0127-4f41-a3f9-b4a8e509a4d7   74a9d826-7ddf-4812-954e-ee1b43ec70cb--01902f10-e1ea-44f2-a252-349e0d51fa07   4          done    2022/02/04 15:05:06   2022/02/04 15:05:35
      service-catalog          74a9d826-7ddf-4812-954e-ee1b43ec70cb--4ddd7fba-8a41-42fc-b7ec-ec45830a13a9   74a9d826-7ddf-4812-954e-ee1b43ec70cb--01902f10-e1ea-44f2-a252-349e0d51fa07   4          done    2022/02/04 15:05:06   2022/02/04 15:06:18
      monitoring               74a9d826-7ddf-4812-954e-ee1b43ec70cb--c0c76f25-241d-47f8-b647-e1cdfe483252   74a9d826-7ddf-4812-954e-ee1b43ec70cb--01902f10-e1ea-44f2-a252-349e0d51fa07   4          error   2022/02/04 15:05:06   2022/02/04 15:16:34   context deadline exceeded
      ...

Also in later retries, if failed always to delete the monitoring component:

      $> kcp rc info -i 74a9d826-7ddf-4812-954e-ee1b43ec70cb--0967a307-ebe3-4b1b-94df-c94c5598014f
      ...
      monitoring               74a9d826-7ddf-4812-954e-ee1b43ec70cb--f3afa05c-7104-47e1-b3bb-23e1245ebd77   74a9d826-7ddf-4812-954e-ee1b43ec70cb--0967a307-ebe3-4b1b-94df-c94c5598014f   4          error   2022/02/04 15:22:07   2022/02/04 15:32:34   context deadline exceeded

**Comment by tobiscr** [comment]
the logs showed that several deployment could not be terminated within the given time range:

      "Tracker stopped checking the progress of the following resource: Deployment [namespace:kyma-system|name:monitoring-grafana]"
      "Tracker stopped checking the progress of the following resource: Deployment [namespace:kyma-system|name:monitoring-auth-proxy-grafana]"
      "Tracker stopped checking the progress of the following resource: Deployment [namespace:kyma-system|name:monitoring-kube-state-metrics]"
      "Tracker stopped checking the progress of the following resource: Deployment [namespace:kyma-system|name:monitoring-prometheus-istio-server]"
      "Tracker stopped checking the progress of the following resource: Deployment [namespace:kyma-system|name:monitoring-operator]"
      Tracker stopped checking the progress of the following resource: DaemonSet [namespace:kyma-system|name:monitoring-prometheus-node-exporter]"

**Comment by rakesh-garimella** [comment]
A bit more context is. needed here is it happening for kyma version 2.0.4 or on main ?

**Comment by rakesh-garimella** [comment]
I tried to reproduce the error on a gardener cluster but was not able to do so. While calling undeploy there was an [issue](https://github.com/kyma-project/cli/issues/1180) found that kyma cli checks out the main branch rather than the version of kyma cluster that is installed which could be a possible reason for error(but again its not reproducible so cant be 100% sure if this is the reason).

**Comment by rakesh-garimella** [comment]
Thanks to @ebensom  the issue was reproduced some more info from investigation

1. There were no monitoring components present on the cluster
2. The CRDs for monitoring components were deleted already although the lower priority job was not deleted. See below here the monotroing correlation_id is still in `in_progress` and CRDs is still in progress we saw on the cluster the CRDs from (atleast) monitoring were deleted.
 ```
 CRDs                     2f7b6dbe-8328-45ec-936c-58e5d1df9f71--1fd26037-3a3f-4a49-8475-36b3a2424e84   2f7b6dbe-8328-45ec-936c-58e5d1df9f71--d44fd207-81df-406f-a4c9-8d953cfa770a   1          new           2022/02/10 08:33:33   2022/02/10 08:33:33
 connectivity-proxy       2f7b6dbe-8328-45ec-936c-58e5d1df9f71--a2c65315-eda5-4bcd-a482-69a11bc2860d   2f7b6dbe-8328-45ec-936c-58e5d1df9f71--d44fd207-81df-406f-a4c9-8d953cfa770a   4          done          2022/02/10 08:33:33   2022/02/10 08:34:04
rma                      2f7b6dbe-8328-45ec-936c-58e5d1df9f71--c39aac33-b211-44a4-992d-69135a019999   2f7b6dbe-8328-45ec-936c-58e5d1df9f71--d44fd207-81df-406f-a4c9-8d953cfa770a   4          done          2022/02/10 08:33:33   2022/02/10 08:34:04
monitoring               2f7b6dbe-8328-45ec-936c-58e5d1df9f71--4b2aa5b9-8f75-4ff0-91b2-586010cb587e   2f7b6dbe-8328-45ec-936c-58e5d1df9f71--d44fd207-81df-406f-a4c9-8d953cfa770a   4          in_progress   2022/02/10 08:33:33   2022/02/10 08:42:31
application-connector    2f7b6dbe-8328-45ec-936c-58e5d1df9f71--13cce461-f775-4294-b1f2-8ed26df3f1b0   2f7b6dbe-8328-45ec-936c-58e5d1df9f71--d44fd207-81df-406f-a4c9-8d953cfa770a   4          done          2022/02/10 08:33:33   2022/02/10 08:34:06
``` 

Further investigation points here
```
SCHEDULING ID                                                                RUNTIME ID                             CREATED AT            UPDATED               STATUES                  LOCK
2f7b6dbe-8328-45ec-936c-58e5d1df9f71--d44fd207-81df-406f-a4c9-8d953cfa770a   2f7b6dbe-8328-45ec-936c-58e5d1df9f71   2022/02/10 08:33:33   0001/01/01 00:00:00   deleting
2f7b6dbe-8328-45ec-936c-58e5d1df9f71--8461ab3f-e1a0-4731-91bd-4aa567da3a21   2f7b6dbe-8328-45ec-936c-58e5d1df9f71   2022/02/10 08:17:34   2022/02/10 08:28:15   delete_error_retryable
2f7b6dbe-8328-45ec-936c-58e5d1df9f71--c8f4f235-1ac4-4eea-b278-682d565b3482   2f7b6dbe-8328-45ec-936c-58e5d1df9f71   2022/02/10 08:00:32   2022/02/10 08:11:45   delete_error_retryable
2f7b6dbe-8328-45ec-936c-58e5d1df9f71--cd16472b-b17d-4c4b-a9d9-7676b81138a4   2f7b6dbe-8328-45ec-936c-58e5d1df9f71   2022/02/10 07:48:32   2022/02/10 07:59:45   delete_pending
2f7b6dbe-8328-45ec-936c-58e5d1df9f71--fd6b9d70-137e-4502-a431-1e657cd549bf   2f7b6dbe-8328-45ec-936c-58e5d1df9f71   2022/02/10 07:36:33   2022/02/10 07:43:15   ready
```

The second from bottom is still in `delete_pending` state (which is not an end state) but there is a new attempt to delete all the resources which looks like some failure in logic

Checking the `delete_pending` scheduling_id we see following the lower priority components are not deleted before the higher priority components which is again some issue with logic.
```
COMPONENT                CORRELATION_ID                                                               SCHEDULING_ID                                                                PRIORITY   STATE   CREATED AT            UPDATED               REASON
CRDs                     2f7b6dbe-8328-45ec-936c-58e5d1df9f71--b7137357-1910-4fc3-9335-116db4e53d4f   2f7b6dbe-8328-45ec-936c-58e5d1df9f71--cd16472b-b17d-4c4b-a9d9-7676b81138a4   1          error   2022/02/10 07:48:32   2022/02/10 07:59:00   context deadline exceeded
cleaner                  2f7b6dbe-8328-45ec-936c-58e5d1df9f71--5208cee0-5117-48a3-baa2-01549475c3f2   2f7b6dbe-8328-45ec-936c-58e5d1df9f71--cd16472b-b17d-4c4b-a9d9-7676b81138a4   2          new     2022/02/10 07:48:32   2022/02/10 07:48:32
cluster-essentials       2f7b6dbe-8328-45ec-936c-58e5d1df9f71--29147e8b-bfb1-4d05-9ae3-8c46474dc3ae   2f7b6dbe-8328-45ec-936c-58e5d1df9f71--cd16472b-b17d-4c4b-a9d9-7676b81138a4   3          new     2022/02/10 07:48:32   2022/02/10 07:48:32
istio-configuration      2f7b6dbe-8328-45ec-936c-58e5d1df9f71--cfca825a-9433-43f2-81ad-5e5e690f3835   2f7b6dbe-8328-45ec-936c-58e5d1df9f71--cd16472b-b17d-4c4b-a9d9-7676b81138a4   3          new     2022/02/10 07:48:32   2022/02/10 07:48:32
```

**Comment by rakesh-garimella** [comment]
It would be nice if the base reconciler on deletion can provide more info on failures rather than only `context deadline` error. May be logging can be improved here.

**Comment by tobiscr** [comment]
Issue is identifed:

Operations were created to be used for `reconciling` a cluster but the mothership decided to handled them as `delete`-operations which finally leads to the wrong order of the execution sequence.

Bug identified by @clebs  here: https://github.com/kyma-incubator/reconciler/blob/119215d497c4cbe926bee540871eed2b14b133eb/pkg/scheduler/invoker/invoker.go#L55

**Comment by tobiscr** [comment]
Fix coming in https://github.com/kyma-incubator/reconciler/pull/817
