### ISSUE TITLE
[Istio] implement test for Istio reconciler

### ISSUE THREAD

**Issue by strekm** [kyma-incubator/reconciler#798]
**Description**

Implement integration test testing Istio installation. Test should assume that connection to a cluster is provided and Istio is installed along with cluster-essentials Test should check if istio is installed and running

Expected result:

- Istio pods should be running ( istiod, ingressgateway)
- healthz returns 200

**Attachments**

https://github.com/kyma-incubator/reconciler/issues/785

**Comment by strekm** [comment]
@piotrkpc i do not see a reason to test anything in `kyma-system`, please correct me if i'm wrong. if this testing is not needed please remove it to keep this test clean

**Comment by piotrkpc** [comment]
> @piotrkpc i do not see a reason to test anything in `kyma-system`, please correct me if i'm wrong. if this testing is not needed please remove it to keep this test clean

Solved with https://github.com/kyma-incubator/reconciler/pull/841
