### ISSUE TITLE
Add e2e tests job for PR in control plane and cli while bump reconciler

### ISSUE THREAD

**Issue by ruanxin** [kyma-incubator/reconciler#799]
## Description
To have better confidence for catch bugs before reconciler used in production artifacts. We can introduce e2e test in the PR before the [reconciler image](https://github.com/kyma-project/control-plane/blob/main/resources/kcp/values.yaml#L5) and dependencies get bumped in the control plane and cli.

The testing scenario should cover the following kyma provision and do fast-integration test in the end.
1. install kyma previous release version (Kyma 2.0.x-1), do fast-integration
1. install Kyma latest release version (Kyma 2.0.x),  do fast-integration
1. install kyma from main branch, do fast-integration
1. kyma upgrades from latest 1.24.x to latest released 2.0.x, do fast-integration
1. kyma upgrades from latest released 2.0.x to main, do fast-integration
1. kyma upgrades from one version previous from latest released (2.0.x-1) to latest released 2.0.x , do fast-integration
~5. kyma upgrades from 1.24.x to 2.0.x to main, do fast-integration~

## Acceptance
- Trigger those job for PRs in control-plane repo when bumping reconciler image in control-plane repo 
- Trigger those job for PRs in cli repo when bumping reconciler dependency in CLI repo
- The jobs should be defined as required for PR
- The test cluster should use K3d, but not Gardener

Hints:
We already have many periodic jobs doing similar tests, which can help with implementing above mentioned new jobs.

In control-plane [PR](https://github.com/kyma-project/control-plane/pull/1332), we already have one e2e job defined:
pre-main-control-plane-reconciler-e2e

In cli [PR](https://github.com/kyma-project/cli/pull/1179), currently, it only test install kyma1, kyma2 with k3d. We should introduce similar test like below:
[kyma-upgrade-k3d-kyma2-to-main](https://status.build.kyma-project.io/?job=kyma-upgrade-k3d-kyma2-to-main)

Tasks:
- [x] #803
- [x] #804
- [x] #802
- [x] #807
- [ ] setup pre submit jobs using kyma-cli:PR

**Comment by pbochynski** [comment]
IMHO the pipeline should be triggered as a pre-submit job on PR. The failing test should prevent the code to be merged to the main branch. See my comment in the other issue: https://github.com/kyma-incubator/reconciler/issues/784#issuecomment-1034730975
And such PR should be tested on k3d, not on gardener (cheaper and faster). k3d tests should catch 99% of bugs. The remaining 1% can be tested by periodic jobs on dev.

**Comment by k15r** [comment]
In the end we need:

**Comment by ruanxin** [comment]
Hi @k15r, just want to mention that the e2e jobs are not only triggered in cli PR, but also need to be in control-plane PR when bump new reconciler image.

**Comment by jeremyharisch** [comment]
@k15r as Xin already mentioned, the important part is not to trigger all the test when a PR in reconciler repo is created, they should be triggered when we upgrade the image in the control plane.

Here: https://github.com/kyma-project/control-plane/blob/main/resources/kcp/values.yaml#L5

The ACs and the description of https://github.com/kyma-incubator/reconciler/issues/802 are already covered by the [nightly-main-reconciler-publish-unstable-cli](https://status.build.kyma-project.io/?job=nightly-main-reconciler-publish-unstable-cli) pipeline. The only difference is that this is a post-submit job. So, the easiest solution is to just put it in the pre-submit section, only for this case of course. The rest should be covered in the control plane repo

We have an overview of our piline in the Wiki at: `Kyma TEams/ By Name/Jellyfish/Monitoring Duty Schedule/ Pipeline Check`

Please also adapt the Wiki page regarding the new pipelines

**Comment by janmedrek** [comment]
Functionalities of the Reconciler were migrated to the new architecture, this issue will not be worked on.
