### ISSUE TITLE
KCP CLI: Operation type missing in JSON output of `kcp rc info` command

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#801]
**Description**

The KCP CLI should also include the type of an operation in the JSON view of a reconciliation. Currently operations don't include a `type` field:

      kcp rc info --scheduling-id 2f7b6dbe-8328-45ec-936c-58e5d1df9f71--cd16472b-b17d-4c4b-a9d9-7676b81138a4 -o json
      {
        "configVersion": 30136,
        "created": "2022-02-10T07:48:32.866951Z",
        "finished": true,
        "operations": [
          {
            "component": "CRDs",
            "correlationID": "2f7b6dbe-8328-45ec-936c-58e5d1df9f71--b7137357-1910-4fc3-9335-116db4e53d4f",
            "created": "2022-02-10T07:48:32.866951Z",
            "priority": 1,
            "reason": "context deadline exceeded",
            "schedulingID": "2f7b6dbe-8328-45ec-936c-58e5d1df9f71--cd16472b-b17d-4c4b-a9d9-7676b81138a4",
            "state": "error",
            "updated": "2022-02-10T07:59:00.798949Z"
          },
      ...
      }

The operation-type defines whether it is a `delete` or `reconcile` operation.

**Expected result**

Operation type is shown in KCP CLI output.

**Actual result**

Operation type is not part of the JSON output when requesting the details of a reconciliation.

**Steps to reproduce**

**Troubleshooting**

**Comment by kwiatekus** [comment]
I'm testing on dev landscape and see empty `type` in json response

**Comment by kwiatekus** [comment]
Thanks @moelsayed. It works
