### ISSUE TITLE
setup a new prow pipeline to build a kyma cli based on cli:main and reconciler:PR

### ISSUE THREAD

**Issue by k15r** [kyma-incubator/reconciler#802]
## Description

e2e tests executed as a pre submit to the reconciler repository we need to setup a new prow pipeline to build a special version of the kyma cli.

## Acceptance
- checkout kyma-project/cli:main
- update the dependencies to kyma-incubator/reconciler to point to the PR
- build the new kyma cli
- push the kyma cli (named kyma-PRXXX) to a central location
- this job runs as a presubmit for every PR to the reconciler repository
- it is a required job. Failures will fail the PR
- job documentation is updated

## Hint
we already have a nightly job to build an unstable cli. This could be used as a starting point

**Comment by jeremyharisch** [comment]
https://github.com/kyma-incubator/reconciler/issues/799#issuecomment-1035066597

**Comment by mfaizanse** [comment]
PR: https://github.com/kyma-project/test-infra/pull/5063

**Comment by mfaizanse** [comment]
Documentation is also updated to list the added prow job.
