### ISSUE TITLE
setup pre submit jobs for reconciler changes in control-plane

### ISSUE THREAD

**Issue by k15r** [kyma-incubator/reconciler#803]
## Description

with every merge to reconciler:main a new PR to the control-plane repo is created (eg https://github.com/kyma-project/control-plane/pull/1333/files). To ensure this change is valid pre submit jobs must execute various e2e test for reconciler scenarios

## Acceptance
- pre submit for control-plane changes to `resources/kcp/values.yaml`
- execute scenarios:
  - install kyma main + fast integration 
  - install kyma latest release + fast integration
  - install kyma previous release + fast integration (descoped for now, as at the time of writing 1.24 ist the previous release)
- all scenarios will be executed on a k3d cluster
- new jobs are documented
- all presubmit jobs introduced by this issue must be required

**Comment by mfaizanse** [comment]
PR: https://github.com/kyma-project/test-infra/pull/4964

**Comment by k15r** [comment]
To simplify initial setup for this job the scenarios will be executed against a gardener cluster. In a follow up ticket this needs to be switched to use k3d

**Comment by mfaizanse** [comment]
PR: https://github.com/kyma-project/test-infra/pull/4997

**Comment by jeremyharisch** [comment]
Documentation is missing, please document it in our wiki @mfaizanse

**Comment by jeremyharisch** [comment]
Done
