### ISSUE TITLE
setup pre submit jobs for reconciler changes

### ISSUE THREAD

**Issue by k15r** [kyma-incubator/reconciler#807]
## Description
With every pull request to reconciler repo we need to build a new cli version and test if it can install various versions of kyma

## Acceptance
- wait for cli to be built
- execute scenarios:
  - install kyma current release + fast integration
  - install kyma main + fast integration
  - install kyma previous release + fast integration; upgrade to kyma current release + fast integration
- all scenarios will be executed on a k3d cluster
- new jobs are documented

**Comment by k15r** [comment]
Question:

**Comment by jeremyharisch** [comment]
@k15r We do not want to use old CLI to install previous Kyma version. The pipeline should update the reconciler dependency with the image from this PR as in the other pre pipelines. Because we want to check that the new reconciler version is also capable of installing the previous kyma version

**Comment by mfaizanse** [comment]
- Scenarios:
  - Install kyma current release + fast integration [PR: https://github.com/kyma-project/test-infra/pull/5078]
  - Install kyma main + fast integration [PR: https://github.com/kyma-project/test-infra/pull/5078]

**Comment by mfaizanse** [comment]
Improvement PR: https://github.com/kyma-project/test-infra/pull/5133

**Comment by mfaizanse** [comment]
Documentation is updated!
