### ISSUE TITLE
Scheduler sets cluster-state to 'reconciling' even when component-reconciler is down

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#82]
**Description**

Scheduler is setting the cluster state to `reconciling` even when the component-reconciler is not reachable. This is bascially acceptable, but it should retry to connect to the component-reconciler or set the cluster state to failed.

**Expected result**

Cluster state is either not changed or set to failed when the component-reconciler cannot be reached.

**Actual result**

Cluster state is set to `reconciling` but scheduler doesn't retry to connect to the component-reconciler. The inventory is also not returning this cluster when querying for "clusters to reconcile" because it considers only clusters which are in `error`, `failed` state or which are too old.

**Steps to reproduce**

Start ms-reconciler and register a new cluster without starting the required component-reconcilers.

**Troubleshooting**

**Comment by suleymanakbas91** [comment]
With the latest changes, the cluster state is now set to `error` when the component reconciler is not reachable.
