### ISSUE TITLE
Introduce `updateOperation` function to `reconciliation.Repository` to avoid multiple small updates

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#842]
**Description**

Currently, in the HTTP endpoint are many small update operations executed when finishing an operation. To improve the execution time and to reduce amount of DB calls, all these small update-calls should be bundled to one call.

See https://github.com/kyma-incubator/reconciler/pull/840/files#diff-69a27ab3e82896ad31ecd173de047c6f6c16015856b3b61a73d6d5de0ce2947cR858-R879 => all these updates could be bundled after supporting a `reconciliation.UpdateOperation(*model.OperationEntity)` function.

**Reasons**

Reduce amount of small DB queries.

**Attachments**

**Comment by janmedrek** [comment]
Functionalities of the Reconciler were migrated to the new architecture, this issue will not be worked on.
