### ISSUE TITLE
Istio-configuration failed to generate Istio configs from file error

### ISSUE THREAD

**Issue by mjakobczyk** [kyma-incubator/reconciler#868]
**Description**

Istio is installed and upgraded through istioctl which accepts Istio Operator definition from file. As a result, we create a temporary file containing the rendered content and pass it as an input to the binary. Sometimes we encounter `failed to generate Istio configs from file` error, however. Here is the example og:

```log
log:2022-02-23T14:53:11.826808183Z stderr F {"level":"INFO","time":"2022-02-23T14:53:11.826Z","message":"Error: failed to generate Istio configs from file [/tmp/temp-file-4276575962.yaml] for the current version: 1.11.4, error: copy: unexpected EOF","correlation-id":"cc15fc99-d837-4168-9136-91fbed88d8d2--83fc3a0d-8fd0-4790-8433-7a78926dfdb0","component-name":"istio-configuration"} @timestamp:Feb 23, 2022 @ 15:53:11.964 kubernetes.pod_name:istio-configuration-reconciler-7d4fdf9748-mplgp kubernetes.namespace_name:kcp-system kubernetes.pod_id:f9a63e4b-0dad-437d-8464-05169467b10b kubernetes.labels.component:istio-configuration kubernetes.labels.kyma-project_io/component-reconciler: kubernetes.labels.pod-template-hash:7d4fdf9748 kubernetes.labels.security_istio_io/tlsMode:istio
```

**Expected result**

We should be at least aware of why the error happened.

**Actual result**

Problem occurs randomly.

**Steps to reproduce**

We do not know how to reproduce it.

**Troubleshooting**

Performing reconciliation loop once again may resolve the problem.

**Comment by mjakobczyk** [comment]
After investigations with @piotrkpc it looks like file could not be empty because there is a different error in such situation. Example:

```bash
touch /tmp/foo
istioctl upgrade -f /tmp/foo
```

Moreover, it can not be a problem with a not created file. We [handle such situations](https://github.com/kyma-incubator/reconciler/blob/2b2d639360dbac43176ec70f918dbcf4564d47ad/pkg/reconciler/file/path.go#L34) and none of these errors are present in the log. As a result, file was created.

**Comment by strekm** [comment]
implement feature flag which would log istiooperator file when istioctl binary returns an error

**Comment by veichtj** [comment]
Feature Log of Istio Operator file is enabled on all SKR environments.
Waiting for further analysis

**Comment by veichtj** [comment]
With new istio 1.12 version the issue seems to be gone and is not reproduceable.
