### ISSUE TITLE
Check if it is possible for Istio-configuration to use istio/client-go instead of istioctl

### ISSUE THREAD

**Issue by mjakobczyk** [kyma-incubator/reconciler#870]
**Description**

Until now istio-configuration component reconciler uses istioctl. There are several problems and limitations that are connected with this approach. As a result, we should validate the possibility of providing an implementation which adapts istio/client-go library.

**Reasons**

Advantages:
- we get rid of I/O problems
- testing will be much easier - instead of validating binary output we will rely on library API
- there will be no headache over choosing exporting `ISTIOCTL_PATH` anymore - neither in reconciler nor anywhere else

Things to consider:
- our custom mechanism of choosing version has to be adjusted properly
- versioning of the library and our way of adjusting to it
- deprecation of current mechanism
- checking if library offers the same set of functionalities as istioctl does

**Attachments**

See example Istio error that we randomly encounter with no clue how to deal with it: https://github.com/kyma-incubator/reconciler/issues/868
Istio/client-go: https://github.com/istio/client-go

**Comment by strekm** [comment]
istio reconciler will be rewordek into istio manager
