### ISSUE TITLE
Istio-configuration performer should be split between actions

### ISSUE THREAD

**Issue by mjakobczyk** [kyma-incubator/reconciler#874]
**Description**

In istio-configuration there is an `IstioPerformer` interface. For now it is shared among all actions. It should be split to smaller units and not be shared across all actions.

**Reasons**

After the refactoring was done for splitting main reconcile action to pre- main- and post- the performer was still untouched. Tests are hard to read and maintain and also do not test stuff from utility point of view.

**Attachments**

```go
type IstioPerformer interface
```

**Comment by strekm** [comment]
istio reconciler will be reworked into istio manager
