### ISSUE TITLE
Enhance cleaner-module in mothership to NOT remove the latest reconciliation

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#884]
**Description**

The existing deletion strategy for removing reconciliation data entries has to be adjusted a bit: 

1.  any reconciliation which is older than Y days is deleted except it is most recent reconciliation - this should survive always.

2. any reconciliation between now and Y days is NOT deleted if

    2.1 the reconciliation is one of the most recent X reconciliations of a cluster
    2.2 or if the reconciliation finished with a non-ready state

This is required to avoid that histories of a non-successfully reconciled cluster got empty over time.

**Reasons**

Avoid deletion of the latest reconciliation which is in a non-successfully state to avoid "history less" reconciliation entries.

**Attachments**

**Comment by Tomasz-Smelcerz-SAP** [comment]
See also: https://github.com/kyma-incubator/reconciler/issues/668

**Comment by Tomasz-Smelcerz-SAP** [comment]
PR for the issue: https://github.com/kyma-incubator/reconciler/pull/912
