### ISSUE TITLE
Setup Prometheus monitoring for component reconcilers

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#902]
**Description**

Monitoring of component reconcilers is mandatory for establishing operational readiness. Currently, the monitoring is limited to a few figures and cannot be extended in an easy way. 

To achieve an extendable and future-proof monitoring approach, a pure Prometheus based solution has to be establishe.

AC:

* Component reconcilers have to export monitoring values by providing Prometheus scrape endpoints
* Prometheus is already running in each KCP cluster and has to be configured:
     *  Define [ServiceMonitor](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/getting-started.md#related-resources) CRs to scrape component-reconciler metrics
     * Custom [PrometheusRules](https://github.com/prometheus-operator/prometheus-operator#customresourcedefinitions) have to be defined to provide metrics (e.g. aggregated avg-values calculated on base of all component-reconciler metrics)
* the custom implementation for reporting metrics from component-reconcilers to the mothership-reconciler (e.g. occupancy tracking, component processing KPIs etc.) has to be removed: the mothership reconciler should not be used for any calculation of metrics based on DB queries. Such information has to be either directly reported to or calculated by the Prometheus server.

- [x] #903

- [x] #907
- [x] #930 
- [x] add grafana dashboard to monitor exposed metrics

**Reasons**

Establish standardised monitoring approach for reconciler (mothership + component reconciler).

**Attachments**

**Comment by janmedrek** [comment]
Functionalities of the Reconciler were migrated to the new architecture, this issue will not be worked on.
