### ISSUE TITLE
Introduce batch delete to remove reconciliations

### ISSUE THREAD

**Issue by adityabhatia** [kyma-incubator/reconciler#918]
Currently reconciliations can only be removed one by one, taking a long time for the cleaner to delete obsolete entities #912.
This PR enables batch delete of these reconciliations.

Miscellaneous:

Removed explicit cleanup of schedular_operations table (initially required by sqlite), now done via Delete Cascade (postgres)
Max batch length set is 200, if exceeded it is split into sub-batches

**Comment by janmedrek** [comment]
Functionalities of the Reconciler were migrated to the new architecture, this issue will not be worked on.
