### ISSUE TITLE
Add Istio upgrade necessity checking

### ISSUE THREAD

**Issue by mjakobczyk** [kyma-incubator/reconciler#926]
**Description**

`istio-configuration` component reconciler should fire Istio upgrade on reconciliation loop only if Istio spec on the cluster is different than what we provide as operator.

**Reasons**

Skipping unnecessary Istio upgrade would save a lot of computing time.

**Attachments**

Check Istio upgrade sources for possible solutions on how to perform such check.

**Comment by strekm** [comment]
TODO:
- implement feature flag
- implement a check if istioctl apply is needed
- implement a check if patching webhook is needed
