### ISSUE TITLE
Improve Istio status reporting

### ISSUE THREAD

**Issue by mjakobczyk** [kyma-incubator/reconciler#927]
**Description**

Our `actions.IstioStatus` struct is a simple value object. We have many private functions working on the struct which even convert its properties to our `helperVersion` struct to perform easy semantic comparisons. We tie checks performed as part of private functions logic to this struct and make it re-useable by many reconcile actions.

**Reasons**

Any refactoring that sticks to `canInstall()` and `canUpdate()` functions or comparing versions is scattered across many places. It should be unified and easy to maintain and extend.

**Attachments**

`IstioStatus` struct - https://github.com/kyma-incubator/reconciler/blob/67d6459b9b280ec7895d254d5df3f5330c03bb5b/pkg/reconciler/instances/istio/actions/performer.go#L39
`helperVersion` struct - https://github.com/kyma-incubator/reconciler/blob/67d6459b9b280ec7895d254d5df3f5330c03bb5b/pkg/reconciler/instances/istio/action.go#L312

Additionally the Status struct is build with strings instead of `semver.Version` , but the logic in the code assumes it is in a compatible format. We get frequently error that mention something like "is not in dotted-tri format. 
The IstioStatus struct should be build with proper version and a builder should check the correct format.

**Comment by barchw** [comment]
PR: https://github.com/kyma-incubator/reconciler/pull/1143
