### ISSUE TITLE
Encryptor does not catch decryption Error - When components are encrypted with wrong key

### ISSUE THREAD

**Issue by jeremyharisch** [kyma-incubator/reconciler#944]
**Description**
Encryptor does not catch decryption Error if `component` column in cluster_config table is encrypted with different key.
Thus, the marshaller tries to unmarshall the encrypted string into the `ClusterConfiguartionEntity` struct, which resolves in the following error:
```
invalid character 'e' looking for beginning of value
```
This error does not give valuable feedback what happened, since it appears in the wrong place.

**Expected result**
Should throw error in encrytor, when decrypting the components column.
In this function: https://github.com/kyma-incubator/reconciler/blob/main/pkg/db/columnhandler.go#L288

**Actual result**
Error gets thrown in unmarshal function.

**Steps to reproduce**
1. Have a running Postgres DB in place
2. Insert various clusters
    1. `kubeconfig` is encrypted with correct encryption key 
    2. `components` is encrypted with different encryption key
3. Start mothership and component reconcilers

Please keep the following ticket in mind, they could be solved together: https://github.com/kyma-incubator/reconciler/issues/936
 

**Troubleshooting**

**Comment by janmedrek** [comment]
Functionalities of the Reconciler were migrated to the new architecture, this issue will not be worked on.
