### ISSUE TITLE
Remove the internal component operations from the Component Reconciler

### ISSUE THREAD

**Issue by franpog859** [kyma-incubator/reconciler#946]
**Description**

Currently, at least one Component Reconciler, in this case, Connectivity Proxy Component Reconciler, operates on a chart that is private, and therefore it requires a confidential token to work correctly. We should not use internal components. Luckily, Connectivity Proxy may make its chart public in the future. When it's done, we can remove the _private token operations_ from the Reconciler logic. All of the implementation you can find in [the linked PRs to this description](https://github.com/kyma-incubator/reconciler/issues/418#issuecomment-1057914073)

The change should consist of the `Cloner` implementation modification, the Component Reconciler chart simplification in the `control-plane` repository, adjustments in the development environments configs, removal of the git-token secrets on these environments, and update of the internal development documentation

**Currently, it's blocked by the Connectivity Proxy chart being internal. Let's wait for it to be public**

**Reasons**

There is no use case of operating on internal/ private components in the Reconciler. A Kyma user can install some private components on their own

**Comment by janmedrek** [comment]
Should be solved by: https://github.com/kyma-project/kyma/issues/15524
