### ISSUE TITLE
P1: Ensure CRDs and ISTIO are always installed before any other components will be installed

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#95]
**Description**

Kyma has a few mandatory resources which have to be installed before any other component can be installed. These are:

* Kyma CRDs
* ISTIO component

To ensure both resources are available, the mothership-reconciler has to take care that

1. CRDs are always installed at the very beginning of each reconciliation run
2. ISTIO is also installed at the very beginning but only if it's part of the components-list for this cluster

After the reconciliation of CRDs and ISTIO is finished, all other components listed in the component-list of the cluster will be reconciled.

AC:
* Mothership-reconciler always installs CRDs first
* Mothership-reconciler also installs the ISTIO component first but only if it's listed in the components-list of the cluster

**Reasons**

Ensure resources which are common pre-requisites for Kyma components are made available before the reconciliation of these components starts.

**Attachments**

**Comment by suleymanakbas91** [comment]
With #104, I've introduced two new configurations `preComponents` and `crdComponents`: https://github.com/kyma-incubator/reconciler/blob/main/resources/reconciler/charts/mothership-reconciler/values.yaml#L57

Scheduler reconciles the crdComponents first, then preComponents and then the rest: https://github.com/kyma-incubator/reconciler/blob/main/pkg/scheduler/scheduler.go#L103
