### ISSUE TITLE
Deprecate `local` and `test` command in mothership CLI

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#954]
**Description**

The need for the `mothership local` and `mothership test` command is no longer given since the Kyma CLI is using the reconciler internally and widely used for testing the reconciler on a local system.

Therefore, we can start to remove the initially created command for testing the reconciler locally:
* `mothership local`
* `mothership test`

AC:
* Define date for final deletion of the command and let the command fail when the date is reached
* Deprecate the command and add a hint when the deletion of this command will happen
* Align with the team whether we should return an >0 exit code to indicate the command is no longer intended to be used
* Remove the code after the deletion date is reached

**Reasons**

Consolidate old command structures in mothership CLI.

**Attachments**

**Comment by janmedrek** [comment]
Functionalities of the Reconciler were migrated to the new architecture, this issue will not be worked on.
