### ISSUE TITLE
Auditlog shipment not working

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#959]
**Description**

The auditlog integration of the mothership reconciler is not correctly working and needs a refinement:

* IP address reported to auditlog server has to be valid (currently is  `-` communiated which is invalid)
* Only requests to mothership which are modifying data (no GET-calls) have to be reported to the mothership
* @rakesh-garimella supports in setting up a monitoring for the fluent-bit auditlog reporter

**Expected result**

Audiglogs are properly send to the auditlog server and including a valid IP address.

Only modifying data requests have to be reported to the auditlog server. Data reading requests which are not touching sensitive data (not the case in mothership reconciler) have to be ignored.

**Actual result**

IP address send to auditlog server is invalid. Alsio GET-calls are reported to the auditlog server. Issues in fluentbit are not reported to monitoring system.

**Steps to reproduce**

**Troubleshooting**

**Comment by jakobmoellersap** [comment]
After initial analysis it seems that the header `X-Envoy-External-Address` based on https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#config-http-conn-man-headers-x-envoy-external-address was used previously. Maybe there was a regression causing this not to be filled any longer. I will update the code to not include GET requests as well as define a sane default for the IP to not fail entirely on not having any IP. When the IP is set we can still use it but I would need more input here @rakesh-garimella @tobiscr

**Comment by jakobmoellersap** [comment]
As we are probably not gonna receive the updated IPs from XFF i included some fallback logic to simply omit the IP as this will still submit successfully into the Audit Log

**Comment by rakesh-garimella** [comment]
The fluentbit updates have been done here: https://github.com/kyma-project/third-party-images/pull/208

**Comment by jakobmoellersap** [comment]
As was described in the above mentioned issue #1006 we need to rethink how we use audit log. Currently we use an http middleware which is causing WAY too many requests against our intended purpose. Ideally what we want is selective audit logs only for relevant security events. (for reconciliation this would be cluster creation/update). As this affects the kubeconfig and thus the security relevant details of the runtime.

**Comment by jakobmoellersap** [comment]
Shipment working as expected now, we will have an independant follow-up on the implementation here
https://github.com/kyma-incubator/reconciler/issues/1056
