### ISSUE TITLE
Resolve CustomResourceDefinition is deprecated warning

### ISSUE THREAD

**Issue by ruanxin** [kyma-incubator/reconciler#975]
At the moment, this deprecation warning is flooding our logging system,
Fix CRD manifest to resolve this issue.

```
2022-03-29T16:10:49.533436198Z stderr F W0329 16:10:49.533279       1 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
```

https://kibana-sf-558ad93f-5db5-4608-8cbf-061dac3471ff.cls-02.cloud.logs.services.eu10.hana.ondemand.com/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-7d,to:now))&_a=(columns:!(log),filters:!(),index:'14924510-9c02-11eb-8771-5dea5972a9ee',interval:auto,query:(language:lucene,query:'log:%20%22*CustomResourceDefinition%20is%20deprecated%20in%20v1.16%2B*%22'),sort:!())

**Comment by tobiscr** [comment]
Duplicated in Kyma backlog. Closing this one.
