### ISSUE TITLE
[Istio reconciler] proxy reset job should put annotations on failed pods

### ISSUE THREAD

**Issue by strekm** [kyma-incubator/reconciler#984]
**Description**

Istio proxy reset post action is responsible to reset workloads after Istio reset. Rollout restart is only executed on pods which have parents. After determining entities restart is performed and progress is tracked. In some cases rollout restart ends up in errors (e.g. image pull back off) and action reports an error. This leads to failed kyma reconciliations. Stand alone pods are omitted, which might cause connectivity issues since Istio not guarantee that old sidecars will work with new Istio. 

Proposed solution is to annotate troublesome pods instead of failing proxy reset action. 

AC:
- [x] pods which can't be restarted should be annotated
- [x] omitted pods should be annotated
- [x] action never fails
- [x] troubleshooting guide with workaround created (delete pods)
- [x] reconciler bumped in control-plane

**Expected result**

proxy reset never fails, failed pods are annotated

**Actual result**

proxy reset fails on restarting pods

**Comment by strekm** [comment]
blocked by https://github.com/kyma-incubator/reconciler/issues/997

**Comment by jakobmoellersap** [comment]
#997 isn't blocking since yesterday as @tobiscr rollbacked the issue and corrected the mod files

**Comment by piotrkpc** [comment]
Merged in control-plane: https://github.com/kyma-project/control-plane/pull/1519
