### ISSUE TITLE
pre-main-reconciler-publish-pr-cli fails

### ISSUE THREAD

**Issue by piotrkpc** [kyma-incubator/reconciler#997]
**Description**

Job `pre-main-reconciler-publish-pr-cli` is failing constatly since today morning 
 - https://status.build.kyma-project.io/?job=pre-main-reconciler-publish-pr-cli

**Comment by tobiscr** [comment]
Reason is probably the mandatory security fixes applied in #992

**Comment by tobiscr** [comment]
Reverting this change for now, to unblock us: https://github.com/kyma-incubator/reconciler/pull/998

**Comment by tobiscr** [comment]
Root cause is `go.mod` of the CLI is configured to use Go 1.17 but the reconciler `go.mod` is still on 1.16. 

The pipeline was complaining about incompatible sub-libraries. Will will fix that by upgrading the reconciler to 1.17 (https://github.com/kyma-incubator/reconciler/issues/999)

**Comment by jakobmoellersap** [comment]
This has been solved.
